### ISSUE TITLE
wheelmap.org/ should show /map directly (no more wordpress on landing page)

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#101]
Tasks related to RoR
- [ ] redirect (and make sure we have no 404s)
- [ ] define menu links within rails app (also i18n)
- [ ] remove menu item "Karte"
- [ ] add "FAQ" between "Presse" and "Kontakt"
- [ ] make sure menu is consistent across all rails pages (also detail pages etc)
- [ ] double check that it looks good on mobile

Task related to Wordpress
- [x] wheelmap logo should always link to "/"
- [x] check implications for sub-domains and redirect (ask @Xylakant  )
- [x] define what "Home" is in the blog.
- [x] remove wheelmap-search from blog
- [ ] add "FAQ" to main menu of blog ("Karte" stays as is)
- [ ] add live counter in lower left in the same design as on wheelmap app.
- [x] double-check that we have no new 404s

**Comment by lennerd** [comment]
Nice! Looking forward to this! :grin:

**Comment by thermann78** [comment]
Due to end of february.

**Comment by holgerd** [comment]
@thermann78 Please let me know when you start this.

**Comment by thermann78** [comment]
When we decide just to setup the map as new landing site in WordPress, we
can switch immediately.

Am Freitag, 12. Februar 2016 schrieb Holger Dieterich :

**Comment by holgerd** [comment]
@thermann78 can you look through this task list and check off wordpress related things you've already done?

**Comment by thermann78** [comment]
Yeah, done. The rest of the WP-related part will only be done with the redesign/new template. This will take place around April.

**Comment by thermann78** [comment]
"add live counter in lower left in the same design as on wheelmap app."

Embed-code needed from @lennerd or Asquera.

**Comment by thermann78** [comment]
FAQ can't be moved at the current because it breaks the menu's layout if I add another item.
ATM it can be found under "Über Wheelmap - Häufig gestellte Fragen".
Must be done within redesign topics.

**Comment by thermann78** [comment]
"check implications for sub-domains and redirect (ask @Xylakant )"

No implications as just map has been set as default site in WP. No changes in cofiguration have further been done.

**Comment by thermann78** [comment]
"double-check that we have no new 404s"

Only URL that has been affected is wheelmap.org - and it just has changed its content, so 404s are impossible.
After implementation of the counter in the WP footer (task that hasn't really to do anything with the landingsite itself) all other tasks can be assigned to RoR-crew.

**Comment by lennerd** [comment]
@thermann78 A live counter can be implemented via the API endpoint: `/api/nodes/counts?api_key=YOUR_API_KEY`. As you can see, this needs to be done via the backend because the API key should not be public. If you need any further help, please contact me.

Example response:
`{"tagged":19165,"fully_accessible":9165,"limited_accessible":4547,"not_accessible":5453}`

**Comment by holgerd** [comment]
closing this in favor of #367
