### ISSUE TITLE
db/structure.sql automatically added to untracked area

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#110]
It seems as if after every change the file `db/structure.sql` is added automatically to the untracked list. To avoid manual work each time (to remove the file from the untracked list), we need to look into the settings.

```
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   Gemfile
#       modified:   Gemfile.lock
#       modified:   db/structure.sql
```

**Comment by schultyy** [comment]
We need to figure out why both `db/structure.sql` and `db/schema.rb` exist at the same time. From what I see we could get rid of `db/structure.sql` and keep `db/schema.rb`.

**Comment by lennerd** [comment]
Do we maybe need this file for the Travis tests?

**Comment by schultyy** [comment]
Rails automatically generates a file containing the current database schema. By default it's `db/schema.rb` but you can decide that you want to have `db/structure.sql` instead. As far as I know, `db/structure.sql` is needed only if we're using more database specific features like Triggers, Stored Procedures etc. But from what I can see this is not the case.
