### ISSUE TITLE
Update node without phone number

### ISSUE THREAD

**Issue by timfreiheit** [sozialhelden/wheelmap#117]
Hi,
we had the request to remove the phone number as an editable field.
But it seems to be not always possible to update a node without the phone number parameter.
The node already has an phone number set with an incorrectly formatted number.

Request Put:    
```
http://staging.wheelmap.org/api/nodes/1110830682.json?api_key=XXXXXXXXXXXXX&name=Lacoste&type=clothes&lat=52.5162143&lon=13.3887506&wheelchair=no&wheelchair_toilet=unknown&category=shopping&wheelchair_description=test&street=Friedrichstra%C3%9Fe&housenumber=158&city=Berlin&postcode=10117&website=http%3A%2F%2Fwww.lacoste.com&locale=en

````

Response:    
```json

{
  "error": {
    "phone": [
      "Telefonnumer ist nicht korrekt. Die Telefonnummer muss im folgenden Format eingegeben werden: +49 30 234567"
    ]
  }
}

```

**Comment by holgerd** [comment]
@lennerd can you help out?

**Comment by lennerd** [comment]
Sorry, no time for this. @schultyy Can you take a look?

**Comment by schultyy** [comment]
yep, I can check that

**Comment by schultyy** [comment]
@timfreiheit I deployed a fix on staging.wheelmap.org. Now phone numbers are not validated anymore. Can you test if that's working for you now?

**Comment by timfreiheit** [comment]
@schultyy looks good. thank you

**Comment by schultyy** [comment]
Ok then I prepare a production deployment.

**Comment by schultyy** [comment]
It's now available on wheelmap.org.
