### ISSUE TITLE
Create Wildcard cert for *.wheelmap.org

### ISSUE THREAD

**Issue by Xylakant** [sozialhelden/wheelmap#132]
We need to secure multiple hosts in the wheelmap.org domain space. A wildcard cert would be the best option, as an alternative we could use a Multi-Domain certificate if we can list all domains we're using.

**Comment by Xylakant** [comment]
CSR:

-----BEGIN CERTIFICATE REQUEST-----
MIIE+zCCAuMCAQAwgYwxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCZXJsaW4xDzAN
BgNVBAcMBkJlcmxpbjEaMBgGA1UECgwRU296aWFsaGVsZGVuIGUuVi4xFzAVBgNV
BAMMDioud2hlZWxtYXAub3JnMSYwJAYJKoZIhvcNAQkBFhdob3N0bWFzdGVyQHdo
ZWVsbWFwLm9yZzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMAU1CJ2
BfF9/lUPrtq5tmDv11PtJduub3U/VCdeSD7d4JflKyMsAq0BkwvIik4bRIxnfP2B
QF2nDH3zfSfMUgIL1rBbyEtltSxkbohWbPv8NVrJQbeHCqmc2NKy5FkKVJo0I8Mi
HblF6h6Rf5HB8yAj61Oti292LwE7i1R4j0YPhA2LNKBGw9FXJcsjPJQuJSs7gCW1
6Vdq8lnB4h7tbtmfl9zufIg+XCUiS+UJOwHSeY/n2DkZceCCt9uR6XXCnTQJIxX5
CQdqBstRWhEmja2KUtOOc1DMNVv4hXJ+voBqSS7+/8F/1sav6VZYH+ucQvM7CrPC
COSaVqwbhbPNBnF2ne+7HyFtQd4Pcw/uRKB6mDqpPYzg2Virgm/HLS9iMa8xRzWc
z6KaXG07LUT6NSAcJ4Q8OguN1MCcasG5b9k331+gctl8mJ9g/7bMW+6ync/IbHYo
+sP7Yg3erXO59YVJTfcObjUWxbaETAyeddb6S14F5fJyGp5xw9dKvFp4ZcJxdZT1
X+16qea00YopqbQI7AUAQynzpBKuWqUNBfsFNRN632LunS1PSL+dz2oR4jmvLnN1
qfQ1vDgGaFzuHqgEcWsKIh0lQHCmI4XVz2tYs3Hm16ivLHsQbQ9xrRi56NCqfInq
hkxYpVTSvRriSqYp5LYCQ6Lpw/Mjnx8LX2p1AgMBAAGgKTAnBgkqhkiG9w0BCQ4x
GjAYMAkGA1UdEwQCMAAwCwYDVR0PBAQDAgXgMA0GCSqGSIb3DQEBCwUAA4ICAQCJ
e17rHF++5TNUYVWPE1t5ZMBEHJywyQPkDyjavr2RfHPX89GZA07bMSaTGt/haUNU
9r1bU4dzprwdrUx69HcbTNjLUKBPiItnPvRgtLepnXQmrFHK3ooHJ/ToKrYSzVyG
KlLdPkCnlKqNH76yzlq2OYL+Yovwd4zjJdVGxdPTRa6u2gt7Ded8HfGK+byutNcw
e0wKc6dZKbaWgEa5z9YPTJYrWo8BLRv/Q+kGfRQYvG+Sz+IbiAZbBAYTHuEOn9Ad
BsQJYiuXwEceHiez3n7YupyFe6mXAzlevj00KMHoyiCLVdKe7627Q//jxII9ko1B
huavyRH4QYvbcsisSSKt5nOBOm3lik5TjZ6N4U3e1AA6OpaHVWYaikKJ9Dt5OF5S
fq9QmjcJ/TvJ5heSkTisI++nfOMTqeqpB7STaRmfAlFP2cq6sB53CGCel5fL2luJ
X9foeyERXfVlf3/PoAuxrRJOB6/SZyjdzAmeJFk44usTtuz0QTC+wcmevYblAJeX
7hqKxS7jisB/18TCPHhO5rLOY0iMKm6L7Cv9Xyurl/dwuD2Ql5fkHuHOv2brOarC
u/Reawl5WnnpHOF6BdaeZWc0tbi3rJyO1LxPqh9oBgEuhcOpF0USvt3ujuR90KzA
GezJwR+CZq71br2JL4ggi4nYudsEhUDNIV3LbBuN2w==
-----END CERTIFICATE REQUEST-----

**Comment by Xylakant** [comment]
This csr should work with comodo or digicert or similar. A wildcard cert costs about 400 USD. Comodo does not offer Multi-Domain (SANS) certificates, digicert does. A Multi-Domain certificate is slightly cheaper with about 300 USD for a one-year certificate https://www.digicert.com/unified-communications-ssl-tls.htm

If we prefer a Multi-Domain cert, I need the list of domains that should be secured (don't forget to list the country-specific domains)

**Comment by holgerd** [comment]
Ok we are creating hostmaster@wheelmap.org now. ;)

**Comment by Xylakant** [comment]
well, I can change the email address in the CSR :). Having the hostmaster email is in general a good thing though.

**Comment by holgerd** [comment]
done.
