### ISSUE TITLE
Ensure that the widget loads only protocol relative resources

### ISSUE THREAD

**Issue by Xylakant** [sozialhelden/wheelmap#135]
Loading of plain-http resources is disabled for TLS-protected resources, so the widget itself must not load any resource from plain http when it's loaded embedded on an https-enabled site. Either protocol-relative URLs should be used or as an alternative, all resources should be loaded via https only.

**Comment by lennerd** [comment]
Fixed via https://github.com/sozialhelden/wheelmap/commit/368872e1c71d046cfd9632046c538bd16723c2df
