### ISSUE TITLE
custom (& funny) 404 error pages

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#137]
Let's create a funny 404 page (eg. http://wheelmap.org/nothinghere ).

photo suggestion (also attached):
https://www.facebook.com/photo.php?fbid=10151263184251247&set=a.10150460337231247.375283.534621246&type=3&theater

![404_raul](https://cloud.githubusercontent.com/assets/218506/13048979/de952db4-d3e9-11e5-9457-3e2ae0d1c830.jpg)

**Comment by lennerd** [comment]
We should deal with this problem. The current page is just a blank page with a header. 

@1000miles @schultyy Is it possible to create a 404 page which is at the same time a 301 redirect? I thought about simply showing the map with a flash message.

**Comment by schultyy** [comment]
You can either have a 404 or a 301 but not both at the same time.

**Comment by schultyy** [comment]
One option here would be to show a 404 page with the image Holger posted or to have a 301 redirect with a flash notice afterwards that for example the node couldn't be found.

**Comment by Xylakant** [comment]
You want a 404. A 301 only makes sense if we can actually redirect the user to a page that makes sense in the context. Delivering a 404 not only indicates to the user that the page does not exist, it also indicates to robots (think google) that the page does not exist. Returning a 301 would just be plain  wrong.

**Comment by Hoverbear** [comment]
<img width="700" alt="screen shot 2017-01-10 at 11 38 20" src="https://cloud.githubusercontent.com/assets/130903/21803207/5bc2a2f6-d729-11e6-9d0d-0e3ba576d380.png">

There is a current 404 page which is served by Wordpress.

This is what is served if you query a node which doesn't exist, for example:

<img width="700" alt="screen shot 2017-01-10 at 11 40 56" src="https://cloud.githubusercontent.com/assets/130903/21803293/c4b0c072-d729-11e6-964d-8db40dbe2c1f.png">

We'd like to replace that.

**Comment by lennerd** [comment]
btw. there is written some error message beneath the header. 🙈
