### ISSUE TITLE
Massive import

### ISSUE THREAD

**Issue by cdupoiron** [sozialhelden/wheelmap#150]
Hello,

I'm sorry, It's not an issue...
I have a CSV file of 300 wheelchair-accessible parking and I'd like to import them.

My csv file is like this : 
![image](https://cloud.githubusercontent.com/assets/4683624/13115910/0b291398-d59a-11e5-944b-8d708c651f42.png)

Do you have any advice to do it?

Thx in advance :)

**Comment by holgerd** [comment]
Thanks for your offer! Wheelmap is a project based on OpenStreetMap (OSM), so an import has to be made to OSM and then will automatically show up on Wheelmap. Having said that, it is good practice to discuss any bulk import with the OSM community first.

This is a good starting point:
http://wiki.openstreetmap.org/wiki/Import/Guidelines

It is also a good idea to discuss your import and/or ask for help at the imports mailing list here:
https://lists.openstreetmap.org/listinfo/imports

Does this help?

**Comment by cdupoiron** [comment]
Thank you for your help :)

**Comment by holgerd** [comment]
Did you take any actions? If not, I'm happy to help!

**Comment by cdupoiron** [comment]
No :(
I'm looking for a way to test each import before doing it, to know if it's a duplicate or not. I plan to do it next holidays :)

**Comment by holgerd** [comment]
I know the OSM [guidelines](http://wiki.openstreetmap.org/wiki/Import/Guidelines) may seem like a daunting process, but my experience is that engaging with the community early on helps a lot. I suggest you simply put the CSV somewhere on the web (github, Google Spreadsheet, whatever) and post the link to the [imports mailing list](https://lists.openstreetmap.org/listinfo/imports). Maybe somebody else can import it or help you do it. I can also lead the discussion on the list if you want.
