### ISSUE TITLE
API-Error

### ISSUE THREAD

**Issue by thermann78** [sozialhelden/wheelmap#162]
I keep getting error 500 for the following API request:

`http://wheelmap.org/api/categories/9/nodes?api_key=(key)&bbox=13.341,52.505,13.434,52.523&per_page=10&wheelchair=yes`

My request is exactly constructed like described in the API doc (http://wheelmap.org/el/api/docs/resources/nodes: "This resource can also be nested within categories or node_types.
http://wheelmap.org/api/categories/1/nodes?api_key=api_key&bbox=13.341,52.505,13.434,52.523&per_page=10&wheelchair=yes").

What did I do?
I replaced the sample category number by 9 and putted in my API key, that's all. The result is an error 500.

My expectation would have been to get a return of all wheelchair accessible accomodation nodes around Berlin. Not sure but I think once some months ago this request had been working...

**Comment by lennerd** [comment]
It's a big caused by inherited_resources in 1.6, which got pinned in the current master by 099e5a81cb294bbca78c2edf0e4dc03c4045297b. It's related to #148 and working as expected on staging.

@schultyy @1000miles Is the current master ready for deployment?

**Comment by schultyy** [comment]
@lennerd From my side it's ready (I didn't merge anything in master this week).

**Comment by 1000miles** [comment]
@lennerd yes, from my side, too.

**Comment by lennerd** [comment]
Fix is deployed on production.
