### ISSUE TITLE
http://wheelmap.org/node_types returns blank page (http 406 error)

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#166]
- I open http://wheelmap.org/node_types on my chrome/mac (tried this logged-in as admin and in incognito mode)
- I expect the list of all nodey-types to show up
- Instead, I see a blank white page. The HTTP Response according to http://web-sniffer.net/ is a 406 error (see below)

=============

HTTP Request Header

Connect to 141.101.125.177 on port 80 ... ok

GET /node_types HTTP/1.1[CRLF]
Host: wheelmap.org[CRLF]
Connection: close[CRLF]
User-Agent: Web-sniffer/1.1.0 (+http://web-sniffer.net/)[CRLF]
Accept-Encoding: gzip[CRLF]
Accept-Charset: ISO-8859-1,UTF-8;q=0.7,*;q=0.7[CRLF]
Cache-Control: no-cache[CRLF]
Accept-Language: de,en;q=0.7,en-us;q=0.3[CRLF]
Referer: http://web-sniffer.net/[CRLF]
[CRLF]
HTTP Response Header

Name	Value	Delim
Status: HTTP/1.1 406 Not Acceptable
Date:	Fri, 04 Mar 2016 08:34:08 GMT	
Content-Type:	text/html; charset=utf-8	
Transfer-Encoding:	chunked	
Connection:	close	
Set-Cookie:	__cfduid=(omitted by holger); expires=Sat, 04-Mar-17 08:34:08 GMT; path=/; domain=.wheelmap.org; HttpOnly	
X-UA-Compatible:	IE=Edge,chrome=1	
Cache-Control:	no-cache	
Set-Cookie:	geoip_lat=50.1167; path=/	
Set-Cookie:	geoip_lon=8.6833; path=/	
Set-Cookie:	flash=%7B%7D; path=/	
Set-Cookie:	_wheelmap_session=(omitted by holger); path=/; HttpOnly	
X-Request-Id:	ca603b2b1d1baf279c98a6c1c714e4d1	
X-Runtime:	0.019045	
X-Rack-Cache:	miss	
Server:	cloudflare-nginx	
CF-RAY:	27e3fcc1e78c2336-FRA

**Comment by 1000miles** [comment]
Hello Holger,

if you type the url `http://wheelmap.org/node_types.json` in the browser, you should be able to see the node_types list as a json-file. Is that enough for you to append `.json`to the url to see the values or do you want us to set json as default for the node_types output?

Happy to hear from you how to progress.

**Comment by holgerd** [comment]
It should return a publicly viewable html file. Check archive.org :)

**Comment by holgerd** [comment]
https://web.archive.org/web/20150318095607/http://wheelmap.org/node_types

**Comment by 1000miles** [comment]
@holgerd Thank you for the info. Will send a pull request today. :)

**Comment by holgerd** [comment]
This is not live yet, so I reopen this issue so that we don't forget it. Please deploy live whenever it is convenient for you.

**Comment by 1000miles** [comment]
We just deployed the fix of PR #168  on production today. As you may see under  `www.wheelmap.org/node_types` the poi translation issues on staging server don't apply to the live server. :)

![screencapture-wheelmap-org-node_types-1459417737874](https://cloud.githubusercontent.com/assets/4077916/14172305/b4fcdbf2-f737-11e5-9712-c83cdb855642.png)

**Comment by 1000miles** [comment]
@holgerd Can we close this now?

**Comment by holgerd** [comment]
sure. :)

**Comment by holgerd** [comment]
thanks!
