### ISSUE TITLE
OSM-Sync not working properly?

### ISSUE THREAD

**Issue by thermann78** [sozialhelden/wheelmap#189]
I have two issues that may indicate that we struggle with our OSM-Sync.

Issue 1:

- A user reported that he changed the node ID 595395687 but nothing had been affected. I looked it up in the OSM and found out that the last edit had been 5 days ago; later edits had not been recognized. 
- I tried to switch wheelchair status from limited to yes what didn't take any change in the OSM for more than an hour.
- Later I looked it up in OSM again and found out that someone had changed the POI via wheelmap what actually was taken over into the OSM. 
 
So it seems that the sync works, but it occurs that places aren't synced properly.

Issue 2:

- Via the new form on the Wheelmap webapp I created a test POI (ID 4118505992) on Wheelmap about 4 hours ago. In OSM it appeared immediately, but it won't show up in Wheelmap. You get a blank page if you try to open wheelmap.org/nodes/4118505992

**Comment by thermann78** [comment]
Seems this is not unique. Sync seems to fail sporadic.
We got two bug reports from a user today:

1.

> Bonjour Sozialhelden,
> something is wrong with location: http://wheelmap.org/fr/nodes/4054866647
>
> The problem is:
> Wheelchair accessibility should be «  Wheelchair accessible » but my modifications are useless, is 
> there a problem with this node? I can’t update it.

2.  (same user)

Hi

>  Sozialhelden,
> something is wrong with location: http://wheelmap.org/en/nodes/4088655695
> 
> The problem is:
> This place is a duplication of this node : http://wheelmap.org/en/nodes/4086581219
> Can you merge them?
> 
> I can’t see any of the 2 on the map, is there a problem with these nodes?

**Comment by thermann78** [comment]
Additionally to my last comment: I already checked out these two issues in my web browser (Safari 9.0.3) and found out, that in fact these two duplicate places aren't shown on the map.

**Comment by 1000miles** [comment]
There might be a connection between this issue and following ticket: https://github.com/sozialhelden/wheelmap/issues/184

We will put further research on this.

**Comment by thermann78** [comment]
Another bug report. If you query for "Adina Hotel Berlin" in Wheelmap, there is just a bbox result without a node. Query in OSM for example delivers node ID 4135629890 which isn't shown in Wheelmap. The provider of Adina Hotels itself tagged it one hour ago.
Just for protocol: I now did a change at the node in OSM to find out if this leads to a change in Wheelmap.

**Comment by thermann78** [comment]
Another occurence in Japan: POIs seem to be visible in OSM, but not in WM - http://overpass-turbo.eu/s/fMr

**Comment by a-di-na** [comment]
Concerning the "Adina Hotel Berlin" issue: There are 6 wheelmap search results, but only 2 of them are right/functional.
Adina Apartment Hotel Berlin Hauptbahnhof: http://wheelmap.org/nodes/3780043266
Adina Apartment Hotel Berlin Hackescher Markt: http://wheelmap.org/nodes/2796710200

Adina Apartment Hotel Checkpoint Charlie isn't shown in Wheelmap, but in OSM it is. :/

Both Adina Hotels in Frankfurt and Hamburg are shown right in wheelmap.org:
Adina Apartment Hotel Hamburg: http://wheelmap.org/nodes/1643184742
Adina Hotel Frankfurt: http://wheelmap.org/nodes/1163693609

**Comment by a-di-na** [comment]
Adina Apartment Hotel Berlin Hauptbahnhof: http://wheelmap.org/nodes/3780043266
Adina Apartment Hotel Berlin Hackescher Markt: http://wheelmap.org/nodes/2796710200
-> These hotels were updated by a user using wheelmap (phone number and website). But it doesn't appear in wheelmap. In OSM you can see the information.

**Comment by thermann78** [comment]
Another report from our friends in Japan:

> This is XXX of Hokkaido Univ. Wheelmap project and member of OpenStreetMap Foundation Japan
> 
> In Japan, about 2100 wheelchair tags have increased since last Mapmyday 
> by wheelmap user group and friends in japan
> http://qiita.com/Yfuruchin/items/f282d0b31dececbe233e   
> 
> As the partner group in Tokyo have technical question in Wheelmap
> Id like to ask you.
> 
> The group held the wheel-mapping party in Tokyo area, every month.
> http://yasashiitabi.sun.bindcloud.jp/mappingparty.html
> However the OSM data which have surveyed by participants in mapping party, 9th Apr,
>  could not reflect to wheelmap yet
> #the tag is making by OSM iD editor
> http://wiki.openstreetmap.org/wiki/ID
> 
> ____
> 
> for examlple this data is surveyed
> 
> ex1:
> 
> OSM
> http://www.openstreetmap.org/node/4109121814
> 
> Wheelmap
> http://goo.gl/VYDNUQ
> 
> ex2
> 
> OSM
> http://www.openstreetmap.org/node/4109115589
> Wheelmap
> http://goo.gl/GK9x54
> 
> ____
> 
> The participants enjoyed in Wheel-mapping party event, 
> but they are disappointing by these situation 
> and their motivation of wheelmapping is decreasing 
> 
> Could you check this situation on web system,?
> If we mistake the method of making data, please tell us the good methods in survey events. 
>

**Comment by Xylakant** [comment]
OSM sync is currently not working while we do database maintenance. Given that we're short on disk space on the server, that involves shuffling quite a bit of data around. The job has been running since yesterday afternoon and is still not done yet. I can't give an estimated time to finish either. I'll monitor the situation and update this ticket as the situation progresses.

**Comment by Xylakant** [comment]
To clarify: Data that has been passed on to OSM does not get synced back. Changes made on the wheelmap do get passed on to the OSM properly as far as we can see. Once the database is doing fine again, wheelmap should pick up the unsynced data.

**Comment by a-di-na** [comment]
Another user mail: 

Mir ist auf Wheelmap.org-Karte aufgefallen, das sich die Orte auf der Karte sich nicht
mehr bearbeiten lassen. Z. B. lassen sich die Namen nicht ändern, so wie der
Objekt-Typ, etc..
Beispiel: Salomon und Julie Kaufmann (http://wheelmap.org/nodes/3776285416) und
CoccoCurry (http://wheelmap.org/nodes/3712159090). Hier läßt sich nicht die
Barrierefreiheit dauerhaft einstellen.
Es werden auch noch Orte auf Wheelmap angezeigt, die auf OSM schon gelöscht
worden sind. Wie Barbara Flöter, Schuhe und Accessoires (http://wheelmap.org/nodes/559145953) und Dietz (http://wheelmap.org/nodes/3070240650). Im Umkreis von
ca. 500-600m wurden auch Orte gemapt, die auf der Wheelmap-Karte nicht angezeigt
werden.
Beim Bahnhofsplatz in 74321 Bietigheim-Bissingen wurden einige Punkte über
Wheelmap geändert und wird nicht ordnungsgemäß angezeigt.
Auf der Insel Rügen sind wir auch einige Orte aufgefallen, die sich leider nicht
richtig markieren lassen.

Können sie bitte den Problemen nachgehen, damit Wheelmap.org wieder
ohne Problme funktioniert.

Vielen Dank im voraus für ihre Mühen.

**Comment by Xylakant** [comment]
i was able to free some space for the database and the sync is running again. It might take some time to pick up. Some indexes need rebuilding, so we might still have a bit of a performance impact.

**Comment by thermann78** [comment]
Just a short backup after todays downtime: Node ID 4118505992 mentioned in my initalliy posting (last sentence) now finally appeared on Wheelmap. After confirmation that this part of the issue has been fixed I deleted the Node in the OSM as it has been a fictive location for testingpurposes.

**Comment by thermann78** [comment]
Finally I tested all the issues mentioned above. They all are fixed or can be explained by user mistakes, so the reason for our problems really seems to have been the HD overflow.
The count of our places has increased about 4.000 places over night :) 
And in the backend the latest POIs is no more dated on April 4th, but on April 25th.
I think this Issue can be closed now, but kept on mind for similar problems. 
Thx to @Xylakant and @1000miles!
