### ISSUE TITLE
Login staging kaputt

### ISSUE THREAD

**Issue by skade** [sozialhelden/wheelmap#19]
Siehe auch Fehlerreport von Tim Freiheit:

Der Login funktioniert über eine Webview auf der URL mit dem Entpunkt: /users/auth/osm allerdings verhält sich die Seite je nach User Agent unterschiedlich. Wir müssten wissen welcher Konvention nach das ganze funktionieren soll. Aktuell schicken wir den User Agent: "Wheelmap-DEV/77 (iPhone; iOS 8.4; Scale/2.00)" mit um das selbe verhalten wie bei der iOS-App zu erreichen.

**Comment by timfreiheit** [comment]
Wie sieht es hier mit dem Status aus?
Und wann ist damit zu rechnen, dass der neue Login in die Liveapi übernommen wird?

**Comment by holgerd** [comment]
@skade , kannst Du Dir das ansehen bitte?

Ist ein Blocker laut Tim/SMF:
"wir haben festgestellt, dass der neue Login-Prozess noch nicht in die Live-api übernommen wurde. Dies muss geschehen bevor wir eine neue iOS Version erstellen und bevor wir die Windows-Version einreichen, ansonsten können sich die User nicht einloggen/registrieren."

**Comment by joustava** [comment]
As I understood from @skade, there are two issues here:
1. Login flow on production(live) should be updated with latest login flow (from?).
2. There are differences in the UI/flow between mobile platforms? (what are the differences?)

**Comment by lennerd** [comment]
The production branch should include the new login features now. We have some problems withd deployment but the feature should work though.

@timfreiheit Does this help?

**Comment by timfreiheit** [comment]
@lennerd 
It is working now :)
What is about the User Agent?

**Comment by lennerd** [comment]
I will take a look. I'm not the one who implemented this but I will try to find out which User Agent is needed.

**Comment by lennerd** [comment]
@timfreiheit What exactly do you want to accomplish? Do you need some kind of User Agent implementation for the Windows Phone? The Android and iOS devices seems to be handled:

https://github.com/sozialhelden/wheelmap/blob/master/app/controllers/omniauth_callbacks_controller.rb#L10-L11
https://github.com/sozialhelden/wheelmap/blob/master/app/controllers/application_controller.rb#L93-L99

**Comment by timfreiheit** [comment]
the WebView from Windows Phone does not contain a unique User Agent for each app.
It seems to be enough that the user agent starts with Wheelmap. I will set it accordingly.

**Comment by lennerd** [comment]
Right. Please report if this works for you so we can close this issue.

**Comment by timfreiheit** [comment]
can be closed

**Comment by lennerd** [comment]
:+1:
