### ISSUE TITLE
Feedback from Team

### ISSUE THREAD

**Issue by lennerd** [sozialhelden/wheelmap#195]
- [x] Address was insert manually and new marker position was calculated while she tried to change the marker herself.
- [x] "Similar places was skipped, why?"
- [x] Placeholder were missing when content was insert
- [ ] Help format string for street address input field

**Comment by lennerd** [comment]
> Image Uploade

@holgerd What do you think? Do we need this?

**Comment by lennerd** [comment]
no image upload

**Comment by lennerd** [comment]
@1000miles @schultyy The team was giving feedback that it would be important for importing our data into the OSM that the provided street name cannot contain short version of `Straße` (e.g. `Str.`).

As we do the validation only on the server, I thought we maybe can add this validation there. What do you think?

**Comment by holgerd** [comment]
Why would it be important?

In general I do not think it is wheelmap's job to validate these inputs. AFAIK no other OSM editor does this. OSM ist based on conventions, not validations. Instead, we could link to the wiki page explaining the tag.

**Comment by lennerd** [comment]
Nice insights. Okay, that sounds like a good plan. Do you have a link we can use?

**Comment by holgerd** [comment]
I guess it's adr:street on this page: http://wiki.openstreetmap.org/w/index.php?title=Key:addr&uselang=en-US

Notice there is no mention that abbreviations are unwanted.

**Comment by lennerd** [comment]
Okay, nice. So I will add the corresponding PR to review.
