### ISSUE TITLE
Toilettenstatus aktualisieren in API

### ISSUE THREAD

**Issue by skade** [sozialhelden/wheelmap#20]
Vom Tim Freiheit:

Toilettenstatus akualisieren. (http://wheelmap.org/api/docs/resources/nodes)
Man kann über den Entpunkt "/api/nodes/{node_id}/update_wheelchair" den Status eines Nodes verändern. Ein Äquivalent gibt es für den Toilettenstatus allerdings nicht.
Im Idealfall für uns würde das über den selben Entpunkt laufen. Also beispielsweise mit 
"/api/nodes/{node_id}/update_wheelchair?wheelchair=yes&toilet=yes".

**Comment by lennerd** [comment]
@timfreiheit Is this still active? cc @joustava

**Comment by timfreiheit** [comment]
@lennerd yes

**Comment by christoph-buente** [comment]
This should have solved with this commit: 
https://github.com/sozialhelden/wheelmap/commit/5a7345637cde2dc8dbdb6eb1176b9562c070ec2d

**Comment by christoph-buente** [comment]
I just saw, that I updated the inline documentation with apipie, but I could not make it work in production. The old api documentation is still in place. I will provide an update for that.

https://rubygems.org/gems/apipie-rails

**Comment by timfreiheit** [comment]
the endpoint is still not reachable:
```
http://staging.wheelmap.org/api/nodes/13/update_toilet?api_key=XXXXXX&wheelchair_toilet=yes
```
results in:
```json
{
  "error": "No route matches '/api/nodes/13/update_toilet', check API documentation for available resources: /api/docs/resources"
}
```

**Comment by christoph-buente** [comment]
Hmm, the implementation is there, see

https://github.com/sozialhelden/wheelmap/blob/master/app/controllers/api/nodes_controller.rb#L184

But for some reason the routes seems to have gone. @lennerd can you check if it has been killed by a merge/rebase?

**Comment by lennerd** [comment]
@timfreiheit I updated the current master to have an `update_toilet` url. Does that fix your problem?

**Comment by timfreiheit** [comment]
@lennerd yes it looks good now. Thank you

**Comment by lennerd** [comment]
:+1:
