### ISSUE TITLE
Fix locate me button

### ISSUE THREAD

**Issue by lennerd** [sozialhelden/wheelmap#201]
The locate me button does not work in newest version of Chrome when visited via the `http` protocol.

**Comment by lennerd** [comment]
The solution would be to force to SSL. Can be configured via Cloudflare or directly in the Rails application.

**Comment by lennerd** [comment]
@Xylakant What do you think? PR for `force_ssl` or changing the Cloudflare configuration?

**Comment by Xylakant** [comment]
cloudflare is better. the redirect to ssl happens closer to the end user that way. We can still additionally enable force_ssl, it won't hurt.

**Comment by holgerd** [comment]
@Xylakant can you please implement this in the cloudflare configuration?

**Comment by Xylakant** [comment]
did we confirm that all mobile apps can handle that properly?

**Comment by lennerd** [comment]
What do you worry about in detail?

**Comment by Xylakant** [comment]
from the top of my mind, but not limited to:

 * apps not handling the redirect properly
 * apps having hard-coded entry points for a various actions
 * apps not handling redirects for post/put operations properly
 * apps not handling SSL properly at all

In general: things breaking in various catastrophic ways.

**Comment by lennerd** [comment]
I see. Best way then it is probably to enable it for staging and hope the apps has proper unit tests. @RaphaelHeber Would that work for you?

**Comment by Xylakant** [comment]
staging already force redirects. however, the app should use https by default. redirects cost a lot of precious time, especially on mobile connections.

**Comment by holgerd** [comment]
Okay since Tim from SMF is on vacation I have put this on the collection of tasks/ideas for the next assignment for SMF in basecamp

(internal reference: https://basecamp.com/2952602/projects/11430727/todos/256068741 )

**Comment by Xylakant** [comment]
ok, since we now enforce SSL for prod as well, this should be fixed
