### ISSUE TITLE
Relation exists in OSM but not in Wheelmap

### ISSUE THREAD

**Issue by thermann78** [sozialhelden/wheelmap#205]
We have a new user feedback concerning a duplicate entry. I did a little bit research and found out that there is a old relation with ID 349274 (Adina Appartement Hotels Berlin Checkpoint Charlie) as well as a new node with ID 4135629890. Provider has added the POI in Wheelmap as search didn't deliver any results. In fact the hotel already exists more than 6 years but is not shown in Wheelmap although it is type tourism=hotel.

Anyone can research why the relation hasn't been added to Wheelmap?

**Comment by holgerd** [comment]
Regarding http://www.openstreetmap.org/relation/349274/history vs. http://www.openstreetmap.org/node/4135629890/history

Relations are not supported by Wheelmap, only nodes and ways.

Duplicate to https://github.com/sozialhelden/wheelmap/issues/170
