### ISSUE TITLE
SSL Certification Error for staging.wheelmap.org

### ISSUE THREAD

**Issue by timfreiheit** [sozialhelden/wheelmap#212]
@Xylakant 
```java
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

**Comment by Xylakant** [comment]
we're using a self signed cert for staging. please use plain http for staging atm. we don't force-redirect so that shouldn't be an issue.

The ultimate goal is that staging gets SSL via cloudflare, just as prod does.

**Comment by lennerd** [comment]
@timfreiheit Does this work for you?

**Comment by timfreiheit** [comment]
it would if the assets api return links using http instead of https.
the normal api is accessed via http

**Comment by Xylakant** [comment]
ok, I see the issue.

**Comment by Xylakant** [comment]
staging is now handled via cloudflare as well, so it gets the same SSL setup as prod does. additionally, we now enforce SSL and forward to https if http is tried.

@timfreiheit can you confirm things are still working on your end?

**Comment by timfreiheit** [comment]
looks good. I can not find find any errors at the moment

**Comment by Xylakant** [comment]
ok, closing
