### ISSUE TITLE
Widget creator cannot change city

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#213]
User reports he cannot change the widget's city from Berlin to anything else. It always stays at Berlin. Svenja could replicate that behavior.

I could not replicate this systematically, but saw the error as well at least twice on my machine with different OSM-user IDs.

More testing needed.

**Comment by lennerd** [comment]
This has something todo with the difference of bounding box and a center returned by photon.komoot.de.

If you watch the generated code in the textfield below, you see, that it's still changing though. So the Widget generator is still usable and the Widget can be integrated without any problems.

**Comment by lennerd** [comment]
FYI: The error appears to be in the web app itself when a new bounding box is passed as a parameter. I will look into this.

**Comment by holgerd** [comment]
@lennerd so I can move this to "next" or are there any impediments?

**Comment by lennerd** [comment]
@holgerd Like I stated in Slack it would be nice to have you and Svenja to test the feature again and see, if everything is working fine.

But unfortunatly there is bug coming from this PR when the map is moved. You can test this on staging. Zoom in and than move the map. The map is moving back to the last position.

**Comment by holgerd** [comment]
@lennerd 

- I'm logged in on http://staging.wheelmap.org/profile/widgets as "holgerd" and see berlin engeldamm in the widget. I type in "berlin" and click the auto-suggest result. I see Berlin unter den linden. I click on "Profil" in the left menu bar and then on "Widget" to come back. I then type in "Freiburg" and click the auto-suggest
- I expect the widget to show the center of Freiburg
- Instead, it says in Berlin

**Comment by lennerd** [comment]
I will take a look on next Tuesday.

**Comment by lennerd** [comment]
@1000miles **Please do not deploy the current master on production.** I added a commit which tries to fix bugs but unfortunatly adding others. So this one needs to be reverted and added to a individual PR. I wil do this on next Tuesday.

See: https://github.com/sozialhelden/wheelmap/commit/3e37317c61c8bea9bc5fdd648d7e9c0c2d000ed9

**Comment by 1000miles** [comment]
@lennerd Okay, thanks for letting me know. :)

**Comment by lennerd** [comment]
FYI: This is on hold because I want to have #218 merged first to be able deploy #221 on staging.

**Comment by holgerd** [comment]
@lennerd I tried to test this but it does not work: 
- On https://staging.wheelmap.org/profile/widgets I entered "berlin" in the "Kartenausschnitt" input field and the autocomplete spinner shows up.
- I expect some suggestions to show up
- Instead, after 30s there are still no suggestions and nothing happens.

**Comment by lennerd** [comment]
WIll check and hopefully have a solution till tomorrow morning.

**Comment by lennerd** [comment]
@1000miles @schultyy I have problems with deploying new assets. The problem here is that we forget to use relative protocol in case a user uses requests the page via https. I can fix this locally. But when I deploy the new assets are not published. Any ideas? I'm not sure if it makes sense to build the files on the machine directly as they are shared?

**Comment by lennerd** [comment]
Just checked directly on the server. The files are correclty deployed. The precompiling though seems to pick the wrong/old file.

**Comment by lennerd** [comment]
I changed the wrong line of code. Now it's working. :see-no-evil: @holgerd It's working on staging now. Unfortunately the bounding box parameter is not shown correctly anymore. Working on it.

**Comment by lennerd** [comment]
@holgerd Deployed again on staging. Please review.

**Comment by holgerd** [comment]
@lennerd it works now on staging!
