### ISSUE TITLE
Error 403 when accessing api from Java

### ISSUE THREAD

**Issue by rabidllama** [sozialhelden/wheelmap#217]
I am trying to get a list of all POIs in a specific area via the API within a script that I have written in Java. It calls the address http://wheelmap.org/api/nodes?api_key=[api_key]&bbox=8.619423,49.369356,8.783105,49.435873 which returns a 403 forbidden message, but when I use the exact same url in a browser the data is returned as expected

**Comment by lennerd** [comment]
Do you have a error message coming with the 403 error? And can you tell us more about your Java implementation?

**Comment by rabidllama** [comment]
The message that comes back form the api is:
`java.io.IOException: Server returned HTTP response code: 403 for URL: http://wheelmap.org/api/nodes?api_key=[api-key]&bbox=8.619423,49.369356,8.783105,49.435873&per_page=100&page=1
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1838)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
	at WheelmapToGeoJSON.getData(WheelmapToGeoJSON.java:104)
	at WheelmapToGeoJSON.main(WheelmapToGeoJSON.java:34)`

The java implementation just creates a HttpURLConnection to the address and then reads the data sent back, where URL_STR is the above address:
`HttpURLConnection connection = null;
		URL url = new URL(URL_STR + "&page=" + page);
		connection = (HttpURLConnection) url.openConnection();
		connection.setRequestMethod("GET");
		
		InputStream is = connection.getInputStream();`

It doesn't set any headers manually, so would it be something to do with that?

**Comment by justahero** [comment]
Hi @rabidllama,

could you try setting a user agent?

```java
connection = (HttpURLConnection) url.openConnection();
connection.setRequestMethod("GET");
connection.setRequestProperty("User-Agent", "Test");
// ...
```

**Comment by rabidllama** [comment]
Yes, putting the API key in as a User-Agent header results in it working, though on the info page for the api it says that the header to use should be X-API-KEY

**Comment by justahero** [comment]
You should **not** put your api key into this field, it is not meant to contain this kind of information. The `User-Agent` HTTP header defines an identifying string a client sends in its requests when accessing a web server. For example every browser will set this header, for example the label `"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"` is the identifying label for a recent version of the Chrome browser.

That the connection now works is that the HTTP Java client requires this header to be present and the value for this entry can be any string. I recommend to set this entry to something that makes sense for your case (e.g. "My Client" or name it after your project).

**Comment by rabidllama** [comment]
OK, i tried it with "test" and it didn't work, but any other string (including "Test") does work... ah well, now at least I can get it to get the data thanks. Strange that the HTTP message is a 403 as I thought that would have been the response generated from the back end of the API itself
