### ISSUE TITLE
[Rails 4.0]: Use new syntax for `match` & remove duplicates in routes.rb

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#229]
**To upgrade from Rails 3.2.x to Rails 4.0 we need to do following:**
-     routes.rb, instead of using `match` use new match syntax.
  -  a `match` needs to either start with HTTP verb, e.g. `get` or needs to have `via: [:get,...] ` argument
-     remove duplicates routes from routes.rb

Important:
needs to be done **before** Rails upgrade

**Comment by justahero** [comment]
Please check if there were recent changes to the routes.rb that apply to this. This issue was addressed in #171.

**Comment by 1000miles** [comment]
@justahero Thank you. Yes, we will check if there more instances left to be adjusted. :)

**Comment by schultyy** [comment]
Lennart made some changes after @justahero's PR got merged but from what I can see they don't break anything.
