### ISSUE TITLE
[Rails 4.0]: Use new syntax for `SimpleForm` in initializer (due to deprecation warning)

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#230]
**In order to upgrade from Rails 3.2.x to Rails 4.0 we need to do following:**
- initializer: `SimpleForm.form_class` to `SimpleForm.default_form_class`, due deprecation

Important:
needs to be done **before** Rails upgrade

**Comment by schultyy** [comment]
We can't do this before installing Rails 4 because there's no compatible version of SimpleForm with the new `default_form_class` for Rails 3.
