### ISSUE TITLE
[Rails 4.0] Check gem `activeresource` if still in use

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#231]
**In order to upgrade from Rails 3.2.x to Rails 4.0 we need to do following:**
- the gem [activeresource](https://rubygems.org/gems/activeresource) has been extracted from Rails, we need to check if it is this still in use

Important: 
needs to be done **before** Rails upgrade

**Comment by schultyy** [comment]
There's one exception import from `activeresource` here https://github.com/sozialhelden/wheelmap/blob/master/app/controllers/api/photos_controller.rb#L2

When the tests pass again I would like to try to remove the gem and see if the application still works without errors.

**Comment by schultyy** [comment]
Just tested it: `activeresource` is still in use.

**Comment by schultyy** [comment]
No deprecation warning occuring anymore, therefore closing this ticket.
