### ISSUE TITLE
[Rails 4.0]: Update gem `mysql2` for Rails 4.0

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#234]
**To upgrade from Rails 3.2.x to Rails 4.0 we need to do following:**
* update gem [mysql2](https://rubygems.org/gems/mysql2) gem for Rails 4.0, propably used by [activerecord-mysql2spatial-adapter](https://rubygems.org/gems/activerecord-mysql2-adapter)
  * avoids Gem::LoadError (http://stackoverflow.com/questions/22932282/gemloaderror-for-mysql2-gem-but-its-already-in-gemfile)

**Comment by schultyy** [comment]
Done in ba416962dcbfb4019ed488cfd29fa33389c59d88.
