### ISSUE TITLE
[Rails 4.0] Fix all deprecation warnings related to Rails 4.0 upgrade

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#236]
**To upgrade from Rails 3.2.x to Rails 4.0 we need to do following:**

* fix all deprecation warnings related to the upgrade, currently counting: 

  ```
   63 (incl. duplicates)
   18 (netto)
  ```

**Comment by schultyy** [comment]
I assign this to Thuy and me to split up the work of fixing the warnings.

**Comment by 1000miles** [comment]
**Last Update: 2016, June 3**

Deprecation warnings to be fixed:
- [ ] The Active Record auto explain feature has been removed. 
- [ ] require "activeresource" is deprecated and will be removed in Rails 3. Use require "active_resource" instead.
- [ ] Support for Rails < 4.1.0 will be dropped.
- [ ] config.whiny_nils option is deprecated and no longer works.
- [ ] Using #scope without passing a callable object is deprecated.
- [ ] Calling #scope or #default_scope with a hash is deprecated.
- [ ] Poi.belongs_to :node_type declaration are deprecated: :include.
- [ ] Calling #scope or #default_scope with a hash is deprecated. 
- [ ] Region.has_many :children declaration are deprecated: :order.
- [ ] Active Admin: using `action_item` without a name is deprecated!
- [ ] You didn't set config.secret_key_base.
- [ ] #connection is deprecated in favour of accessing it via the class.
- [ ] Model.scoped is deprecated. Please use Model.all instead.
- [ ] This dynamic method is deprecated. Please use e.g. Post.find_or_create_by(name: 'foo') instead.
- [ ] Relation#all is deprecated. If you want to eager-load a relation, you can call #load
