### ISSUE TITLE
[Rails 4.0]: Update `rgeo-activerecord` for activeadmin

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#237]
**In order to upgrade from 3.2.x to Rails 4.0 we need to do following:**

* update gem from 0.4.x to later version? 

This is in preparation for the `activeadmin` gem

* ~~update activeadmin to latest version 1.0.0.pre2~~ (Already done in merged PR)
* update associated gems, e.g. safe_yaml
* this might require at least Rails 4.0 gem
* check gem `formtastic`

**Comment by schultyy** [comment]
Already done in ba416962dcbfb4019ed488cfd29fa33389c59d88. Closing.
