### ISSUE TITLE
[Rails 4.0] Check `search_methods` & replace it if needed

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#238]
**Background infos:**
* method `search_methods :region_id_eq` not available anymore

**In order to upgrade from 3.2.x to Rails 4.0 we need to do:**
* check where else this method is needed than at the 1 place
* implement an alternative in model Poi, e.g. `ransack`?

**Comment by schultyy** [comment]
Right now filtering by region works out of the box with ransack without any additional configuration
