### ISSUE TITLE
Travisify

### ISSUE THREAD

**Issue by skade** [sozialhelden/wheelmap#24]
Get the test suite running on travisci.

**Comment by lennerd** [comment]
Thanks to @christoph-buente, who fixed this.

**Comment by christoph-buente** [comment]
I added a simple travis config and changed some more minor things to get travis rolling. Now there are still 10 specs failing.

**Comment by christoph-buente** [comment]
I had to add some migrations to let the db/structure.sql reflect the current state of the schema. Now all specs are passing.

Unfortunately 4 of the cucumber tests are failing. Please have a look, if you can fix it.

PR #12 had to be rewritten as it largely broke the cucumber specs. But this is also done now.

I also removed the restriction to let travis only build the master. This means for future pull request travis should build them and give feedback to the contributor.
