### ISSUE TITLE
[Rails 4.0]: Fix i18n locale warnings

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#242]
**In the process of upgrading from Rails 3.2.x to Rails 4.0 we need to do**
- check & fix i18n locale warnings

**Failure/Error Example**
```
Failure/Error: I18n.locale = session["locale"] - # ./lib/rack_i18n_locale_switcher.rb:30:in call' # ./spec/features/create_spec.rb:16:inblock (3 levels) in '
```

**Comment by schultyy** [comment]
We need to figure out when these failures happen. On my local machine they do not occur, Travis don't report them either right now.

**Comment by schultyy** [comment]
My comment above is obsolete because this behavior only occurs with Rails 4.
