### ISSUE TITLE
[Rails 4.0] Update gem `activeadmin`

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#244]
In the process of upgrading from Rails 3.2.x to Rails 4.0 we use this ticket as a parent task for all the issues/errors associated with this upgrade.

### Overview:

- [x] **1** NoMethodError in Admin::PhotosController#index (Fixed in 3574ede18d76005ea82655e8104d4221aa12375a)
- [x]  **2** NoMethodError in Admin/providers\#index (Fixed in 9a7aef1adb867ec215910c9eaa36a9655fe6e368)
  - [x]  **6** Formtastic::UnknownInputError in Admin/providers#upload_csv (Fixed in db051f238fb37a01a3dcdae700716027147f5b65 )
  - [x] NoMethodError in Admin/providers#new (Fixed in 34be7ee6f1ddcfa7f660591d8f3b3ba7a5ce7475) 
- [x]  **2** NoMethodError in Admin/provided_pois\#index (Fixed in 9a7aef1adb867ec215910c9eaa36a9655fe6e368)
  - [x]  **6** Formtastic::UnknownInputError in Admin/provided_pois#upload_csv (Fixed in db051f238fb37a01a3dcdae700716027147f5b65 )
  - [x] NoMethodError in Admin/provided_pois#new (Fixed in 34be7ee6f1ddcfa7f660591d8f3b3ba7a5ce7475)
- [x]  **3** NoMethodError in Admin/users\#new (PR #250)
- [x]  **4** LoadError in Admin/photos\#new (Fixed in 3574ede18d76005ea82655e8104d4221aa12375a)

**Comment by 1000miles** [comment]
**Occurrences:**
- `/admin/regions/netherlands/photos`

## NoMethodError in Admin::PhotosController#index

undefined method `find' for nil:NilClass

Rails.root: /home/vagrant/wheelmap
Application Trace | Framework Trace | Full Trace

app/admin/photos.rb:13:in `collection'
lib/rack_i18n_locale_switcher.rb:32:in `call'

Request

Parameters:

{"region_id"=>"netherlands"}

Show session dump

Show env dump
Response

Headers:

None

---

# 2

**Occurrences:**
- `/admin/providers`
- `/admin/provided_pois`

##  NoMethodError in Admin/providers\#index

Showing /home/vagrant/wheelmap/vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre2/app/views/active\_admin/resource/index.html.arb where line \#2 raised:

undefined method `icon' for \#

Extracted source (around line \#2):

1: insert\_tag renderer\_for(:index)

Rails.root: /home/vagrant/wheelmap
Application Trace | Framework Trace | Full Trace

app/admin/provider.rb:9:in 

```
block (3 levels) in <top (required)>'
app/admin/provider.rb:8:in
```

block (2 levels) in '
lib/rack\_i18n\_locale\_switcher.rb:32:in `call'

Request

Parameters:

None

Show session dump

Show env dump
Response

Headers:

None

---

# 3

**Occurrences:**
- `/admin/users/new`
- `/admin/node_types/new`
- `/admin/regions/netherlands/edit`

## NoMethodError in Admin/users\#new

Showing /home/vagrant/wheelmap/vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre2/app/views/active\_admin/resource/new.html.arb where line \#2 raised:

undefined method `buttons' for \#

Extracted source (around line \#2):

1: insert\_tag renderer\_for(:new)

Rails.root: /home/vagrant/wheelmap
Application Trace | Framework Trace | Full Trace

---

# 4

**Occurrences:**
- `/admin/photos/new`

## LoadError in Admin/photos\#new

 Showing */home/vagrant/wheelmap/vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre2/app/views/active\_admin/resource/new.html.arb* where line **\#2** raised: 

```
cannot load such file -- formtastic/inputs/datetime_input

```

Extracted source (around line **\#2**): 

```
1: insert_tag renderer_for(:new)

```

`Rails.root: /home/vagrant/wheelmap`

 [Application Trace](http://192.168.33.10:3000/admin/photos/new#) | [Framework Trace](http://192.168.33.10:3000/admin/photos/new#) | [Full Trace](http://192.168.33.10:3000/admin/photos/new#) 

```
app/admin/photos.rb:51:in `block (3 levels) in <top (required)>'
app/admin/photos.rb:48:in `block (2 levels) in <top (required)>'
lib/rack_i18n_locale_switcher.rb:32:in `call'

```

## Request

**Parameters**: 

```
None

```


app/admin/users.rb:79:in 

```
block (2 levels) in <top (required)>'
lib/rack_i18n_locale_switcher.rb:32:in
```

call'

Request

Parameters:

None

Show session dump

Show env dump
Response

Headers:

None

----

# 5 

**Occurrences:**
 `/admin/addresses`

## Mysql2::Error in Admin::AddressesController\#index

```
Table 'wheelmap_development.addresses' doesn't exist

```

`Rails.root: /home/vagrant/wheelmap`

 [Application Trace](http://192.168.33.10:3000/admin/addresses#) | [Framework Trace](http://192.168.33.10:3000/admin/addresses#) | [Full Trace](http://192.168.33.10:3000/admin/addresses#) 

```
lib/rack_i18n_locale_switcher.rb:32:in `call'

```

## Request

#  

**Parameters**: 

```
None

```

[Show session dump](http://192.168.33.10:3000/admin/addresses#)

[Show env dump](http://192.168.33.10:3000/admin/addresses#)

## Response

#  

**Headers**: 

```
None

```

**Comment by schultyy** [comment]
For MetaSearch there was a `search_methods` method defined in [`app/models/poi.rb`](https://github.com/sozialhelden/wheelmap/blob/master/app/models/poi.rb#L95). Search is possible nevertheless. I'm not sure if we need to replace this call with something else. @christoph-buente is that call still needed?

**Comment by christoph-buente** [comment]
ActiveAdmin switched from MetaSearch to Ransack in the latest version. This search method is used in the filter field on the right sidebar. Either remove the filter, or refactor the search method using the ransacker.

**Comment by 1000miles** [comment]
# 6

**Occurrences:**

- `/admin/providers/upload_csv`
- `/admin/provided_pois/upload_csv`

## Formtastic::UnknownInputError in Admin/providers#upload_csv

Showing /home/vagrant/wheelmap/app/views/admin/provided_pois/upload_csv.html.haml where line #16 raised:

Unable to find input class for select

Extracted source (around line #16):

13:   = form.inputs  "Neue Premiumorte Hochladen", class: :inputs do
14:     %ol
15:       %li.select.input.required
16:         = form.input :provider, collection: Hash[Provider.all.map{|b| [b.name,b.id]}]
17:       %li.select.input.required
18:         = form.input :csv_file, as: :file, required: true
19: 

Rails.root: /home/vagrant/wheelmap
Application Trace | Framework Trace | Full Trace

app/views/admin/provided_pois/upload_csv.html.haml:16:in `block (2 levels) in _app_views_admin_provided_pois_upload_csv_html_haml___669742871923653629_69969990037000'
app/views/admin/provided_pois/upload_csv.html.haml:13:in `block in _app_views_admin_provided_pois_upload_csv_html_haml___669742871923653629_69969990037000'
app/views/admin/provided_pois/upload_csv.html.haml:12:in `_app_views_admin_provided_pois_upload_csv_html_haml___669742871923653629_69969990037000'
app/admin/provider.rb:15:in `block (2 levels) in <top (required)>'
lib/rack_i18n_locale_switcher.rb:32:in `call'

Request

Parameters:

None

Show session dump

Show env dump
Response

Headers:

None

**Comment by 1000miles** [comment]
# 7 

**Occurrences:**

- `/admin/provided_pois/upload_csv` => click on upload_csv button
- `/admin/providers` => click on upload_csv button

## NoMethodError in Admin::ProvidedPoisController#import_csv

undefined method `[]' for nil:NilClass

Rails.root: /home/vagrant/wheelmap
Application Trace | Framework Trace | Full Trace

app/admin/provided_poi.rb:24:in `block (2 levels) in <top (required)>'
lib/rack_i18n_locale_switcher.rb:32:in `call'

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"XQ05tP0jCKmJ/XgidJlrwhPmtAX21dH9fPNkdlst5N8=",
 "commit"=>"Upload"}

Show session dump

Show env dump
Response

Headers:

None

**Comment by 1000miles** [comment]
Related Issue: https://github.com/sozialhelden/wheelmap/issues/243
ActiveAdmin: RuntimeError in Regions#Index
