### ISSUE TITLE
Mysql2::Error in Admin::AddressesController#index

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#246]
# 5 

**Occurrences:**
- local
- `/admin/addresses`

## Mysql2::Error in Admin::AddressesController\#index

```
Table 'wheelmap_development.addresses' doesn't exist

```

`Rails.root: /home/vagrant/wheelmap`

 [Application Trace](http://192.168.33.10:3000/admin/addresses#) | [Framework Trace](http://192.168.33.10:3000/admin/addresses#) | [Full Trace](http://192.168.33.10:3000/admin/addresses#) 

```
lib/rack_i18n_locale_switcher.rb:32:in `call'

```

## Request

#  

**Parameters**: 

```
None

```

[Show session dump](http://192.168.33.10:3000/admin/addresses#)

[Show env dump](http://192.168.33.10:3000/admin/addresses#)

## Response

#  

**Headers**: 

```
None

```

**Comment by schultyy** [comment]
Related to #71

**Comment by 1000miles** [comment]
Closed.
