### ISSUE TITLE
Confirm that assets::precompile still works with Rails 4

### ISSUE THREAD

**Issue by schultyy** [sozialhelden/wheelmap#269]
From the upgrade guide (http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html):

> In Rails 4.0, precompiling assets no longer automatically copies non-JS/CSS assets from vendor/assets and lib/assets. Rails application and engine developers should put these assets in app/assets or configure config.assets.precompile.

We need to ensure that precompilation still works as expected.

**Comment by 1000miles** [comment]
Related PR: #272 
Closed.
