### ISSUE TITLE
Venue photos do not show up on mobile apps

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#286]
- I open the venue "ScoutLounge Kantine" in the latest iOS App and Android App and Windows 10 App
- I expect two photos to show up
- Instead, I see white rectangles on iOS and a spinner on Android and its missing completely in the w10 app.

I can see the photos of the venue on the website though: http://wheelmap.org/nodes/1336912426

iOS:
![img_8507](https://cloud.githubusercontent.com/assets/218506/15861672/54392624-2ccd-11e6-8423-ecc67dc3def3.PNG)

Android:
![screenshot_20160607-162533](https://cloud.githubusercontent.com/assets/218506/15861695/713c3c84-2ccd-11e6-800d-025e107759a6.png)

**Comment by lennerd** [comment]
@holgerd Can you please check again now?

**Comment by holgerd** [comment]
it works now in iOS. Can not test the other apps right now.
