### ISSUE TITLE
Geolocation Error in Chrome when clicking "locate me" icon in map

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#287]
- I'm using Chrome and load http://wheelmap.org/map I click on the "locate me" icon in the upper left of the map to set my current location.
- I expect the map to recenter to where I am
- Instead, I get a javascript alert saying:  "Geolocation error: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).."

More info

- goo.gl link destination: https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features
- click statistics for this goo.gl shortlink (read: we are not the only ones and clicks increased recently):
https://goo.gl/#analytics/goo.gl/Y0ZkNV/all_time
- It works in Firefox.

**Comment by Xylakant** [comment]
you need to use https://wheelmap.org/map for geolocation to work in chrome.

**Comment by Xylakant** [comment]
closing in favor of #201 which tracks the same thing
