### ISSUE TITLE
[Rails 4.2] Support for Rails < 4.1.0 will be dropped.

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#297]
Deprecation warning:
```
Support for Rails < 4.1.0 will be dropped. 
```
> This one is raised by another gem we use, when I remember correctly it was formtastic. Either we update the gem or live with the warning until we upgrade to Rails 4.2

This ticket is the follow-up to the deprecation warning collection: 
https://github.com/sozialhelden/wheelmap/issues/236

**Please see here for further references:**
https://github.com/activeadmin/activeadmin/issues/3788
https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin.rb#L8

**Comment by lennerd** [comment]
will be fixed with #296

**Comment by schultyy** [comment]
Is now fixed with the Upgrade to Rails 4.1. Closing.
