### ISSUE TITLE
Places do not show up on map

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#309]
- I'm on one of these detail pages:
http://wheelmap.org/nodes/4254019058
http://wheelmap.org/nodes/3102724235
http://wheelmap.org/nodes/3102724233
I click on the Link "back" (not in the browser) to get to the map view where the place is on.

- I expect the place to be on the center of this map view when I zoom in to the maximum.

- Instead, there is no icon for this place at all.

The places in OSM for reference:
http://www.openstreetmap.org/node/4254019058
http://www.openstreetmap.org/node/3102724235
http://www.openstreetmap.org/node/3102724233

**Comment by holgerd** [comment]
@1000miles can you look into this next week?
It may be a frontend problem that the nodes are not displayed in the map, maybe @lennerd can say more about that.

**Comment by 1000miles** [comment]
@holgerd yes, will do. thanks for reporting this.

**Comment by lennerd** [comment]
@1000miles From reading this my first guess is the tile loading. We only have limited amount of nodes per tile. So maybe they are too many places inside these tiles and therefore the node for the corresponding marker is not loaded.

Normally we send a `node_id` parameter to the server for defining a single node which should always be loaded. But I have the feeling, that this `node_id` is not handled correctly.

Maybe this helps. Ping me, if you need any more information.

**Comment by 1000miles** [comment]
@holgerd @lennerd 

After our research we found out following:

**CIU CIU Bonbonmanufaktur**

poi with id `4254019058` has been deleted in the last 18 hours:
https://www.openstreetmap.org/node/4254019058 <=> http://wheelmap.org/nodes/4254019058
```
Knoten: 4254019058
korr
Gelöscht vor etwa 18 Stunden von ...
Version #3 · Änderungssatz #40329730
```
and has been replaced with following poi:
https://www.openstreetmap.org/node/4244739589 <=> http://wheelmap.org/nodes/4244739589

- [x] **status: nothing to do here, all is fine.**

----
**TUI Reisecenter**

poi with id `3102724235` has been deleted in the last 18 hours:
https://www.openstreetmap.org/node/3102724235 <=> http://wheelmap.org/nodes/3102724235

```
Node: 3102724235
korr
Deleted about 20 hours ago by ...
Version #3 · Changeset #40329730
```
and has been replaced with following poi:
https://www.openstreetmap.org/node/4244725592 <=> http://wheelmap.org/nodes/4244725592

- [x] **status: nothing to do here, all is fine.**

----

**Die Diekers**

There are duplicates of the place `Die Diekers` on openstreetmap and wheelmap:
- https://www.openstreetmap.org/node/3102724233 <=> http://wheelmap.org/nodes/3102724233 (Location: 53.139561, 8.21310029)
-  https://www.openstreetmap.org/node/4258312022 <=> http://wheelmap.org/nodes/4258312022 
(Location: 53.1395113, 8.2130796)

On local host we can render each poi `node-popup-content` with:
- http://192.168.33.10:4567/map#/popup/4258312022?lat=53.1395113&lon=8.2130796&zoom=19
- http://192.168.33.10:4567/map#/popup/3102724233?lat=53.139561&lon=8.2131002&zoom=19

But on wheelmap.org it is not possible to render the given coordinates, they just don't show up:
- http://wheelmap.org/map#/popup/3102724233?lat=53.139561&lon=8.2131002&zoom=1
- http://wheelmap.org/map#/popup/4258312022?lat=53.1395113&lon=8.2130796&zoom=19

- [x] Status: We will look further into it

@lennerd Any further ideas welcome.

**Comment by lennerd** [comment]
@1000miles Please see my pull request which fixes this issue. #315

**Comment by holgerd** [comment]
@lennerd at least with one POI the issue still exists:
I'm on one of these detail pages:
http://wheelmap.org/nodes/3102724233
I click on the Link "back" (not in the browser) to get to the map view where the place is on.
The pin does not show up.

**Comment by lennerd** [comment]
@holgerd We need to deploy this on production in order to know if it fixes the bug there. At the moment it is only deployed on staging.

**Comment by holgerd** [comment]
Our general rule is to never deploy fridays. ;) How about next Monday or
Tuesday so you have time to revert/debug anything which may go wrong?

2016-07-01 10:10 GMT+02:00 Lennart Hildebrandt <notifications@github.com>:

**Comment by lennerd** [comment]
Agree. Let's deploy on Monday then.

**Comment by lennerd** [comment]
@holgerd PR is deployed. Issues seems to have fixed.

**Comment by holgerd** [comment]
@Svenyo says this is happening again. she'll post it here

**Comment by Svenyo** [comment]
Einige Icons zu Ortstypen, die in der OSM sind und die wir unterstützen, werden noch immer nicht angezeigt. Betrifft: Lange Straße 48-53, 26122 Oldenburg

![bildschirmfoto 2016-07-14 um 14 39 55](https://cloud.githubusercontent.com/assets/20318534/16839761/176dc6b6-49d1-11e6-8200-5a9a084c4dab.png)

![bildschirmfoto 2016-07-14 um 14 39 00](https://cloud.githubusercontent.com/assets/20318534/16839773/2bab51fc-49d1-11e6-8d8b-dec1d0991b76.png)

Ich habe gerade auch nochmal versucht neue Orte anzulegen. Merkwürdig: In Berlin funktionierte es inklusive Icon, eine Schule hinzuzufügen. In Oldenburg fehlen die Icons wieder.

**Comment by lennerd** [comment]
1. We won't be able to fix this. But if you provide a node id in the URL as a query paramter, this node will be shwon.

2. This fix is not published on production yet. Did you check against staging?

**Comment by Svenyo** [comment]
Oh, okay. On staging the situation looks slightly better. Randomly, one out of two nodes are displayed. However, shop=confectionery and shop=department_store for example are still gone missing.

**Comment by lennerd** [comment]
They are missing completely everywhere on the map? Even in areas where there are only a few nodes?

**Comment by Svenyo** [comment]
No. Node types that are shown on this special extract of the map are shown elsewhere.

**Comment by lennerd** [comment]
No I mean if you can see nodes on our Wheelmap with the same node type or if this node type is not shown in the Wheelmap at all.

**Comment by lennerd** [comment]
I sorry, I see, that you answered this question. Okay, than we have a problem with the limit of nodes per tile. I did not found a good solution for this without risking bad performance when there are multiple node tiles loaded on the screen.

Imagine we say 30 is the new limit. This maybe won't be enough in a few months. So either we change the limit again every time we see this problem or we change the limit to a much bigger number, like 200 per tile.

Now again imagine you see multiple small areas (tiles) on our wheelmap each containg 200 nodes. When you see 9 tiles, this will lead to around 1800 nodes and certainly will crash the application or lead to very bad performance of the browser.

I'm not sure how we could fix this. Clustering could be a solution bad there are other problems which needs to be solved then (e.g. filtering). Any ideas?

**Comment by holgerd** [comment]
Idea: Can we increase the amount of nodes per tile dependent on the zoom level? eg. on maximum zoom level show everything (eg. 500 per tile) and on other zoom levels show much less?

**Comment by lennerd** [comment]
This would be possible yes. Will look into this as soon as possible. I'm not quite sure yet how easy or difficult this will be with the current implementation.

**Comment by lennerd** [comment]
I wrote a quite extensive post about this topic and my research. Seems I did not submit it. 🎉 😑

Never the less, I think I was able to locate the error. The corresponding code is the following:

https://github.com/sozialhelden/wheelmap/blob/master/app/controllers/nodes_controller.rb#L225-L238

As the right, left, top and bottom parameters are rounded to some float values with a maximum of three decimals this is especially critical in high zoom levels as we then need more precise bounding boxes to have valid and not overlapping results.

I added some debug rectangles to the GeoJSON response of tile API which helped me find this error. This is how the tile boundaries look like in the current implementation:

![screenshot 2016-07-19 19 29 58](https://cloud.githubusercontent.com/assets/1609692/16959850/3c322c2a-4de7-11e6-803a-ec29e9490053.png)

And this is how they look like if we use float values with the default 15 decimals:

![screenshot 2016-07-19 19 31 15](https://cloud.githubusercontent.com/assets/1609692/16959884/6295ded4-4de7-11e6-96a7-49b77812f553.png)

There is a huge different between the number of visible nodes and how nodes are actually loaded.

I already pinged @christoph-buente with the hope he knows more about the linked code part. It was implemented on the Hackathon with Webxells when we did first steps with clustering. And I'm not quite sure what it actually does or more importantly why it was implemented.

In case of doubt I'm pretty sure this code parts can all be removed. The clustering is something we won't find a solution for the frontend soon.

**Comment by holgerd** [comment]
You suggest to remove this code, right?

Will this ensure that all POIs show up in the closest zoom level?

**Comment by christoph-buente** [comment]
Hi @all,

the code in question was meant to make bounding box queries more cacheble. Back then there was only one GeoJSON request for the full viewport. Moving the map 3 pixels to the side would then result in a new request with slightly different bounding box. And a cache miss.

During the hackathon, a slightly different approach was developed, that was somewhat mimicking tiles. But obviously the rounding of top/bottom, right/left coordinates was screwed up. In fact there are overlapping and gaps in the "poor-mans tiles".

Now, as all GeoJSON data is fetched via tiles, which are essentially well cacheable request, this code is not needed anymore.

@lennerd when/where did you ping me? I seemed to missed it.

**Comment by lennerd** [comment]
I'm always confused by `unless`. Thanks @christoph-buente for the information.

> Will this ensure that all POIs show up in the closest zoom level?

@holgerd I'm not 100% sure unless we deploy my debug code to staging and production and look at the returned rectangles there. I would suggest to deploy the current debug code on both environments and see what happens. Okay?

The debug rectangles are only visible via a corresponding query parameter.

**Comment by holgerd** [comment]
yes, please do and let me know what the parameter is so I can learn as well.

**Comment by lennerd** [comment]
#338 seems to fix it.

![screenshot 2016-07-25 11 31 48](https://cloud.githubusercontent.com/assets/1609692/17097388/dc7b257c-525d-11e6-8087-c7b7b947cb73.png)

https://wheelmap.org/map#/?lat=53.139491950339256&lon=8.213489949703217&zoom=19

**Comment by holgerd** [comment]
looks much better now!

![wheelmap_-_rollstuhlgerechte_orte_finden](https://cloud.githubusercontent.com/assets/218506/17098064/b625548a-5260-11e6-8907-f49808fb6c1b.png)

before: https://github.com/sozialhelden/wheelmap/issues/309#issuecomment-232654799
