### ISSUE TITLE
Add notice "Zoom in closer to see all places"

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#316]
Svenja suggests:

As a user who is looking for a place by zooming into the map, I am not aware that certain places appear only when I zoom in closest to the highest zoom level.

I would find it helpful to get informed of this particularity in a info bubble saying "Zoom in closer to see all places" that stays visible until the highest zoomlevel is displayed.

**Comment by holgerd** [comment]
Zunächst müssen wir sicherstellen dass beim reinzoomen wirklich alle Orte auftauchen (siehe anderes issue: https://github.com/sozialhelden/wheelmap/issues/309 )

**Comment by lennerd** [comment]
#309 is fixed.
