### ISSUE TITLE
500 error on profile/after_signup_update

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#317]
Die Fehlermeldung kommt allerdings weiterhin beim erstmaligen Eintragen der E-Mail-Adresse auf http://wheelmap.org/profile/after_signup_edit (siehe Screenshots), obwohl hinterher korrekterweise ein Profil in der Admin-Ansicht angezeigt wird.

Anstatt "Sorry, something went wrong" müsste auf http://wheelmap.org/profile/after_signup_update ein positives Feedback hin bzw. sollte der User direkt in das Formular seines Profils gelangen, um dort Name etc. einzutragen.

Außerdem kommt nach Absenden und Fehlermeldung keine Bestätigungsmail für das Profil auf Wheelmap.org.

![bildschirmfoto 2016-06-29 um 10 51 28](https://cloud.githubusercontent.com/assets/218506/16446908/53938092-3dea-11e6-8d2a-df5fb14c3dbe.png)

![bildschirmfoto 2016-06-29 um 10 49 01](https://cloud.githubusercontent.com/assets/218506/16446912/58afc266-3dea-11e6-89e9-044207e2aa80.png)

**Comment by schultyy** [comment]
I checked the log file. That's the error:

```
Sent mail to jane@example.com (40632.1ms)
Completed 500 Internal Server Error in 41111ms (ActiveRecord: 25.4ms)

Net::SMTPFatalError (550-Please turn on SMTP Authentication in your mail client.  (wheelmap.org)
):
  app/models/user.rb:45:in `send_email_confirmation'
  app/controllers/users_controller.rb:66:in `after_signup_update'
  lib/rack_i18n_locale_switcher.rb:32:in `call'
  librato-rack (0.6.0) lib/librato/rack.rb:94:in `process_request'
  librato-rack (0.6.0) lib/librato/rack.rb:64:in `call'
```
