### ISSUE TITLE
CSV-Export of Wheelmap-POIs should support >500 entries 

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#32]
As admin I would like to be able to export more than 500 POIs as CSV-file. Right now only <500 entries are possible to be exported at http://wheelmap.org/en/admin/pois .

Example: download a CSV file of all POIs (yes, no, limited, unknown) in the category "food".

Requested by the wheelmap community manager.

**Comment by joustava** [comment]
@holgerd, deployed a fix to staging. As far as I tested it it seems to download as many pois as the current filters returns. (so over 30000 pois without filters, which can take a while)

**Comment by holgerd** [comment]
@joustava What is the maximum now?

I tried to download all 623.000 "unknown" places with this URL:
http://staging.wheelmap.org/en/admin/pois.csv?order=osm_id_desc&page=1&scope=unknown_accessibility

After a few seconds I got a "something went wrong" error.

It works with smaller sets such as the 5.900 fully accessible bakeries:
http://staging.wheelmap.org/en/admin/pois.csv?order=osm_id_desc&page=1&q%5Bnode_type_id_eq%5D=45&scope=fully_accessible&utf8=%E2%9C%93

**Comment by christoph-buente** [comment]
Well, there is a timeout if course. So if rails takes a long time to render the csv information, nginx will show the error page at some point.

**Comment by joustava** [comment]
So, it seems we are limited by the unicorn timeout, but capping the exported pois by an arbitrary number doesn't seem right to me either. Would it make sense to disable export features whenever the search result are to big to handle instead of limiting poi csv records to export?

Or can we configure unicorn to have a slightly higher timeout and make it support streaming, and generate the csv in batches?

**Comment by christoph-buente** [comment]
Or maybe we can trigger a background job and put the file into the dropbox.

**Comment by joustava** [comment]
Seems streaming this is supported out of the box in the newest version: https://github.com/activeadmin/activeadmin/pull/3038

**Comment by christoph-buente** [comment]
Nice find! :+1:

**Comment by holgerd** [comment]
@joustava The feature is fine as it is, please deploy and let me know when it is live. Just discussed it with Svenja and she said she will only download CSVs with less than 100.000 POIs, which already works. Thanks! :)

**Comment by joustava** [comment]
@holgerd it is on staging for review.

**Comment by holgerd** [comment]
@joustava thanks. The CSV-download stops after 1.4MB which is ca. 13.000 rows. I'll ask S. if that size is enough.

**Comment by holgerd** [comment]
Yeah it's fine!

**Comment by holgerd** [comment]
@joustava please let me know as soon as this is live.

**Comment by holgerd** [comment]
@joustava is this live now?

**Comment by holgerd** [comment]
It's live. Example: http://wheelmap.org/en/admin/pois.csv?order=osm_id_desc&page=1&scope=unknown_accessibility
