### ISSUE TITLE
wheelchair-tag not shown on wheelmap, but toilet correctly shown

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#334]
- I'm OSM-user nanonan and  and mark the place  http://wheelmap.org/nodes/-239534993 using wheelmap as wheelchair=yes and toilet=yes
- I expect both to become "green" and the data to be saved in OSM
- Instead, I the wheelchair-tag stays unmarked/grey and only the toilet tag changes to green. But my changes have been written to OSM as I can see in this changeset: http://www.openstreetmap.org/changeset/40795134

**Comment by holgerd** [comment]
Svenja schreibt:

ja, ich konnte den Bug gerade mit der Web-App reproduzieren:

Der POI hatte einen grünen Zugänglichkeitsstatus, als ich die Toilette grün markierte, wurde der Zigänglichkeitsstatus grau. Dann auch das Icon grau. Wenn ich jetzt auf das Icon klicke, wird beides grün angezeigt. Wenn ich die Bubble schließe, ist das Icon komplett verschwunden.

Siehe Screenshots.
![bildschirmfoto 2016-07-18 um 10 59 19](https://cloud.githubusercontent.com/assets/218506/16939981/c0068868-4d86-11e6-9071-f24a3f12ad32.png)

![bildschirmfoto 2016-07-18 um 10 59 09](https://cloud.githubusercontent.com/assets/218506/16939984/c44851ae-4d86-11e6-830e-99c3e1a5c8cb.png)


![bildschirmfoto 2016-07-18 um 10 59 00](https://cloud.githubusercontent.com/assets/218506/16939989/cb54a15a-4d86-11e6-8a56-79dad47e8df1.png)

![bildschirmfoto 2016-07-18 um 10 58 46](https://cloud.githubusercontent.com/assets/218506/16939993/d0524626-4d86-11e6-852f-6a147b42c247.png)

**Comment by holgerd** [comment]
@Svenyo Bei mir sieht der Freizeitpark ok aus. Ich habe eben danach gesucht in Wheelmap und auch gefunden und er ist grün/grün. http://wheelmap.org/nodes/1834315985

**Comment by holgerd** [comment]
I notice the node-id in the wheelmap URL is negative, so I understand this is a POI which has been converted from a shape. Maybe this is related to this issue?

**Comment by Svenyo** [comment]
Hej, true, seems the tag is displayed correctly after some time again.

**Comment by holgerd** [comment]
happens on iOS as well; related?
https://github.com/sozialhelden/wheelmap-iphone2/issues/21

**Comment by holgerd** [comment]
Can reproduce it on iOS app and website with 'malabar Brandenburg'

**Comment by Svenyo** [comment]
I've just experienced another case: Re-editing the wheelchair tag from yes to limited and back to green again caused the toilet tag to switch to unknown. Please compare http://wheelmap.org/nodes/1336912426 with http://www.openstreetmap.org/node/1336912426. 
On this occasion I've noticed the wrong toilet tag in the same OSM changeset.  

![bildschirmfoto 2016-08-09 um 15 32 42](https://cloud.githubusercontent.com/assets/20318534/17518420/1e97c8f2-5e48-11e6-9f8f-d47664a16448.png)

**Comment by holgerd** [comment]
This wrong tag was also mentioned here:
https://lists.openstreetmap.org/pipermail/talk-de/2016-July/113238.html

We should fix this soon and discuss with the OSM community if/how an automated correction of existing tags could be done.

**Comment by 1000miles** [comment]
@holgerd
cc @schultyy

**Estimation to fix:**
- approx. 0.5 - 1 day (just a fix & including tests)
- approx. 2-2.5 days (fix, tag concept improvements & tests)

**Explanation:**
- research
- fix
- tests
- (concept & discussions for improvements)

In case it's just refactoring the `update_tags_job` of this file https://github.com/sozialhelden/wheelmap/blob/master/app/jobs/update_tags_job.rb), then we think it wouldn't take long (0,5 day) but if we need to improve the tag concept behind the `wheelchair` & `wheelchair:toilet` & test it, then it could take longer.

**Comment by schultyy** [comment]
I openend a PR for the problem that wheelchair and toilet status couldn't be updated at the same time. 

Concerning the wrong wheelchair toilet tag name: I would like to move that into a new issue since that's not directly related to the issue's topic. WDYT?

**Comment by schultyy** [comment]
Regarding the wrong toilet tag in changeset: I opened a follow up ticket here: https://github.com/sozialhelden/wheelmap/issues/400

**Comment by 1000miles** [comment]
@holgerd @Svenyo 
The changes from PR #399 have been deployed on staging and production on thursday, 2016, sept 15.

**Now the current flow is for example:**

- node at the beginning: 
  - wheelchair = unknown
  - toilet = unknown

- if i change
  - wheelchair to `orange` & click on `save` button
  - toilet to `green` & click on `save` button

- i get:
  - wheelchair = `orange` after a few seconds
  - toilet = `green` after a few seconds

@holgerd Can you please test any node and confirm?

**Comment by holgerd** [comment]
LGTM. 👍 

@1000miles  It now works in the iOS app as well, is that possible?
