### ISSUE TITLE
Issue with regions

### ISSUE THREAD

**Issue by thermann78** [sozialhelden/wheelmap#335]
We have a new issues with our regions.
When I open for example http://wheelmap.org/map/berlin/theatre/wheelchair/yes, I get the reply "Could not find region berlin". Also, if I try to open http://wheelmap.org/admin/regions/berlin in the backend, this leads to an error 500. Can be reproduced with any region - and all regions exist, and the list views have been working so far.
This is a critical issue as we are using the list views as results on travelable.
Please have a look at this asap.

**Comment by holgerd** [comment]
That's bad. 
@1000miles please look into this tomorrow first thing. Thanks.

**Comment by 1000miles** [comment]
Acknowledged. :)

**Comment by 1000miles** [comment]
Thanks for reporting, @thermann78 . :)
cc @holgerd 

Wenn we call the page http://wheelmap.org/map/berlin/theatre/wheelchair/yes, we get a `400 Bad Request` (instead of 500 Internal Server Error).

![00000127](https://cloud.githubusercontent.com/assets/4077916/16982917/ad608aa0-4e72-11e6-9543-b173f23c9b9e.png)


Also when we call http://wheelmap.org/admin/regions/berlin, we get a `404 Not Found` error (instead of 500 Internal Server Error).

**Following is the error output in the log file on `production`:**

```
I, [2016-07-20T12:00:31.372269 #22139]  INFO -- : Started GET "/admin/regions/berlin"
I, [2016-07-20T12:00:31.376050 #22139]  INFO -- : Processing by Admin::RegionsController#show as HTML
I, [2016-07-20T12:00:31.376120 #22139]  INFO -- :   Parameters: {"id"=>"berlin"}
I, [2016-07-20T12:00:31.387937 #22139]  INFO -- : Completed 404 Not Found in 12ms (ActiveRecord: 1.1ms)
F, [2016-07-20T12:00:31.397404 #22139] FATAL -- :
ActiveRecord::RecordNotFound (Couldn't find Region with 'id'=berlin):
  lib/rack_i18n_locale_switcher.rb:32:in `call'
  librato-rack (0.6.0) lib/librato/rack.rb:94:in `process_request'
  librato-rack (0.6.0) lib/librato/rack.rb:64:in `call'
```

=> It seems something is broken  with the queries on region IDs. 

P.S. When @schultyy and me did the Rails 4 upgrade we were already confronted with another issue on regions, please find it here: https://github.com/sozialhelden/wheelmap/issues/257

Maybe the regions part can be fixed altogether?

**Comment by thermann78** [comment]
IDK if there is a connection between these issues, but I can collect some data from Librato: there have been data delivered considering the regions until 20th July - meaning today. Then the datastream seems to have ended: https://metrics.librato.com/share/dashboards/3wf885ot - at least it seems to have happened within the last few updates, I guess.

**Comment by schultyy** [comment]
I deployed the fix for Active Admin on production.

**Comment by schultyy** [comment]
@thermann78 The regions page is now back on the production system.

**Comment by lennerd** [comment]
@thermann78 Can you show me the page, where you include the `node_type` pages? It would be much better to use the API for this so we do not produce such regression errors.

**Comment by thermann78** [comment]
The node_types aren't included anywhere. We link to the list results from travelable, e.g. http://berlin.travelable.info/project/essen-trinken-und-feiern-ohne-barrieren/

**Comment by lennerd** [comment]
Ah okay, so you need a list of places without getting a very long post in travelable. I see.

Is there already an issue for the Widget embed view for suggesting the features you want to have to be able to add them to traveable?

The `category` API btw. does provide all `node_types`. Via the `node` API you can than filter by wheelchair status.

**Comment by thermann78** [comment]
I just created an issue for the widget thing.

**Comment by holgerd** [comment]
The issue still persists sometimes.

Example:

- I'm on http://wheelmap.org/nodes/1390162166 and click on "All places of typ 'Gas station' in North America" in the right column of the page
- I expect to see a list
- Instead, I see "Could not find region north-america" and the URL is http://wheelmap.org/en/map/north-america/fuel/wheelchair/unknown

Same problem in San Francisco:
http://wheelmap.org/nodes/302742486

When I'm in Vietnam I see this, and it works (but "Asia" sounds like a pretty big region):
http://wheelmap.org/en/map/asia/furniture/wheelchair/unknown

Paris, France seems to work though:
http://wheelmap.org/en/map/paris/fuel/wheelchair/limited

**Comment by holgerd** [comment]
Re-checked, it seems to work now. So I'm closing this.
