### ISSUE TITLE
Wheelmap "live counter", embedable in other websites

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#34]
As campaigner for wheelchair accessible places I want to embed a wheelmap-counter on my campaign website so my visitors can see how many places have been marked as wheelchair=yes/no/limited. The counter should update often (eg every 5min) to give a "live" feeling to encourage and celebrate participation.

**Comment by holgerd** [comment]
ping

**Comment by holgerd** [comment]
@christoph-buente just told me the counter should already be part of the API:
http://wheelmap.org/en/api/docs/resources/nodes


you should be able to filter here for example:
/api/nodes?wheelchair=yes&page1&per_page=1

result should give a total  number and a filtered for yes/no wheelchair accessibility.

@1000miles do you think this is something an external agency could work with?

**Comment by 1000miles** [comment]
Hi @holgerd, thank you for asking. I'll check it and get back to you asap. I may have a few questions related to the counter (from user perspective) and might ask you, if that is okay? :)

**Comment by 1000miles** [comment]
Hi @holgerd,  

question: are we talking about the possibility to a) embed the **current** counter on other websites or are we talking about b) the filter option for different statuses (yes, limited, no) on the counter?

**Regarding the filter on the counter:**
When hovering over the counter, at the moment there is already a tooltip which shows filtered numbers of each (yes, limited, no), so I am not sure what you exactly mean with the result of a total number and a filtered number. 

Maybe you can help specifying? :) Thank you.

**Comment by holgerd** [comment]
We are planning a campaign and the makers of the external campaign website http://mapmyday.org should be able to display a counter on the homepage. No filter necessary. 
Feel free to join slack (I sent you an invitation a few days ago) if you have more questions.
