### ISSUE TITLE
can not add place

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#345]
received today via the feedback form:
	
guten tag,
ich bin mehr als befremdet, dass es nicht möglich ist einen ort hinzuzufügen - ich gebe jetzt auf und werde sofern dies weiter nicht funktioniert in facebook stellen.

Man drückt auf speichern zuletzt aber es geht gar nichts.
Habe meinen Account kontrolliert und ollte selbstbestimmt leben in graz eingeben in der eggenberger allee 49 aber es speichert es nicht - keine fehlermeldung und gar nichts.

Es ermutigt so niemand ihr an sich gutes system zu erweitern und wird es so uninteressant.

**Comment by holgerd** [comment]
Similar report from july 28:

	
Hallo liebes wheelmap-Team!
Ich habe jetzt leider schon seit längerem immer wieder Probleme, neue Orte auf der Karte einzutragen, bzw zu speichern. Nachdem ich alle Informationen eingegeben habe und auf speichern geklickt habe (bei dem neuen Eingabeformular), passiert einfach gar nichts. Ist so ein Problem vielleicht schon bekannt?

**Comment by holgerd** [comment]
similar report from july 26:

	
Eine Funktion "neuen Ort hinzufügen" bei wheelmap funktioniert nicht. Habe mehrfach versucht einen neuen Ort einzutragen: Ruheplatzstraße 12, 13347 Berlin, Himmelbeet, voll Rollstuhlgerecht + Rollstuhlgerechtes WC, Urban Gardening Project...

**Comment by holgerd** [comment]
Ich habe den Ort in Graz auf OSM gesucht und er scheint tatsächlich nicht eingetragen zu sein:
http://www.openstreetmap.org/edit?node=270508833#map=20/47.07036/15.40172

**Comment by holgerd** [comment]
@lennerd Hab ein Problem gefunden in Wheelmap Webapp:

- Ich bin eingeloggt und lege einen neuen Ort an und durchlaufe die Schritte bis zur "Alle Eingaben Korrekt"-Seite: http://wheelmap.org/nodes/new/overview?node=%5Bobject%20Object%5D . Ich drücke auf "Speichern"
- Ich erwarte dass ich eine Bestätigung sehe dass gespeichert wurde
- Stattdessen passiert garnichts und ich bleibe auf der Seite

**Comment by lennerd** [comment]
Like I wrote in Slack the problem is already solved on Staging. At the moment we have problems with the language strings inside the form. We are working on it.

**Comment by holgerd** [comment]
I just re-tested it on staging now and it works.

**Comment by holgerd** [comment]
ok ist zwar viel englisch auch in der frz version aber ich habe zumindest keine komischen keys gesehen. und es ging

**Comment by holgerd** [comment]
It now works live. thanks @lennerd 

@Svenyo Kannst du die Nutzer die sich beschwert haben bitte informieren?
