### ISSUE TITLE
New logging strategy

### ISSUE THREAD

**Issue by schultyy** [sozialhelden/wheelmap#351]
When the wheelmap application is going to be deployed on the new servers the logging strategy should be changed.
Right now the application logs to `log/production.log` or `log/staging.log` depending on the environment. We would like to change this to the following:

The application logs only to stdout and stderr respectively. Then via systemd we're able to capture the output and store it in the journal.

**Comment by Hoverbear** [comment]
This was addressed in #353 however we're waiting backend changes.

**Comment by Xylakant** [comment]
done and merged to the main infra-rebuild branch
