### ISSUE TITLE
Adapt unicorn script

### ISSUE THREAD

**Issue by schultyy** [sozialhelden/wheelmap#352]
In order to be able to deploy on the new environment `config/unicorn.rb` must be changed.

- There's no need for an environment differentiation anymore
  - The application path doesn't need to reflect this anymore
  - Uniform timeout configuration
  - Uniform worker process configuration
  - Unicorn needs to listen to port 3000 and accept connections from other hosts

**Comment by Xylakant** [comment]
I think that's done in the feature/infra-rebuild branch
