### ISSUE TITLE
Creating, editing, marking places is not shown

### ISSUE THREAD

**Issue by lennerd** [sozialhelden/wheelmap#356]
Since the 29.7. we have problems with creating, editing, marking places. We get many bug reports from users all over the world that places and changes for places are not shown on desktop and mobile devices while they are shown correctly on OSM.

**As I said this is the case since the 29th July and really urgent!**

From our Slack channel:

![pasted image at 2016_08_08 03_54 pm](https://cloud.githubusercontent.com/assets/1609692/17482687/3dbeaf40-5d83-11e6-89c5-4a0a200bb026.png)

> Hey Felix, vielleicht hilft folgender Hinweis. Seit dem 29.7. um ca. 12:30 haben wir null Zuwachs von WC tags. Zur selben Zeit gab es ein Deployment.

<img width="876" alt="screenshot 2016-08-08 16 15 30" src="https://cloud.githubusercontent.com/assets/1609692/17482730/612d2614-5d83-11e6-9f78-40ac9aae7be1.png">
<img width="166" alt="screenshot 2016-08-08 16 16 10" src="https://cloud.githubusercontent.com/assets/1609692/17482751/70a4fb08-5d83-11e6-8cd1-ec68c584a02b.png">

> [15:58]
> Darüber hinaus konnten wir über Librato feststellen, dass sich die Anzahl der markierten Orte in den letzten Tagen stetig vergrößert hat, während die Anzahl markierter Toiletten gleich blieb.
Die Zahl in Librato stimmt mit dem Counter auf der Karte (unten links) überein. Diese Zahl kommt wiederum aus der Datenbank. Ich weiß nicht, in wie weit das weiterhilft.

> [16:00]
> Noch viel interessanter ist die Tatsache, dass, wie gesagt, in Librato die Zahl stetig steigt, im Backend aber seit dem 30.7. keine Orte mehr geändert/angelegt wurden. Seltsame Diskrepanz.

**Comment by Svenyo** [comment]
Folgende Beispiele einer Nutzerin könnten darauf hinweisen, dass es mit dem Wheelchair-Toilet-Tag zu tun haben könnte, der in einigen Fällen angezeigt wird, der Wheelchair-Status-Tag aber nicht (siehe Issue #334).

Ich habe auf Wheelmap.org Punkte gefunden, wo die Rollstuhlgerechtigkeit von
nicht von OSM übernommen werden.
Es sind folgende Orte:
-Ich habe diesen Ort auf Wheelmap gefunden: Bio Hofladen
(http://wheelmap.org/nodes/3008841013)
-Ich habe diesen Ort auf Wheelmap gefunden: Biergarten
(http://wheelmap.org/nodes/273930476)
-Ich habe diesen Ort auf Wheelmap gefunden: Sandkasten
(http://wheelmap.org/nodes/-297045248)
-Ich habe diesen Ort auf Wheelmap gefunden: Parkplatz/Parkhaus
(http://wheelmap.org/nodes/-25366060)
-Ich habe diesen Ort auf Wheelmap gefunden: Bushaltestelle
(http://wheelmap.org/nodes/273931790)
-Ich habe diesen Ort auf Wheelmap gefunden: Bushaltestelle
(http://wheelmap.org/nodes/3951759215)
-Ich habe diesen Ort auf Wheelmap gefunden: Bushaltestelle
(http://wheelmap.org/nodes/274852707)
Könnt ihr bitte nachschauen, was es für ein Problem vorliegt.
Vielen Dank schon im Voraus für eure Mühen.

**Comment by Svenyo** [comment]
Aus der Mail einer Nutzerin in Peru:

- When qualified an existing site, the information is not saved. That place will remain in gray qualify despite trying several times. Even waiting a few days, still it appears in gray that place.
- When adding a new place, it is the same, the information is not saved. Even waiting a few days, still does not appear on the map added the new place.

All these problems have seen that happen from the web wheelmap.org. I am told that the same problems also manifest apps using iOS and Android.

**Comment by Svenyo** [comment]
Aus der Mail von Nutzer*innen in Japan (vom 6.8.2016):

Could you check the data server?

______

https://goo.gl/2xGWbR

this osm data is created about 17hours ago 

it including 

amenity=cafe
Wheelchair=no

it didnt show  in wheelmap
http://goo.gl/j3t5nN

**Comment by Xylakant** [comment]
so the osm2psql import process is running but as metioned before we're running out of space on the fast disks, so it's slower than it used to be. setting up a new server is currently in the works but taking longer than we hoped for since the old server has been set up manually.

since the can be correlated with a deployment it would be good if someone could double check that the problem is not related to the app/mysql side of things. maybe an import worker dying or similar?

**Comment by Xylakant** [comment]
this mysql error looks like a plausible candidate: 

Mysql2::Error: Incorrect key file for table './wheelmap_production/pois.MYI'; try to repair it: INSERT INTO `pois` (`osm_id`,`version`,`tags`,`geom`,`status`,`created_at`,`updated_at`,`node_type_id`,`region_id`,`toilet`) VALUES (4322711412,4,'---\nleisure: pitch\nname: Nan Shae Soccer Field (နန်းရှ့​ေဘာ​ေလုံးကွင်း)\nname:my: \"နန်းရှေ့ဘောလုံးကွင်း\"\nsport: soccer\n',GeomFromWKB(0x00000000014058076f69afc7034035fddda059a73b,0),8,'2016-08-09 10:08:20','2016-08-09 10:08:20',127,NULL,NULL),(4322711412,5,'---\nleisure: pitch\nname: Nan Shae Soccer Field (နန်းရှေ့ဘောလုံးကွင်း)\nname:my: \"နန်းရှေ့ဘောလုံးကွင်း\"\nsport: soccer\n',GeomFromWKB(0x00000000014058076f69afc7034035fddda059a73b,0),8,'2016-08-09 10:08:20','2016-08-09 10:08:20',127,NULL,NULL) ON DUPLICATE KEY UPDATE `pois`.`osm_id`=VALUES(`osm_id`),`pois`.`version`=VALUES(`version`),`pois`.`tags`=VALUES(`tags`),`pois`.`geom`=VALUES(`geom`),`pois`.`status`=VALUES(`status`),`pois`.`updated_at`=VALUES(`updated_at`),`pois`.`node_type_id`=VALUES(`node_type_id`),`pois`.`region_id`=VALUES(`region_id`),`pois`.`toilet`=VALUES(`toilet`)

**Comment by lennerd** [comment]
@Svenyo Whats the status here?

**Comment by Svenyo** [comment]
Markings, edits and newly created places are displayed again without any further delay.
