### ISSUE TITLE
Fix styling errors in the toolbar in Firefox

### ISSUE THREAD

**Issue by lennerd** [sozialhelden/wheelmap#36]
<img width="698" alt="screenshot 2015-10-05 19 35 41" src="https://cloud.githubusercontent.com/assets/1609692/10288298/48ef9452-6b98-11e5-8426-98faca423c8e.png">

**Comment by yeralin** [comment]
Fixed. Implemented using Flexboxes. Flexbox doesn't work with buttons in Firefox, so I had to use additional div inside class="corrector".

See in https://github.com/yeralin/wheelmap

**Comment by lennerd** [comment]
Hey @yeralin, thank you for your great help and the fix for this issue! :+1:

Please make a quick [PR](https://help.github.com/articles/using-pull-requests/) for this, so we can review and discuss the changes there.

PS: What's #hacktoberfest?

**Comment by yeralin** [comment]
Done.

https://hacktoberfest.digitalocean.com/

**Comment by lennerd** [comment]
Nice idea of a hackathon. :+1: And of course nice project you choosed to help in. :sunglasses:

**Comment by yeralin** [comment]
Should it be pull requested into Assets branch? 
There is one: Merge pull request #30 from sozialhelden/assets

**Comment by lennerd** [comment]
No, just create your own branch in your forked repository and use this branch to make a PR.

**Comment by lennerd** [comment]
Oh no, this is a branch where we refactore our dependency management of javascript assets. The master branch is fine for your changes.
