### ISSUE TITLE
Use Digicert SSL Certificate for wheelmap.org (live)

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#360]
We are using cloudflare at the moment but have bought a SSL certificate from digicert in February.

I think we should use the SSL certificate we bought?

**Comment by Xylakant** [comment]
we're currently not using the digicert certificate since we move pretty much everything under the cloudflare umbrella afterwards. we'd need a larger cloudflare plan to use our own certificate on CF.

**Comment by 1000miles** [comment]
@holgerd please clarify with felix.

**Comment by 1000miles** [comment]
@holgerd as clarified [here](update/header-title-i18n-keys-community-support) here i would suggest to close this ticket for now and re-open it as soon as a larger cloudflare plan is chosen?

**Comment by 1000miles** [comment]
As long as we don't use the bigger cloudflare plan as stated [above](https://github.com/sozialhelden/wheelmap/issues/51#issuecomment-263537808), this cert is useless. Closed for now.
