### ISSUE TITLE
502 Bad Gateway after signup on staging

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#361]
- I signup as new user holger@mailinator.com on staging. On "please add email" on wheelmap staging I add holger@mailinator and submit
- I expect to be logged in
- Instead, I get a 502 gateway error

find selenium test attached:
[seleniumtest - WM staging SignupAndDel holgermailinator.zip](https://github.com/sozialhelden/wheelmap/files/421944/seleniumtest.-.WM.staging.SignupAndDel.holgermailinator.zip)

**Comment by lennerd** [comment]
@1000miles @schultyy @Hoverbear Not sure but maybe related to the email service problem not sending mails correctly? Anything in the logs?

**Comment by holgerd** [comment]
this magically fixed itself.
worksforme
