### ISSUE TITLE
500 error when submitting /admin/providers/new

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#365]
- I login as admin to /admin
- I go to http://wheelmap.org/admin/providers/new and give a test name and select a 44x44 icon (see billa_png.png attachment)
- I expect the new provider to be created
- Instead, I see a "Something went wrong" error

![billa_png](https://cloud.githubusercontent.com/assets/218506/17921138/c2f196a8-69d8-11e6-8056-d756170e3b71.png)

**Comment by 1000miles** [comment]
@holgerd 

cc @schultyy 

**Estimation to fix**
- approx. 0,5-1 day (research, fix & tests)

**Explanation**

After a bit of research this seems to be the reason that raises the error:
```
I, [2016-09-07T12:20:20.319640 #10777]  INFO -- : Started POST "/admin/providers" for 123.456.789.100 at 2016-09-07 12:20:20 +0200
I, [2016-09-07T12:20:20.326169 #10777]  INFO -- : Processing by Admin::ProvidersController#create as HTML
I, [2016-09-07T12:20:20.326313 #10777]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"{hidden}", "provider"=>{"name"=>"testt_20160907_3", "logo"=>#<ActionDispatch::Http::UploadedFile:0x007efcbc65a490 @tempfile=#<Tempfile:/tmp/RackMultipart20160907-10777-4aizgv>, @original_filename="c2f196a8-69d8-11e6-8056-d756170e3b71.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"provider[logo]\"; filename=\"c2f196a8-69d8-11e6-8056-d756170e3b71.png\"\r\nContent-Type: image/png\r\n">}, "commit"=>"Provider anlegen"}
I, [2016-09-07T12:20:20.337981 #10777]  INFO -- : Completed 500 Internal Server Error in 12ms (ActiveRecord: 1.6ms)
F, [2016-09-07T12:20:20.346338 #10777] FATAL -- :
ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
  lib/rack_i18n_locale_switcher.rb:32:in `call'
  librato-rack (0.6.0) lib/librato/rack.rb:94:in `process_request'
  librato-rack (0.6.0) lib/librato/rack.rb:64:in `call'
```

which specifically involves these parts:
https://github.com/sozialhelden/wheelmap/blob/master/lib/rack_i18n_locale_switcher.rb#L11-L33
https://github.com/sozialhelden/wheelmap/blob/master/lib/rack_i18n_locale_switcher.rb#L58-L66

**Comment by 1000miles** [comment]
@holgerd 

This issue is fixed now. :) 

Please go to admin dashboard on production and check:
- /admin/providers/new 
- /admin/provided_pois

**Comment by holgerd** [comment]
lgtm!
