### ISSUE TITLE
language dropdown unreadable in narrow browser

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#366]
![wheelmap_-_rollstuhlgerechte_orte_finden](https://cloud.githubusercontent.com/assets/218506/17928104/6bc835dc-69f9-11e6-9ab6-8002f28c0abb.png)

- I'm in Firefox or Chrome mac and make the window narrow.
- I expect the language dropdown to "drop down"
- Instead, it "drops upward" (See screenshot) so I can not select a different language

**Comment by lennerd** [comment]
Did you try to reload the page after resizing the window?

**Comment by holgerd** [comment]
@lennerd reloading helped, now it scrolls downwards as expected. Is there a better way or just a #wontfix ?

**Comment by lennerd** [comment]
I would vote for #wontfix, as I think only a very few people resize the window like this. Either you have a small screen or a desktop size screen.
