### ISSUE TITLE
add monitoring to OSM syncing

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#369]
In July it appened that the sync between Wheelmap and OSM did not work for a few weeks, which lead to inconsistencies between the two databases.

Add monitoring/alerts to this sync service so we learn sooner if that happens again and can act upon it.

**Comment by schultyy** [comment]
What should happen in case the importer does not work anymore? Shall it send and email to a specified address or shall it post something into Slack?

**Comment by 1000miles** [comment]
@holgerd 
cc @schultyy 

**Estimation**
- as we need to put research on the OSM syncing first, the estimation of this ticket is open and will be added asap

**Comment by Xylakant** [comment]
we do have monitoring in the sense that we do paint pretty graphs in munin but nobody looks at them. There's no alerting.

**Comment by Xylakant** [comment]
we currently don't have any alerting except on total failure

**Comment by 1000miles** [comment]
@Xylakant suggested to trigger librato or new relic for email alerts for which we need to define the criteria first.

**Comment by schultyy** [comment]
From Holger:

> My hunch is it’s either a couple of minutes behind or not working at all, right? So a day should be fine, right?

**Comment by Xylakant** [comment]
There's no need to rely on hunches: the sozialhelden team has access to the munin graphs that display the current lag. sadly, the chef manifest that adds accounts is broken and so I'd have to add everyone manually :( I'll add an image of the last 7 days:

![osm_replication_lag-week](https://cloud.githubusercontent.com/assets/337823/18589061/3f5187c8-7c29-11e6-9498-e630cf6011d3.png)

**Comment by holgerd** [comment]
so 7000 seconds = ca 2h lag, correct?

**Comment by Xylakant** [comment]
about 2h, yes. I'd add a little safety margin since the lag depends on the amount of activity on the OSM, but anything longer than 6 hours or so would be an indicator of a major problem.

**Comment by Hoverbear** [comment]
The chef `users` module bug is fixed in `4.0.0` and up. :)

**Comment by schultyy** [comment]
So to sum this up what we discussed over the last couple of days:
- Monitoring takes action when the replication lag gets bigger than 7000 seconds
- It will send an email to a predefined address informing about the lag

**Comment by holgerd** [comment]
We decided not to monitor this automatically but @schultyy will look into this weekly (recurring calendar event for himself).

#wontfix

cc @1000miles
