### ISSUE TITLE
API returns 500 on IS24 integration

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#388]
sebastian From IS24 just came by and told me that the Wheelmap Integration on all their Exposé page is returning an 500 error since yesterday 6:30pm. No Wheelmap places are shown anymore. Example (scroll down to and click wheelmap on the map): https://www.immobilienscout24.de/expose/90136266

**Comment by Hoverbear** [comment]
No errors in console either:

![screen shot 2016-09-08 at 10 54 22](https://cloud.githubusercontent.com/assets/130903/18343209/afdf86a2-75b2-11e6-8d04-3d5a80e13cef.png)

**Comment by Xylakant** [comment]
We'd need some info regarding the endpoint being called, the error returned from the wheelmap api (if any), the ip address from which the requests are sent so that we have a chance to find something in the logs.

**Comment by holgerd** [comment]
Sebastian: If this is confidential, jsut email this info to me and we'll move to a private issue tracker.

**Comment by SebastianStiehl** [comment]
Since 11:10 we cant reproduce the errors. Did you change something on your site? To be save and secured we are now changing the api calls to https.

**Comment by Xylakant** [comment]
we disabled the redirect to https, but we'd like to enable it again.

**Comment by SebastianStiehl** [comment]
we are now live with https and it seems to work. @holgerd from my point of view this issue can be closed.

**Comment by Xylakant** [comment]
let me first re-enable the redirect and see if it works.

**Comment by Xylakant** [comment]
seems to work perfectly fine
