### ISSUE TITLE
https://wheelmap...-Links redirect to homepage instead of detail page

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#389]
- On the IS24 map of https://www.immobilienscout24.de/expose/90136266 I click on a optician "Wilhelm" in Ulm, the URL is https://www.wheelmap.org/nodes/1477243434 .
- I expect to get to https://wheelmap.org/nodes/1477243434 .
- Instead, I get to https://wheelmap.org/map#/?toilet=yes.unknown&zoom=15

**Comment by Hoverbear** [comment]
I was not able to replicate this issue. I was directed to `http://wheelmap.org/nodes/1477243434` after clicking the Optiker.

**Comment by holgerd** [comment]
I have the issue when using Chrome.

In Firefox it works but I get a warning:
![dieser_ort_ist_auf_wheelmap_org__wilhelm__optiker__einkaufen__ulm](https://cloud.githubusercontent.com/assets/218506/18344227/b0054334-75b6-11e6-826f-b4238bbbe3bc.png)

**Comment by Xylakant** [comment]
as per #51 the canonical url should be https://wheelmap.org/nodes/1477243434 and not  https://www.wheelmap.org/nodes/1477243434 (no www). I added a specific rule to redirect www. in CF

@holgerd that warning is unrelated. there are some logo urls that use plain http and trigger a mixed content warning when using https.

**Comment by Hoverbear** [comment]
(Mixed content warnings are very common on most sites, it's nothing to be concerned about for now)
