### ISSUE TITLE
Make sure indoor views are disabled in streetview

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#401]
- I go to https://wheelmap.org/nodes/4398847391
- I expect to see the streetview of Zimmerstraße 26
- Instead, I see an indoor 360° view of a haircutter.

We never want 360° photos on wheelmap detail pages. @lennerd noted that in his opinion we already changed the embed code to work that way. This needs to be reviewed again.

**Comment by holgerd** [comment]
related #480

**Comment by holgerd** [comment]
IMHO:
https://developers.google.com/maps/documentation/javascript/3.exp/reference?hl=de#StreetViewSource

**Comment by 1000miles** [comment]
@schultyy 

I put a bit research on the documentation page @holgerd posted (https://developers.google.com/maps/documentation/javascript/3.exp/reference). I assume this seems to be the interesting part for us?

`google.maps.StreetViewLocationRequest`
![00000241](https://cloud.githubusercontent.com/assets/4077916/21816609/fb0921a0-d760-11e6-9d71-ede4ae200662.png)

`google.maps.StreetViewSource.OUTDOOR`
![00000240](https://cloud.githubusercontent.com/assets/4077916/21816620/009bb92a-d761-11e6-879e-fe0ef244db61.png)

**Comment by 1000miles** [comment]
And from what I can see so far it is already specified in the [`nodes.coffee`
 file](https://github.com/sozialhelden/wheelmap/blob/8df541107ed785f82a2436ebe53d11129e7e2fba/app/assets/javascripts/nodes.coffee#L263-L266):

```javascript
streetViewLocationRequest =
    location: position,
    preference: google.maps.StreetViewPreference.NEAREST,
    source: google.maps.StreetViewSource.OUTDOOR
```

@TODO

- [ ] Find out why specifying OUTDOOR views only doesn't work

**Comment by 1000miles** [comment]
> We never want 360° photos on wheelmap detail pages. 

@holgerd Just to check-in again: You don't want 360° panorama views at all or just only outdoor views?

**Comment by holgerd** [comment]
@1000miles we only want outdoor views. All StreetView images are 360°, you are right. ;)

**Comment by holgerd** [comment]
This is not resolved.

Places still show indoor panoramas in StreetView. Example:
https://wheelmap.org/nodes/4034138645

**Comment by Hoverbear** [comment]
@holgerd Yes the patch is not live yet, sorry.

**Comment by 1000miles** [comment]
Perfect, let's close this ticket then. :)
