### ISSUE TITLE
nodes/new page empty

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#407]
- I'm using Chrome and am logged and got to "add a place". I see the form and click the back button in the browser and then the forward button.
- I expect to see the form again
- Instead, I see the wheelmap header but nothing else 

Screenshot by the user:
![addaplace](https://cloud.githubusercontent.com/assets/218506/18826780/75261686-83cf-11e6-8a20-a910798800ee.png)

This also suggests a SSL problem maybe.

**Comment by holgerd** [comment]
my screenshot:
![wheelmap_-_find_wheelchair_accessible_places](https://cloud.githubusercontent.com/assets/218506/18826866/e753b7fe-83cf-11e6-981a-981e92f65742.png)

**Comment by lennerd** [comment]
I see the form but with multiple layout errors:

![screenshot 2016-09-26 10 25 16](https://cloud.githubusercontent.com/assets/1609692/18827556/b6f40b00-83d3-11e6-9a69-fcf829db3dba.png)

I also don't see any errors about not secured assets. Can you please open the log, reload the page and make a screenshot of the console tap. (Alt + Cmd + I)

**Comment by lennerd** [comment]
Did a little bit research on @holgerd machine. The developer tools show no errors and the React app root is rendered correctly. No further DOM is created though. Very strange … 🤔

**Comment by holgerd** [comment]
For now I asked the reporting user to try to reload or use a different browser.
