### ISSUE TITLE
Can not add nodes in iOS or Android app

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#410]
- I'm logged in as "holgerd" in iOS app 3.0.2 and add a new node. 
- I expect the change to show up on  https://www.openstreetmap.org/user/holgerd/history within minutes.
- Instead, nothing shows up. But when I add a node using the webapp this changeset shows up.

**Comment by holgerd** [comment]
![server_metrics___librato](https://cloud.githubusercontent.com/assets/218506/18835042/82f807ea-83f9-11e6-8671-dfddec04f612.png)

https://metrics.librato.com/share/dashboards/y5pi2ryo?duration=2419200

It seems there were no new nodes added with the iOS or Android app since Sept 9th.

**Comment by holgerd** [comment]
@thermann78 just successfully added this new node using the live iOS app
https://www.openstreetmap.org/node/2926670705

**Comment by Xylakant** [comment]
The date lines up fairly well with the switch to SSL. The last items were added roughly in the timeframe where SSL was disabled due to https://github.com/sozialhelden/wheelmap/issues/388 (Theres a bit of a time shift, which may be due to TZ errors)

**Comment by holgerd** [comment]
Although it seemed to work for @thermann78 it still does not work on my iphone.

**Comment by Xylakant** [comment]
closing in favor of the app-specific tickets

**Comment by thermann78** [comment]
Wait, I just marked it, I didn't add the place.

**Comment by Xylakant** [comment]
ok, marking was known to work before.
