### ISSUE TITLE
Wrong Url redirects

### ISSUE THREAD

**Issue by schultyy** [sozialhelden/wheelmap#411]
When I try to access `https://staging.wheelmap.org/community_support/new` I get redirected to `https://community.wheelmap.org/en/new-android-app-wheelmap/`.

Other Urls I tried:
- https://staging.wheelmap.org/bugreport/new
- https://staging.wheelmap.org/community_bugreport/new
- https://staging.wheelmap.org/community/new

This blocks #370 right now

**Comment by Xylakant** [comment]
The trigger seems to be new:

https://staging.wheelmap.org/community/new fails https://staging.wheelmap.org/community works.

**Comment by Xylakant** [comment]
I can explain the behavior: URLs that get handled by the wheelmap app are whitelisted, everything that is not on the list gets proxied to community.wheelmap.org for historic reason (*). Anything ending in /new triggers wordpress' helpful "I'll guess what you meant even though you never asked me to" feature which picks the first article starting with "new" and redirects there.

So the quick fix is whitelist any of those url prefixes, the long-term fix is drop the stupid proxy rule.

(*) back when we had the front page delivered from the community server, but couldn't have the domain apex point there.

**Comment by schultyy** [comment]
I understand. I'll go ahead and whitelist our new url then.

**Comment by 1000miles** [comment]
This seems to be fixed and there is no redirecting when calling `https://staging.wheelmap.org/community_support/new`.

Closing.

![00000270](https://cloud.githubusercontent.com/assets/4077916/24243789/96ac9c7a-0fbc-11e7-9149-e3008652d3b6.png)
