### ISSUE TITLE
Enhance nodes API to accept measurements generated by Project Tango

### ISSUE THREAD

**Issue by schultyy** [sozialhelden/wheelmap#413]
As requested by SMF, the nodes API should be enhanced in a way so measurements can be stored for each node.

Pasting the proposal from SMF here:

```
Messungsbild hochladen:

/api/nodes/{node_id}/measurement
POST (wie /api/nodes/{node_id}/photos)

Response:
{"message":"OK", "id": 123456}

===========================================

Metadaten hochladen:

/api/nodes/{node_id}/measurement/{id}/meta
PUT oder POST

{
        'type': 'DOOR/STEPS/RAMP/TOILET',
        'description': 'some user description',
        'data': {
                // daten abhängig von dem typ
                // DOOR
                'width': 1.04 //meter

                // STEPS
                'height': 0.11 //meter

                // RAMP
                'angle': 15.42 // degree

                // TOILET
                'space': 2.04 // m^2

        }
}
```

A measurement consists for an image (Messungsbild) and meta data such as:
- width (in meters)
- height (in meters)
- angle (in degrees)
- space (in m^2)

**Comment by schultyy** [comment]
After phone calls with Raphael Heber, Tim Freiheit and Holger Dietrich the following was agreed upon:

The first version if this feature will include the following:

- Two new API endpoints which will allow creating new measurement records (details below)
- Measurement photos for a node will be returned together with the other regular photos for that node.

It will not be possible to fetch meta information for a measurement yet. One option here would be to provide these via another endpoint. All apps (iOS, Android, Web, Windows Phone) then need to talk to that endpoint as well. This solution is not feasible right now due to budget reasons.

The other option would be to enhance the existing endpoint which delivers photos for a node. This could possibly break existing installations on Android, iOS, Windows Phone and also the web application.

## Create new measurement

There will be two endpoints handling creation of measurements.

1. Upload measurement image

```
POST /api/nodes/:nodeid/measurement
(image is sent as multipart)

=> 201 Created
{"id": 4234523543}
```

This will return `201 Created` with the new image id if successful.

2. Upload metadata
Upload metadata for an existing measurement image.

```
POST /api/nodes/:nodeid/measurement/:id/metadata
{
        'type': 'DOOR/STEPS/RAMP/TOILET',
        'description': 'some user description',
        'data': {
                // Data depends on selected type
                // DOOR
                'width': 1.04 //meter
                // STEPS
                'height': 0.11 //meter
                // RAMP
                'angle': 15.42 // degree
                // TOILET
                'space': 2.04 // m^2
        }
}
```
This will return 404 if the image id is not present.

Depending on `type` different attributes are allowed/not allowed. 

Type `door`:
Only `width` will be allowed. Unit is meters and the value must be of type integer.

Type `steps`:
Only `height` will be allowed. Unit is meters and the value must be of type integer.

Type `ramp`:
Only `angle` will be allowed. Unit is degrees and the value must be of type float/double.

Type `toilet`:
Only `area` will be allowed. Unit is m^2 and the value must be of type float/double.

**Comment by timfreiheit** [comment]
the width and height should have the type float/double

**Comment by schultyy** [comment]
With #428 being merged the only thing left to do is storing the metadata per picture. This will probably will happen via a metadata table where each row will be associated with one picture from the `photos` table.

**Comment by 1000miles** [comment]
**Update, 2016, Oct 10:**

@holgerd 

cc @RaphaelHeber 

The PR "Store measurement photos" #428 has been merged and deployed on staging today. 
Happy to get image examples to test the feature properly at our end or feedback after you have tested it. Merci.

**Comment by holgerd** [comment]
I installed the REST Client [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm) on my Chrome browser to test this on node https://staging.wheelmap.org/nodes/1336912426 .

- I created a POST request:
`https://staging.wheelmap.org/api/nodes/1336912426/measurement/?api_key=MYAPIKEY`
- I expect "201 created"
- Instead, I get
`{
    "error": "No route matches '/api/nodes/1336912426/measurement', check API documentation for available resources: /api/docs/resources"
}`

**Comment by Hoverbear** [comment]
@holgerd According to https://github.com/sozialhelden/wheelmap/pull/418 the endpoint is `https://staging.wheelmap.org/api/nodes/1336912426/measurements/?api_key=MYAPIKEY`

Note `measurements`.

Example:

```
curl -XPOST "https://staging.wheelmap.org/api/nodes/1336912426/measurements/?api_key=SOMEAPIKEY"
{"error":"photo is missing"}
```

**Comment by holgerd** [comment]
Ok now it works!

I edited the examples in https://github.com/sozialhelden/wheelmap/issues/413#issuecomment-251432176 so it now says "measurement**s**" with an "s". 😄

**Comment by schultyy** [comment]
Removing the "Review" label here because this ticket is not completely done yet.

**Comment by schultyy** [comment]
Fetching metadata can be implemented when API versioning is done (that topic is discussed in #468).

**Comment by timfreiheit** [comment]
The Api for storing the measurement metadata does not allow to send an empty description:
for example:
```json
{
	"metadata": {
		"data_type":"door",
		"description":"",
		"data":{
			"width":0.36413
		}
	}
}
```

this results int the following error message:

Status Code: 422 
```json
{
  "errors": {
    "measurements": [
      "ist nicht gültig"
    ]
  }
}
```

**Comment by schultyy** [comment]
@timfreiheit I made the corresponding changes and it's now available on Staging.
