### ISSUE TITLE
[Translations] Fetch translations from Transifex (#54 & #396)

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#417]
Fetch the latest translations for following issues:
- Hauptmenüpunkt "Projekte" umbenennen in "Mitmachen" #396
- Add/Update place types (key/value-pairs) = categories #54

**Comment by 1000miles** [comment]
@Svenyo We made a quick difference check  of all current resources files (EN) in the wheelmap project and on transifex via https://www.diffchecker.com/ (date: 2016-11-16)

As far as we can see only `categories.yml` seems to differ while the other resources files are identical. However, we included them all (10 items) in the zip file so you can have a look at them. 

[resource_files_for_translations_20161116.zip](https://github.com/sozialhelden/wheelmap/files/594573/resource_files_for_translations_20161116.zip)

**Comment by karolinamakaruk** [comment]
@1000miles I found new categories in https://github.com/sozialhelden/wheelmap/files/594573/resource_files_for_translations_20161116.zip
It looks good for me.

**Comment by 1000miles** [comment]
Closed. Deployed on production with release: https://github.com/sozialhelden/wheelmap/releases/tag/production-20161129150628.
