### ISSUE TITLE
Large number of new POis created at  location 52.513, 13.388 by wheelmap.org

### ISSUE THREAD

**Issue by mmd-osm** [sozialhelden/wheelmap#439]
There seems to be some strange issue with new POIs creaed on wheelmap.org. As someone noted on the [German forum](http://forum.openstreetmap.org/viewtopic.php?pid=612649#p612649), there are currently 75 POIs (!!) at the following node location: https://www.openstreetmap.org/node/4437324390.

57 of those POIs have been added in the last 6 days alone.

Also, check out this overpass turbo query returning those POI nodes: http://overpass-turbo.eu/s/jlI

Can you please investigate if this is maybe some strange bug?

**Comment by holgerd** [comment]
Yes, we'll investigate. Thanks for letting us know!

**Comment by holgerd** [comment]
Cause seems to be a bug in an old version of our iPhone app. Hope id does not happen again but I'll monitor the area for a while and notify wheelmap users who do create nodes at that location.

**Comment by mmd-osm** [comment]
Thanks a lot. Indeed the number of affected users seems to be rather small, although they're quite activate. Let's see if these users will apply the update in the near future. 😃

**Comment by mmd-osm** [comment]
I'd suggest to keep this issue open as long as it is not resolved and we're seeing more reports of it in the German Forum. Thanks.

**Comment by holgerd** [comment]
We did not see an new occurences.
