### ISSUE TITLE
Default to English via geolocation?

### ISSUE THREAD

**Issue by voltagex** [sozialhelden/wheelmap#44]
Currently the site switches back to German frequently. Can't pin it down to any one action.

**Comment by joustava** [comment]
Could be related to #50 ?

**Comment by lennerd** [comment]
Hey @voltagex thanks for creating an issue. What browser do you use? And which situtations do you have your language resetted to German?

**Comment by lennerd** [comment]
@voltagex Did you have time to test this for us again?

**Comment by voltagex** [comment]
Sorry! It's on my list for this weekend.

**Comment by voltagex** [comment]
Still on my to do list :disappointed:

**Comment by lennerd** [comment]
Do you maybe remember which setup you used when this bug appeared?

**Comment by voltagex** [comment]
Front page is in German even though I'm sending `Accept-Language:en-GB,en;q=0.8,en-US;q=0.6,en-AU;q=0.4`

**Comment by lennerd** [comment]
Ah, okay. So this is a duplicate: #67

If you still interested in helping out with this, please take a look in the linked issue. :relaxed:

**Comment by voltagex** [comment]
If I find the other place where this was happening I'll let you know :) Sorry for the duplicate.

**Comment by lennerd** [comment]
Okay, that would be nice.

> Sorry for the duplicate.

No problem. We're happy when people contribute. :wink:
