### ISSUE TITLE
photon.komoot.de is down

### ISSUE THREAD

**Issue by Hoverbear** [sozialhelden/wheelmap#441]
Currently the backend for [photon.komoot.de](http://photon.komoot.de) is down which makes creating new nodes impossible (on the website).
![screen shot 2016-10-17 at 16 06 12](https://cloud.githubusercontent.com/assets/130903/19440827/a612e138-9483-11e6-9c11-8977b1f70306.png)

```
curl "photon.komoot.de/api/?q=berlin"
```

**Comment by holgerd** [comment]
maybe you want to open an issue here: https://github.com/komoot/photon

**Comment by Hoverbear** [comment]
Related issue: https://github.com/komoot/photon/issues/239

**Comment by holgerd** [comment]
> which makes creating new nodes impossible.

That only affects the webapp, right? The API should still work afaik.

**Comment by Hoverbear** [comment]
Right. Sorry, I should have specified that.

**Comment by holgerd** [comment]
It's up again and I could just add a new node with the live webapp. so closing this now.

**Comment by Hoverbear** [comment]
👐
