### ISSUE TITLE
[active_admin] Check category assignment

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#448]
This is a follow-up ticket for issue #404 

Holger wrote:

> @1000miles I tested this. It does not give me a 500 error but two things came up:
> 
>  tourism exists twice on staging in the dropdown. I tested with both.
>    I changed the category from "Bildung" to "Tourismus" and clicked "Node type aktualisieren"  and then went to https://staging.wheelmap.org/nodes/new/name_category to see where "museum" shows up.
>        >  I expected it to be in the new category "Tourismus"
>         > Instead, it is still in "Bildung"

**Comment by 1000miles** [comment]
@holgerd 

> tourism exists twice on staging in the dropdown.

I set the `tourism` (id: 5) back to `education` (identifier) via the rails console because somehow editing directly in the admin dashboard doesn't work. Not sure if this ever worked but for now this should be fixed. Please let me know if there are any further strange occurrences. 

![wheelmap_categories](https://cloud.githubusercontent.com/assets/4077916/20307543/3d1bc342-ab40-11e6-8a78-12a91093ec3d.png)

**Comment by holgerd** [comment]
lgtm
