### ISSUE TITLE
/architektur leitet auf 404 weiter

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#450]
We published material for architetcure students under wheelmap.org/architektur , eg. here:
https://www.youtube.com/watch?v=xUJbkHoYOnk
http://raul.de/referenzen/barriefreiheit-in-der-architektur/
https://de.wikipedia.org/wiki/Wheelmap.org#cite_note-8

When I click the link today it redirects to:
https://news.wheelmap.org/wheelmap-botschafter/barrierefreie-architektur/

Instead, I am not able to find the content anymore.

**Comment by Hoverbear** [comment]
Found this in the nginx configuration while looking for something else:

![screen shot 2016-10-20 at 10 25 31](https://cloud.githubusercontent.com/assets/130903/19552307/9548849c-96af-11e6-9ab3-3264a53ac6d9.png)

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd Can you please specify here what to do when users call `wheelmap.org/architektur`? 

Usually wordpress redirects the user automatically to the follow-up path that has been changed but the `404 - not found` indicates that this page has been removed permanently on wordpress. 

Shall we delete the redirect from `/architektur` nginx or will you create a new page and send us the url to redirect?

**Comment by 1000miles** [comment]
P.S. Can you also please specify where to direct following links because they also return a `404 - not found` at the moment.

- `/goes-london` => http://wheelmap.org/impressum/archiv/ => https://news.wheelmap.org/impressum/archiv/ (error 404)
- `/goeslondon` => http://wheelmap.org/impressum/archiv/ => https://news.wheelmap.org/impressum/archiv/ (error 404)

**Comment by holgerd** [comment]
ping @Svenyo

**Comment by Svenyo** [comment]
Hi @1000miles, for 
wheelmap.org/architektur
wheelmap.org/goes-london
wheelmap.org/goeslondon

there are no contents on the new blog, so an error 404 seems right to me.

**Comment by holgerd** [comment]
ok so this is expected behavior.
