### ISSUE TITLE
Icons on node_types page return 404 - Not Found

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#476]
- I go to `staging.wheelmap.org/node_types` of the staging server
- I expect all icons on that page to be rendered but instead I see that some icons are not displayed (e.g. tea_house.png, massage.png, naval_museum.png, etc.).
- I log into the staging server and see that the mentioned icons are existent in the `apps/assets/images/icons` folder.

Please see:

![icns_on_staging_server](https://cloud.githubusercontent.com/assets/4077916/20014856/1ef6533a-a2b9-11e6-9ef9-a97e1ac91cad.png)

Looking at the web developer tool we interestingly see that these missing icons are supposed to be on a URL that is `https://community.wheelmap.org` but not `https://wheelmap.org` itself.

![wheelmap_icons_404](https://cloud.githubusercontent.com/assets/4077916/20015222/dd2c61a4-a2ba-11e6-961b-a365898415fb.png)

**Comment by 1000miles** [comment]
This issue blocks the introduction of new categories. We will investigate the redirection path.

**Comment by 1000miles** [comment]
As this is happening to a couple of icons, we will give explanation to 1 example only. 

What we have found out so far:

-  the icon-image `spa.png`  is listed in the folder as `app/assets/images/icons/spa.png` and can be found in the generated zip file under `/public/icons.zip` but it it is neither displayed on the `node_types page` of the staging server (http://staging.wheelmap.org/node_types) nor displayed on production (http://wheelmap.org/node_types). 
- so according to rails 4 asset pipeline `spa.png` should be compiled to the folder `public/assets/icons` which should result in the location `public/assets/icons/spa.png` but it doesn't. 
- `spa.png` was introduced in april 2016 by this commit https://github.com/sozialhelden/wheelmap/commit/2d2190d50d6bc819dd15f8d46773b8bd4ba6e72f


`spa.png` listed in the folder `public/assets/icons`?

- `spa-9833e9c3701c9e83d9db846a7e9d39de0b1ef970081c4f8a0e7e5a182d0dab1a.png` => yes!
- `spa@2x-f8cbe567eab32cf49a0f242d126e746c10a24bdf2dbd1f60a0a6f9210efeef19.png` => yes!
- `spa.png` => no!


### production:

- https://wheelmap.org/assets/icons/spa-9833e9c3701c9e83d9db846a7e9d39de0b1ef970081c4f8a0e7e5a182d0dab1a.png => yes, displayed!
- https://wheelmap.org/assets/icons/spa-9833e9c3701c9e83d9db846a7e9d39de0b1ef970081c4f8a0e7e5a182d0dab1a.png => yes, displayed!
- https://wheelmap.org/assets/icons/spa.png => `Error 404`

in comparison:
- https://wheelmap.org/assets/icons/cinema-95d916cefc4817f113e1208b3dfdb95ad5f79a720679a18d3728e2da133e434b.png => yes, displayed!
- https://wheelmap.org/assets/icons/cinema@2x-ea3f2e217d5f171b62eceb87cd3c53bdbbbdc72dec83e541ba8677351c66f903.png => yes, displayed!
- https://wheelmap.org/assets/icons/cinema.png => yes, displayed!

---

### staging:

- https://staging.wheelmap.org/assets/icons/spa-9833e9c3701c9e83d9db846a7e9d39de0b1ef970081c4f8a0e7e5a182d0dab1a.png => yes, displayed!
- https://staging.wheelmap.org/assets/icons/spa-9833e9c3701c9e83d9db846a7e9d39de0b1ef970081c4f8a0e7e5a182d0dab1a.png => yes, displayed!
- https://staging.wheelmap.org/assets/icons/spa.png => `Error 404`

in comparison:
- https://staging.wheelmap.org/assets/icons/cinema-95d916cefc4817f113e1208b3dfdb95ad5f79a720679a18d3728e2da133e434b.png => yes, displayed!
- https://staging.wheelmap.org/assets/icons/cinema@2x-ea3f2e217d5f171b62eceb87cd3c53bdbbbdc72dec83e541ba8677351c66f903.png => yes, displayed!
- https://staging.wheelmap.org/assets/icons/cinema.png => yes, displayed!

**Comment by 1000miles** [comment]
@holgerd 

cc @Svenyo & @karolinamakaruk 

The PR #482 has been deployed on staging today with release [staging-20161125141452](https://github.com/sozialhelden/wheelmap/releases/tag/staging-20161125141452) and can be reviewed here: https://staging.wheelmap.org/en/node_types

Follow-up ticket: #484 (art_museum.png not found)

![node_types_25112016](https://cloud.githubusercontent.com/assets/4077916/20627802/c1d4daa8-b322-11e6-837c-65cd5fd922ca.png)

**Comment by karolinamakaruk** [comment]
@1000miles I tested it. I can see all icons on http://staging.wheelmap.org/node_types. Only art museum is missing, but as I understand is another issue. LGTM.

**Comment by 1000miles** [comment]
@karolinamakaruk 

Thank you for your feedback. Yes, we are currently working on the issue with `art_museum.png` (https://github.com/sozialhelden/wheelmap/issues/484). Will deploy this on production tomorrow.

**Comment by 1000miles** [comment]
Closed. Deployed on production with release: https://github.com/sozialhelden/wheelmap/releases/tag/production-20161129150628.
