### ISSUE TITLE
Bug: changeset created by android_visitor contains new nodes

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#477]
- I expect that non-loggedin users on wheelmap can not create new nodes. They only can add changes which are then posted as wheelmap_visitor or [wheelmap_android](https://www.openstreetmap.org/user/wheelmap_android).
- But I look at this [changeset](http://www.openstreetmap.org/changeset/43210369) and see a node called ["Jablonec nad Nisou"](https://www.openstreetmap.org/node/4450390192/history) has been created (version 1). The changeset is by wheelmap_android

**Comment by holgerd** [comment]
I just looked at http://hdyc.neis-one.org/ and saw that android_visitor added 687 nodes until today.

**Comment by holgerd** [comment]
Update, today the stats say 688 created nodes by wheelmap_android user

**Comment by schultyy** [comment]
I did some digging for this one. I saw that there's now user called `wheelmap_android` in our database.

**Comment by schultyy** [comment]
By chance I also found out, that wheelmap_visitor is able to actually create nodes via the API.

**Comment by schultyy** [comment]
TODO for me: Find out how many edits over the time are made by the `wheelmap_android` user.

**Comment by Svenyo** [comment]
Update from SMF (Raphael Heber):

"Es sind noch 77 Installationen mit einer Version von 2012 (siehe Tabelle).
Es könnte sein, dass das Geräte mit Android 2 sind, was wir ja nicht mehr supporten. Das können wir aber leider nicht aus den Daten ablesen.

![unnamed](https://cloud.githubusercontent.com/assets/20318534/22970400/4d7734b8-f372-11e6-8691-6731540457b4.png)

Wir können den Fehler bei der aktuellen Version auch nicht reproduzieren und glauben auch nicht, dass es Probleme gibt wenn dem Default Token das Recht entzogen wird Orte anzulegen.

Es ist nicht einfach nachzuvollziehen wo der Fehler herkommt.

Eine unserer Vermutungen ist, dass es passiert wenn man einen Ort erstellt, dieser aber nicht sofort hochgeladen werden kann und man sich dann abmeldet.
Die App versucht dann den Ort später zu speichern. Dann aber nicht mehr mit dem Key des Nutzers, da dieser ja nicht mehr eingelogged ist.

Die Rechte für den von euch genannten User anzupassen dürfte appseitig nicht zu Problemen führen."

**Comment by Svenyo** [comment]
@schultyy @1000miles I suggest we proceed as suggested: Changing the permission for this user into tagging the accessibility and toilet status only.

**Comment by holgerd** [comment]
yes let's put this in production

**Comment by 1000miles** [comment]
Done in PR #569 & #578.

Deployed to [production](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170222124705) today. Closing.
