### ISSUE TITLE
[Translations] Locale Switcher does not apply to header > navigation

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#479]
**Preconditions:**
- we look at the `navigation` in the header 
- we check the transifex key-value pair of `projects: Get Involved` that has been changed from `projects: Projects` in the resource file [relaunch.yml](https://github.com/sozialhelden/wheelmap/pull/475/files#diff-d250e923a9a2d44e6e304a690ffaa755) (EN)
- we compare the english relaunch.yml file with the spanish [relaunch.yml](https://github.com/sozialhelden/wheelmap/pull/475/files#diff-b22223ea41ce8d94668e909ce78923e6) and see that `projects: Proyectos` has also changed to `projects: Involúcrate` which is correct
- we export the newest translations with `bundle exec rake i18n:js:export` and can see them modified in `app/assets/javascripts/i18n` which is correct
- we check the spanish javascript file [es.js](https://github.com/sozialhelden/wheelmap/pull/475/files#diff-1bbd4dfc4e71abab8ef1e184e0297bfe) and can confirm that also here the key-value-pair has changed from `projects: Proyectos` to `projects: Involúcrate` which is correct

**Now:**
- we go to `https://staging.wheelmap.org` and switch to `german` and get the value `Mitmachen` for `projects` => correct!
- we go to `https://staging.wheelmap.org` and switch to `english` and get the value `Get Involved` for `projects` => correct!
- we go to `https://staging.wheelmap.org` and switch to `french` but get the value `Get Involved` for `projects` => not correct!
- we go to `https://staging.wheelmap.org` and switch to `spanish` but get the value `Get Involved` for `projects` => not correct!
- this goes on with the other languages...

**Conclusion:** 
- it seems the locale switcher does not work for the navigation neither locally, nor `staging` and `production` server
- for example on wheelmap.org when switching to spanish it should display `Proyectos` (old value) but it still shows `Projects` (old value) => https://github.com/sozialhelden/wheelmap/blob/master/app/assets/javascripts/i18n/es.js#L769
- no matter what language we switch to the same behavior applies to the others as well

**Comment by 1000miles** [comment]
This issue blocks:
- issue #396

**Comment by holgerd** [comment]
@lennerd Do you have an idea what the problem is here?
