### ISSUE TITLE
Add Mapillary to detail pages

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#480]
Suggestion from the OSM forum:
Add Mapillary and OpenStreetView to detail pages
https://forum.openstreetmap.org/viewtopic.php?id=55958

Sounds like a good idea, maybe as an addition instead of a replacement of Google Streetview.

https://github.com/mapillary/mapillary-js seems to be free for non-profits and I did not find a widget option for OSV yet.

**Comment by holgerd** [comment]
I've created a mapillary user "sozialhelden" for this and put in in the shared 1p-vault.

**Comment by holgerd** [comment]
as step one, just Mapillary.

**Comment by holgerd** [comment]
@schultyy In case there is no mapillary photo, I now see a black rectangle. Example: https://staging.wheelmap.org/nodes/3017232832

Can the default background color of the widget be white or be omitteded completely?

**Comment by schultyy** [comment]
@holgerd Sure, I'll have a look into that. We could also just not render it if there's nothing to show.

**Comment by holgerd** [comment]
@schultyy Yes, not rendering if empty is a good soloution if that's possible!

**Comment by schultyy** [comment]
@holgerd On Staging there's now a version available which only renders Mapillary if there's actual content available. Otherwise it stays hidden.

**Comment by holgerd** [comment]
great! LGTM

**Comment by schultyy** [comment]
As discussed on Slack this will go into production beginning next week

**Comment by Svenyo** [comment]
@schultyy cc @holgerd Seems like the mapillary view we've implemented is not complete. 
Peter from Mapillary told me in an email: 

"There are however missing assets that can't be loaded like https://asset3.wheelmap.org/assets/stepper-play.svg that make the icons for navigation not be visible. Wold be great if you can fix that for a better integration :)"

**Comment by peterneubauer** [comment]
Yes, I'm seeing the missing assets in e.g. https://wheelmap.org/nodes/2370599905

**Comment by Svenyo** [comment]
Thanks @peterneubauer for commenting on this. Could you write down your further recommendations on how to fix the navigation icons?

**Comment by peterneubauer** [comment]
As you can see,
the icons are supposed to be under 

    https://asset3.wheelmap.org/assets/stepper-left.svg

etc, but give a 500 there.

Not sure how to fix it on your server but either move the MpaillaryJS script or the .svg assets somewhere so they can be found?

<img width="1440" alt="fullscreen_2_14_17__12_51_pm" src="https://cloud.githubusercontent.com/assets/11977/22928000/7ede5f0e-f2b4-11e6-9086-027f1b63065c.png">

**Comment by schultyy** [comment]
So I found out why there's a 500:

```
2017/02/15 09:51:01 [error] 22604#0: *46493905 rewrite or internal redirection cycle while internally redirecting to "/assets/stepper-play.svg.html.html.html.html.html.html.html.html.html.html.html", client: <REDACTED>, server: asset0.wheelmap.org, request: "GET /assets/stepper-play.svg HTTP/1.1"
```

It appears to be a NGINX rule which is either missing or not working properly.

**Comment by schultyy** [comment]
To check whether the problem is in the NGINX configuration or with wheelmap, I created a small example application with the snippet from the [Mapillary-js GitHub page](https://github.com/mapillary/mapillary-js). There everything works just fine. Even though the browser receives HTTP 500 errors right now, they occur because the file cannot be found.
My solution on this is to copy over the missing assets from the GitHub repository into our assets directory to ensure they can be loaded properly.

**Comment by Svenyo** [comment]
Thanks, @schultyy, let's try this.

**Comment by 1000miles** [comment]
@Svenyo We have deployed our fix to staging today. Can you please review the fix, e.g. via this node? https://staging.wheelmap.org/nodes/1229408775

Merci.

**Comment by Svenyo** [comment]
@1000miles Looks great! Can be deployed to prodution.

**Comment by schultyy** [comment]
Is in [production](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170216155747) now 🙆 .

**Comment by peterneubauer** [comment]
Great, looks good!
