### ISSUE TITLE
Bug: POI is not appeared on the wheelmap

### ISSUE THREAD

**Issue by karolinamakaruk** [sozialhelden/wheelmap#485]
I added test POI on the browser and Android app.
I expected to see POI on the OSM map and wheelmap.
Wheelmap didn't not mark POI, I can see it only on Open Street Map.

Here is the example: https://www.openstreetmap.org/node/4520334989

**Comment by holgerd** [comment]
the sync was not working and Jan reactivated it. I see the node now on wheelmap: https://wheelmap.org/nodes/4520334989

**Comment by holgerd** [comment]
i removed the node from osm
