### ISSUE TITLE
bug: "toilets:wheelchair=unknown" written to OSM

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#492]
- I am logged in as holgerd and use https://wheelmap.org/en/nodes/new/ to add the new node "Labyrintoom" to Wheelmap/OSM with wheelchair=no and no more info to the toilet, leaving it at "unknown" like this:

![image](https://cloud.githubusercontent.com/assets/218506/20787775/ea4da7b4-b7ad-11e6-8967-6dd9e0865ce2.png)

- I expect that only wheelchair=no is written to the node in OSM
- Instead, I also see toilets:wheelchair=unknown in the node: http://www.openstreetmap.org/node/4531573193 .
![image](https://cloud.githubusercontent.com/assets/218506/20787862/5c609fe6-b7ae-11e6-8261-478f2126281e.png)

 I also see that there are thousands of tags like this in OSM: https://taginfo.openstreetmap.org/tags/toilets%3Awheelchair=unknown#overview (maybe all added this way?)

**Comment by holgerd** [comment]
related: #505

**Comment by schultyy** [comment]
We deployed the fix for this one directly on production because on Staging all jobs talking to OSM are disabled.

**Comment by 1000miles** [comment]
Re-opening, ready for review. @holgerd & @Svenyo

**Comment by 1000miles** [comment]
Thanks for the feedback, @karolinamakaruk ! 🎉
