### ISSUE TITLE
image alert text missing

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#497]
- I'm logged-in and on a detail page, eg. https://wheelmap.org/nodes/1873679231
- I expect to see a description on what kind of photos are appropriate for wheelmap
- Instead, I just see "Alert" in any language

<img width="1060" alt="dieser_ort_ist_auf_wheelmap_org__edeka__spatkauf__einkaufen__berlin" src="https://cloud.githubusercontent.com/assets/218506/20825577/60d778f8-b865-11e6-864d-e740b4078b0a.png">

**Comment by 1000miles** [comment]
@holgerd 

It seems some magic has happend here and the error is gone, or?

![00000216](https://cloud.githubusercontent.com/assets/4077916/21143846/92d5087a-c148-11e6-8822-86caeae435b2.png)

**Comment by holgerd** [comment]
@1000miles you need to be logged-in to see this.

**Comment by holgerd** [comment]
@Svenyo 's hunch is that the translation key is missing in the code. As far as we remember this alert text was once hard-coded by @lennerd .

**Comment by 1000miles** [comment]
@holgerd cc @Svenyo

So I digged a bit into this case. There was already an `alert` key in `en/relaunch.yml` in a branch (2016, sept 6) that has been merged into master but was somehow deleted again from master. Maybe it got lost during the rebase process? 

I am not sure if this key worked or was hard coded because the structure being used was `t('.alert')` instead of `t('nodes.node_photos.alert')`. Will investigate further.

**Comment by holgerd** [comment]
@1000miles find the text here: https://github.com/sozialhelden/wheelmap/pull/327#issuecomment-234933168

**Comment by 1000miles** [comment]
@holgerd cc @Svenyo @karolinamakaruk 

**Update, 2017-01-10:**
- PR #540 is deployed to [staging](https://github.com/sozialhelden/wheelmap/releases/tag/staging-20170111105152) and ready for review 
   - (preconditions: you have to log in and accept the terms in order to see the image alert)

**Comment by 1000miles** [comment]
@holgerd & @Svenyo 

ping, still waiting for your approval to deploy to production. :)

**Comment by 1000miles** [comment]
Approved live by @holgerd . :)

**Comment by 1000miles** [comment]
**Update, 2017-01-16:**

Deployed to production today with [release 20170116133241](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170116133241). Closed.
