### ISSUE TITLE
API category requests always in German

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#50]
Raphael from SMF schreibt:
es scheint bei der iOS Version generell ein Problem mit den APIs des Kategorie-Filters zu geben. Der erscheint bei mehreren Sprachen auf deutsch.
Die Namen kommen von der Wheelmap API so zurück. Das solltet ihr euch mal anschauen.
http://staging.wheelmap.org/api/categories?locale=en-GB liefert z.B. deutsche Ergebnisse zurück.

**Comment by holgerd** [comment]
Status?

**Comment by lennerd** [comment]
@RaphaelHeber Is this still active?

http://staging.wheelmap.org/api/categories?locale=en-GB looks wrong. Maybe try to change the locale to `en`: http://staging.wheelmap.org/api/categories?locale=en

**Comment by RaphaelHeber** [comment]
Hi Lennart,

kann die Links leider beide nicht aufrufen:
{"error":"invalid API key."}

LG
Raphael

**Comment by holgerd** [comment]
In der URL musst Du deinen eigenen API key einsetzen den Du in http://staging.wheelmap.org/profile/edit findest (Achtung: dafür musst du angemeldeter user auf staging sein, anders als auf live).

Also:
http://staging.wheelmap.org/api/categories?locale=en&api_key=[deinAPItokenhier]

**Comment by RaphaelHeber** [comment]
Tut mir leid aber ich verstehe nicht ganz um was es eigentlich geht.
Kann mich bitte jemand aufklären (wenn es relevant ist)?

LG
Raphael

2015-12-03 12:08 GMT+01:00 Holger Dieterich <notifications@github.com>:
