### ISSUE TITLE
Bug: Toilet status - unknown appears on OSM

### ISSUE THREAD

**Issue by karolinamakaruk** [sozialhelden/wheelmap#505]
- I opened Mozilla Firefox and I logged in on the: https://wheelmap.org/en/map#/?zoom=19 as karolinamakaruk user

- I added a new place: I created a bar and gave a name test POI. I added the address Ribnitzer Str. 11
In the information on wheelchair accessibility I chose: Wheelchair accessible, and
Toilet status - unknown
[poi detail](https://wheelmap.org/en/map#/popup/4550973093?lat=52.570391925331755&lon=13.499195873737335&zoom=19)

- On OSM I can see toilet status - unknown: [osm detail](http://www.openstreetmap.org/node/4550973093)

![screenshot from 2016-12-14 11 30 32](https://cloud.githubusercontent.com/assets/19149119/21178648/df128854-c1f0-11e6-9a11-2f77144d43bd.jpeg)

- status unknown shouldn't appear on OSM

**Comment by karolinamakaruk** [comment]
I tested also Android app, and result is the same.
- Wheelmap version: 3.0.3 (Build 515)
- Android model: Project Tango Tablet Development Kit
- Android version: 4.4.2

http://www.openstreetmap.org/node/4553744889

**Comment by holgerd** [comment]
maybe related: https://github.com/sozialhelden/wheelmap/issues/512

**Comment by schultyy** [comment]
This is fixed in #530
