### ISSUE TITLE
[Translations] Fetch & introduce Community Support Form

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#508]
This is a follow-up ticket for #370 so that we keep track of the upcoming translation process. 

@TODO:
- [x] Send merged `relaunch.yml` (EN) file to Sozialhelden => tbd by @1000miles
- [x] Upload `relaunch.yml`(EN) file on transifex to roll out the translation process => tbd by @Svenyo 
- [x] Deploy DE & EN version to live server after approval => tbd by @1000miles
- [x] Inform devs when translations are ready => tbd by @Svenyo 
- [x] Fetch translations from transifex => tbd by @1000miles
- [x] Deploy to staging => tbd by @1000miles
- [x] Deploy all translated files to live server after approval => tbd by @1000miles

**Comment by 1000miles** [comment]
@Svenyo As discussed please find attached the merged into master version of the resource file `relaunch.yml` (EN) that you can upload on transifex. :)

[EN_relaunch.yml.zip](https://github.com/sozialhelden/wheelmap/files/651874/EN_relaunch.yml.zip)

**Comment by Svenyo** [comment]
@1000miles cc @holgerd The updated source file has been uploaded to Transifex and the translation process has been started. Translations will be ready on Tuesday.

**Comment by 1000miles** [comment]
Great, thanks for the info. :)

**Comment by 1000miles** [comment]
**Update, 2016-12-22:**

Deployed to production with release [20161222101339](https://github.com/sozialhelden/wheelmap/releases/tag/production-20161222101339) today. Closed.
