### ISSUE TITLE
Add "FAQ"-Link to main menu

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#513]
between "contact" and "report a problem"

if DE: to german FAQ
else: to english FAQ

**Comment by 1000miles** [comment]
**Update, 2017-01-09:**

- deployed to staging, 2017-01-06
- deployed to production, 2017-01-09 with release 20170109110124](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170109110124)
