### ISSUE TITLE
main menu overlaps icons

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#514]
<img width="837" alt="wheelmap_-_rollstuhlgerechte_orte_finden" src="https://cloud.githubusercontent.com/assets/218506/21384579/68e8c672-c76b-11e6-9e8c-bcb76c5c7074.png">

**Comment by 1000miles** [comment]
**Update, 2017-01-09:**

- deployed to staging, 2017-01-06
- deployed to production, 2017-01-09 with [release 20170109110124](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170109110124)
