### ISSUE TITLE
Implementing Czech (cs) as a new language

### ISSUE THREAD

**Issue by Svenyo** [sozialhelden/wheelmap#515]
- Create a map version for Czech: //wheelmap.org/cs/map
- Implement Czech = "Čeština" in the dropdown menu
- Fetch translations from Transifex

**Comment by 1000miles** [comment]
**Update, 2016-12-21:**

@Svenyo cc @holgerd @karolinamakaruk 

Following tasks have been done today and can be reviewed:

- set `cs` as new available locale - PR #518 
- fetch translations for `cs` - PR #517 
- deploy to staging with [release 20161221152553](https://github.com/sozialhelden/wheelmap/releases/tag/staging-20161221152553)

**Comment by Svenyo** [comment]
Looks fine! Can be deployed.

**Comment by 1000miles** [comment]
**Update, 2016-12-22:**

Deployed to production with release [20161222101339](https://github.com/sozialhelden/wheelmap/releases/tag/production-20161222101339) today. Closed.
