### ISSUE TITLE
Implementing Portuguese (pt) as a new language

### ISSUE THREAD

**Issue by Svenyo** [sozialhelden/wheelmap#516]
- Create a map version for Portuguese: //wheelmap.org/pt/map
- Implement Portuguese = "Português" in the dropdown menu
- Fetch translations from Transifex

**Comment by 1000miles** [comment]
As discussed with @Svenyo today we are supposed to use following locale versions for portuguese:
- `pt` https://github.com/sozialhelden/wheelmap/tree/master/config/locales/pt
- `pt_BR` https://github.com/sozialhelden/wheelmap/tree/master/config/locales/pt_BR

@holgerd Please decide what to do with this locale folder `pt_PT` (this seems to be redundant):
https://github.com/sozialhelden/wheelmap/tree/master/config/locales/pt_PT

**Comment by 1000miles** [comment]
**Update, 2016-12-21:**

@Svenyo cc @holgerd @karolinamakaruk 

Following tasks have been done today and can be reviewed:

- set `pt` as new available locale - PR #518 
- fetch translations for `pt` - PR #517 
- deploy to staging with [release 20161221152553](https://github.com/sozialhelden/wheelmap/releases/tag/staging-20161221152553)

**Comment by Svenyo** [comment]
@1000miles Done the review. The wording of the accessibility status is a bit too long to fit in the buttons, but looking at the pt_BR version, it's the same there. The rest is fine. I'll say: deploy to production and we'll take care of the wording later.

**Comment by 1000miles** [comment]
@Svenyo Alright, thanks for letting us know.

**Comment by 1000miles** [comment]
**Update, 2016-12-22:**

Deployed to production with release [20161222101339](https://github.com/sozialhelden/wheelmap/releases/tag/production-20161222101339) today. Closed.
