### ISSUE TITLE
[Menu] Remove nav item "Über wheelmap"

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#526]
As agreed with @svenyo today we want to get rid of the nav item `Über wheelmap` in the main menu because of following reasons:
- we don't have enough space for the main menu anymore when adding `FAQ` and `Reiseführer` as new nav items
- `Über wheelmap` and `FAQ` would link to the same page (https://news.wheelmap.org/faq)

**Comment by 1000miles** [comment]
@svenja cc @holgerd 

If we remove the nav item `Über wheelmap` should we also remove the key (:about_wheelmap) from all `locale/relaunch.yml` or is it enough to only update the `en/relaunch.yml` file and send it to you for transifex?

**Comment by Svenyo** [comment]
It should be enough to change it in the english source file. For the new "travel guide" in the menu we'd need translations anyways.

**Comment by 1000miles** [comment]
@Svenyo Merci for the quick feedback.

**Comment by 1000miles** [comment]
**Update, 2017-01-09:**

- deployed to staging, 2017-01-06
- deployed to production, 2017-01-09 with [release 20170109110124](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170109110124)
