### ISSUE TITLE
API::NodeController#create behaves differently on Staging

### ISSUE THREAD

**Issue by schultyy** [sozialhelden/wheelmap#537]
The `create` action in `api::NodesController` behaves different when it's in staging environment. Instead of enqueuing the job it's creating the Node directly.

```ruby
if Rails.env.staging?
  @node.version = 1
  @node.osm_id = Poi.highest_id + 1
  @node.save
else
  CreateNodeJob.enqueue(@node.lat, @node.lon, @node.tags, current_user, source('create'))
end
```
Reference:
https://github.com/sozialhelden/wheelmap/blob/master/app/controllers/api/nodes_controller.rb#L145-L151

This has several drawbacks:

- The API client can access the POI directly after it's been saved on Staging but not in any other environment (development, test, production)
- Client code has to take this behavior into account
- This behavior has to be tested extra
- This code fails with a `NoMethodError` when the database is empty because of `Poi.highest_id`: (https://github.com/sozialhelden/wheelmap/blob/master/app/models/poi.rb#L124): 
```ruby
def self.highest_id
    Poi.order('osm_id DESC').limit(1).select(:osm_id).first.osm_id
end
```

**Comment by Hoverbear** [comment]
[This last line](https://github.com/sozialhelden/wheelmap/blob/master/app/jobs/create_node_job.rb#L10) seems to do a similar-but-not-the-same thing.

```ruby
  def self.enqueue(lat, lon, tags, user, source)
    raise 'user not app authorized' unless user.app_authorized? # implies user.access_token.present?

    # Do not enqeue job if not in production or test environment
    return unless Rails.env.production? || Rails.env.test?
```
