### ISSUE TITLE
[Translation] Fetch translations for 'photos upload alert'

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#539]
This is a follow-up ticket for https://github.com/sozialhelden/wheelmap/issues/497

@TODO
- [x] add key and text to `de/relaunch.yml` and `en/relaunch.yml`- tbd by @1000miles
- [x] send updated `en/relaunch.yml` to @Svenyo  - tbd by  @1000miles
- [x] upload updated `en/relaunch.yml` to transifex - tbd by @Svenyo 
- [x] fetch latest translations from transifex after OK from @Svenyo - tbd by @1000miles
- [x] generate js translation files and check into git - tbd by @1000miles
- [ ] deploy to staging & get approval - tbd by @1000miles
- [ ] deploy to production - tbd by @1000miles

**Comment by 1000miles** [comment]
@Svenyo Please find attached the updated `en/relaunch.yml` file for ticket #497.

Happy to get info as soon as we can fetch the translations. :)

[EN_20170116_relaunch.yml.zip](https://github.com/sozialhelden/wheelmap/files/708592/EN_20170116_relaunch.yml.zip)

**Comment by 1000miles** [comment]
Partly done.

Deployed PR #560 on:
- staging [release 20170124094621](https://github.com/sozialhelden/wheelmap/releases/tag/staging-20170124094621) 
- production [release 20170124101806](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170124101806)

**Comment by Svenyo** [comment]
@1000miles 
For the 10 ordered languages the translations in Transifex are complete and can be pulled.

**Comment by 1000miles** [comment]
@Svenyo 

Great! Thanks for informing us. :)

**Comment by 1000miles** [comment]
@Svenyo cc @karolinamakaruk @schultyy 

As far as we can see from the last [Transifex Fetch](https://github.com/sozialhelden/wheelmap/pull/563) the `image upload alert text` is 100% fully translated on all languages. The few ones that are translated, we have already deployed to production.

Can you please confirm that we should wait a few more days before we fetch further translations?

**Comment by Svenyo** [comment]
@1000miles @schultyy Ok! We'll try to boost our community to add more translations. I'll let you know when it's worth fetching more.

**Comment by 1000miles** [comment]
@Svenyo Good morning. :) Any updates so far? I tried to pull the latest translations but it seems there haven't been any changes yet on this matter.

**Comment by Svenyo** [comment]
Dear @1000miles: This will still take some weeks – and just with all other features requiring translations they will probably never be complete after all.

**Comment by Svenyo** [comment]
@1000miles I've checked the most important languages e.g. Spanish, French, Portuguese and found that the image alert text has been successfully implemented with the right translations. 

This issue can be closed.

**Comment by 1000miles** [comment]
@Svenyo Alright, so we are closing this ticket and will pull the translations in another round along with other translation units, if there are any. Thank you.
