### ISSUE TITLE
Futher .CSV export for Streetspotr from Germany and UK

### ISSUE THREAD

**Issue by Svenyo** [sozialhelden/wheelmap#551]
Streetspotr requested more data for the countries Germany and UK where the step spots are very popular. The goal is to have data not only on the biggest cities, but also in the countryside or smaller cities to have a better distribution of "step spots".

The parameters of the export stay the same like in #433, except for the need to define specific cities or administrative boundaries. However, the new files shouldn't contain the node types already exported in the last files (which I will send @schultyy again in Slack).

We'll need two files for each country:

1. A CSV file with ALL data sets from Germany and UK complying with the filters:

- unknown accessibility
- categories: food, shopping, leisure, tourism (excluding the node type: memorial)

2. A CSV file with 15.000 nodes also with the parameters

- unknown accessibility
- categories: food, shopping, leisure, tourism (excluding the node type: memorial)

that is cut off after 15.000 random entries from all parts of the country but if necessary limited in the number of node types. Priority node types order: Node types from category 1. Food, 2. Shopping, 3. Leisure, 4. Tourism (excluding the node type: memorial).

**Comment by schultyy** [comment]
We send the files to @Svenyo via Slack. Therefore closing this one now.
