### ISSUE TITLE
Changing my email results in a new confirmation mail

### ISSUE THREAD

**Issue by Hoverbear** [sozialhelden/wheelmap#555]
As a user:

* I browse to https://wheelmap.org/profile/edit
* I change my email on the form.
* I hit "Speichern"
* I wait for the page to load.
* I receive an email containing the contents:

> Willkommen email@example.org!
>
> Du kannst deine E-Mail Adresse bestätigen indem du folgenden Link klickst:
>
> Mein Benutzerkonto bestätigen.

* The link points to http://wheelmap.org/users/confirmation (no key or id attached).

I expect when I change my email for it to either:

* Send a confirmation with a valid confirmation link.
* Not send me an email.

@holgerd Could you confirm the desired outcome of a user changing their email?

**Comment by holgerd** [comment]
@Hoverbear Yes this is a bug. And when I click the "confirmation link" I get the error message:

> An error prohibited to save a user:
Confirmation token can't be blank

<img width="1130" alt="find_wheelchair_accessible_places" src="https://cloud.githubusercontent.com/assets/218506/22109579/a559ad34-de58-11e6-91bf-a52fba4e54a8.png">

**Comment by Hoverbear** [comment]
Yup, https://github.com/sozialhelden/wheelmap/issues/556 fixes it.
