### ISSUE TITLE
I'd like to get nodes from the API that are changed since a given timestamp

### ISSUE THREAD

**Issue by opyh** [sozialhelden/wheelmap#558]
Hi,

I'm Sebastian Felix Zappe, currently working on accessibility.cloud 👋

1) For the project it would be great to have a way to get nodes from the API that have recently been changed so accessibility.cloud could fetch nodes without downloading a big dataset when syncing, saving bandwidth, CPU and our time. Is this already possible? If not, how could we make this possible?
2) To really have a data synchronization, an endpoint to get IDs of deleted nodes since a specified timestamp would be helpful.

@holgerd Could you see if this is possible and prioritize? :)

**Comment by schultyy** [comment]
So when can provide changed nodes easily already, for deleted ones we need to start writing some sort of log (another table just containing the Ids).

**Comment by holgerd** [comment]
yes

**Comment by schultyy** [comment]
@opyh I'm currently thinking of the frequency you might query this data. Is there a need to have them immediately after something changed or do you fetch them in longer intervals?

**Comment by schultyy** [comment]
We definitely have to change the import tasks for this, because they're the main actor when it comes to delete data. 
We probably also have to have a look at ActiveAdmin as well, because via the Admin interface a user can delete a POI as well.

**Comment by Xylakant** [comment]
using a trigger in the database may be an option, but much less visible.

**Comment by schultyy** [comment]
Maybe it makes sense to copy the CouchDB changes stream behavior.

**Comment by schultyy** [comment]
@opyh Thuy and me are currently talking about how the API response should look like. A first draft looks like this:

```json
[
  {
    "osm_id": 1,
    "action": "update",
    "updated_at": "30.01.2017 9:30"
  },
  {
    "osm_id": 2,
    "action": "delete",
    "updated_at": "29.01.2017 9:30"
  }
]
```

Does this already cover your requirements or do we have to include more information such as which field(s) have changed?

**Comment by opyh** [comment]
Cool, thank you very much, this should work! :) The server will just get the whole PoI again on re-import, no matter which fields changed exactly, so nothing else needed from AC's side.

**Comment by opyh** [comment]
If I can have one wish: Can we se UTC timestamps in milliseconds instead of date strings?

**Comment by Xylakant** [comment]
@opyh I absolutely recommend using ISO Date formats instead of UNIX Timestamps. Easier to debug for humans, includes TZ information if needed, DST switchovers and leap seconds get handled properly and in a defined fashion (POSIX is ignorant about leap seconds and counts each day the same, leading to a discontinuity at leap seconds). In general POSIX/UNIX Timestamps are pretty ignorant about a host of common time issues.

**Comment by 1000miles** [comment]
@opyh & @Xylakant Thanks, we'll consider your inputs.

**Comment by opyh** [comment]
@Xylakant Real ISO date strings would be fine for me too.

**Comment by schultyy** [comment]
@opyh We deployed it now on Staging. Can you test if everything works as expected?

Example request:
```
curl -XGET "https://staging.wheelmap.org/api/nodes/changes?api_key=<API_KEY>&since=2017-01-01"
```

**Comment by schultyy** [comment]
As agreed in Slack we would like to have the API endpoint to return paginated requests like the other endpoints do as well.

**Comment by 1000miles** [comment]
Deployed to [production](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170213125412) today.
