### ISSUE TITLE
[Footer] Add Github repo link to footer

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#561]
I noticed that currently there is no Github link anywhere on wheelmap.org. Providing a link increases the idea and benefit of open source work.

**Comment by holgerd** [comment]
i suggest rather to write a blog post addressing this

**Comment by Xylakant** [comment]
Why not do both?

**Comment by holgerd** [comment]
tbh, I fear the github badge is cluttering the already noisy UI. Also, we already have a section where we actively promote volunteering for wheelmap and it feels natural to add a section how developers could help. :)
