### ISSUE TITLE
[Cleanup] Remove unused translation keys from transifex resource files

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#568]
In our meeting with @Svenyo today we agreed on a cleanup of unused translation keys, e.g. when specific terms have already been deleted from the project. This way translation costs can be reduced.

**Comment by Svenyo** [comment]
@1000miles Is it possible to run an analysis on which strings are used and which not? I'd need some input here from you first.

**Comment by 1000miles** [comment]
Yes, we'll write a script for this. :)

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd 

As discussed please find below the current status (date: 2017-02-17) of translations keys.

#### Following are the keys that exist in `DE` files but are not used in `EN` files:
```shell
vagrant@vagrant:~/wheelmap$ bundle exec rake transifex:cleanup_de
---------------------------------
active_admin.yml
  de.activerecord
  de.devise
---------------------------------
authentication.yml
 # => nil
---------------------------------
categories.yml
 # => nil
---------------------------------
dates.yml
  de.datetime.distance_in_words.almost_x_years
  de.datetime.distance_in_words.less_than_x_minutes
  de.datetime.distance_in_words.less_than_x_seconds
  de.datetime.prompts
---------------------------------
ember.yml
 # => nil
---------------------------------
rails.yml
 # => nil
---------------------------------
relaunch.yml
  de.header.navigation.about_wheelmap
---------------------------------
wheelmap.yml
 # => nil
```

#### Following are the keys that exist in `EN` files but are not used in `DE` files:
```shell
vagrant@vagrant:~/wheelmap$ bundle exec rake transifex:cleanup_en
---------------------------------
active_admin.yml
 # => nil
---------------------------------
authentication.yml
  # => nil
---------------------------------
categories.yml
 # => nil
---------------------------------
dates.yml
 # => nil
---------------------------------
ember.yml
 # => nil
---------------------------------
rails.yml
 # => nil
---------------------------------
relaunch.yml
 # => nil
---------------------------------
wheelmap.yml
 # => nil
```

**Comment by Svenyo** [comment]
@1000miles The lines not used in the German version can be deleted. Thanks!

**Comment by 1000miles** [comment]
### 1. Active Admin 

a) As agreed with @Svenyo we are not going to remove the listed keys in `de/active_admin.yml` since the keys here effect only those who have access to the admin dashboard and therefore use german locale only.

b) Add missing key `DE` values for `translation missing: de.devise.failure.admin_user.not_found_in_database`

### 2. Remove keys:

**de/dates.yml**
``` 
  de.datetime.distance_in_words.almost_x_years
  de.datetime.distance_in_words.less_than_x_minutes
  de.datetime.distance_in_words.less_than_x_seconds
  de.datetime.prompts
```

   **de/relaunch.yml**
 ```
de.header.navigation.about_wheelmap
```
