### ISSUE TITLE
Use Poi.destroy_all instead of Poi.delete_all in PlanetReader

### ISSUE THREAD

**Issue by schultyy** [sozialhelden/wheelmap#577]
We found out that our newly created `PoiLog` only contains updated entries but no deleted ones. 

The reason for this is the following:
We invoke `Poi.delete_all` in `PlanetReader` and `delete_all` does not invoke any callbacks. 

In order to fix this, we need to change `delete_all` to `destroy_all`. `destroy_all` invokes callbacks but also loads each entry from database first. This might result in decreased performance but is the most reasonable way of fixing it right now.

**Comment by 1000miles** [comment]
Deployed to [production](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170222124705) today.
