### ISSUE TITLE
Change header on wheelmap.org (for facebook scraper)

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#58]
This
https://developers.facebook.com/tools/debug/og/object?q=www.wheelmap.org/map 

should look exactly like this:
https://developers.facebook.com/tools/debug/og/object?q=www.wheelmap.org

If translations are missing, please let me know by commenting this issue.

**Comment by lennerd** [comment]
I need to login to see the content of the linked pages. Can you maybe make a screenshot or describe the problem in more detail.

**Comment by holgerd** [comment]
scraper info for wheelmap.org
https://www.dropbox.com/s/qlbti2ksgi4hoxj/wheelmapohnemap.html?dl=0

scraper info for wheelmap.org/map
https://www.dropbox.com/s/eb12nft1fol0yvq/wheelmapMITmap.html?dl=0

url to download the copied HTML of scraper info:
https://www.dropbox.com/sh/cmkqqbzn4732lgv/AAB2yz8DBsqzfAf-W7FVA7ria?dl=0

**Comment by lennerd** [comment]
Should be fixed now. I also changed the meta information for the node detail pages to include a meaningful description and a twitter tag.
