### ISSUE TITLE
Add filtering nodes by category to nodes API

### ISSUE THREAD

**Issue by opyh** [sozialhelden/wheelmap#587]
Hi,

For a frontend makeover that will probably happen soon (details from @holgerd) it would be really cool if the nodes API endpoint would support filtering by category (for example by adding a `category_id=2` parameter to the query).

I know that this impacts caching, but as it would only filter by one category, not by multiple categories, the number of cached objects should still be in an acceptable range.

Background: When you currently filter by categories in the UI, the number of results is simply too low in lower zoom levels. Being able to filter by category on the server side should enable us to fix this and make the map much more usable for the 'show me where I can do X' use case.

**Comment by schultyy** [comment]
@opyh Just for clarification: This change would affect the `/api/nodes` endpoint, right?

**Comment by 1000miles** [comment]
ping @opyh :)

**Comment by opyh** [comment]
No, from what I get, Wheelmap's frontend uses the `/nodes` endpoint, so this one should support the new parameter. Sorry for the missing clarity, at the point of writing I didn't know there were two different controllers.

**Comment by 1000miles** [comment]
Good to know, thanks for clarification. :)

**Comment by opyh** [comment]
This is a blocker for the new frontend – is this issue part of an upcoming sprint?

**Comment by 1000miles** [comment]
@opyh 

Based on these resources 

- https://github.com/sozialhelden/wheelmap/blob/master/app/controllers/api/nodes_controller.rb#L62-L77
- https://wheelmap.org/en/api/docs/resources/nodes

there is already a way to filter via `category_id`, `node_id` and `bbox` params, or? Please let us know if you need anything else from us.

**Example request:**

```shell
➜  curl "https://wheelmap.org/api/nodes?api_key=[api_key]&node_type_id=42&category_id=5&wheelchair=unknown&per_page=2" 
```
**Example representation:**

```javascript
conditions:
  page:     1
  per_page: 2
  format:   json
  search:   education
meta:
  page:             1
  num_pages:        390785
  item_count_total: 781569
  item_count:       2
nodes:
  -
    name:                   Ecole élémentaire
    wheelchair:             unknown
    wheelchair_description: null
    wheelchair_toilet:      unknown
    node_type:
      id:         42
      identifier: school
    lat:                    14.1375188
    lon:                    -16.6961532
    id:                     -480084500
    category:
      id:         5
      identifier: education
    street:                 null
    housenumber:            null
    city:                   null
    postcode:               null
    website:                null
    phone:                  null
  -
    name:                   Pond Road Middle School
    wheelchair:             unknown
    wheelchair_description: null
    wheelchair_toilet:      unknown
    node_type:
      id:         42
      identifier: school
    lat:                    40.2364762
    lon:                    -74.6253129
    id:                     -480084135
    category:
      id:         5
      identifier: education
    street:                 null
    housenumber:            null
    city:                   null
    postcode:               null
    website:                null
    phone:                  null

```

**Comment by opyh** [comment]
This works as intended, so I think we can close this issue. Thanks for your help!

**Comment by anngreenberg** [comment]
As stated by @opyh, works as explained above, therefore closing this issue.
