### ISSUE TITLE
500 error on /api/node_types/4/nodes

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#589]
A user reported:

This endpoint doesn't work http://wheelmap.org/api/node_types/4/nodes?api_key=api_key&bbox=13.341,52.505,13.434,52.523&per_page=10&wheelchair=yes

____

I tested it and get a 500  error.

**Comment by thermann78** [comment]
This cannot work.

> api_key=api_key

**Comment by 1000miles** [comment]
@thermann78 i believe the api_key was intentionally replaced by @holgerd? however, even with a correct api_key i can confirm the reported `500 internal error` occurs.

**Comment by thermann78** [comment]
Okay, then there is another problem. But no, the api_key-string was part of the original bug report, that's why I guessed that this could be the mistake as it is the same spelling like in our API documenation.

**Comment by 1000miles** [comment]
First hunch: this might have something to do with the gem `inherited resources`. More research needed.

<img width="1263" alt="00000273" src="https://cloud.githubusercontent.com/assets/4077916/24361683/cac5b7de-130a-11e7-9218-2d9b16cddbff.png">

### Server output:

```shell
I, [2017-03-27T16:03:11.807355 #23766]  INFO -- : Started GET "/api/node_types/4/nodes?api_key=[FILTERED]&bbox=13.341,52.505,13.434,52.523&per_page=10&wheelchair=yes" for xx.xx.xx.xx at 2017-03-27 16:03:11 +0200
I, [2017-03-27T16:03:11.810470 #23766]  INFO -- : Processing by Api::NodesController#index as HTML
I, [2017-03-27T16:03:11.810569 #23766]  INFO -- :   Parameters: {"api_key"=>"[FILTERED]", "bbox"=>"13.341,52.505,13.434,52.523", "per_page"=>"10", "wheelchair"=>"yes", "node_type_id"=>"4"}
I, [2017-03-27T16:03:11.813877 #23766]  INFO -- : Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.6ms)
I, [2017-03-27T16:03:11.823889 #23725]  INFO -- : Started GET "/api/nodes?api_key=[FILTERED]&bbox=11.042161258954593,47.475705926101654,11.1084225504585,47.50586413065716&per_page=100" for xx.xx.xx.xx at 2017-03-27 16:03:11 +0200
I, [2017-03-27T16:03:11.825698 #23725]  INFO -- : Processing by Api::NodesController#index as JSON
I, [2017-03-27T16:03:11.825745 #23725]  INFO -- :   Parameters: {"api_key"=>"[FILTERED]", "bbox"=>"11.042161258954593,47.475705926101654,11.1084225504585,47.50586413065716", "per_page"=>"100"}
F, [2017-03-27T16:03:11.827909 #23766] FATAL -- :
NoMethodError (undefined method `find' for Api::NodeType:Module):
  app/controllers/api/nodes_controller.rb:199:in `collection'
  app/controllers/api/nodes_controller.rb:82:in `index'
  lib/rack_i18n_locale_switcher.rb:29:in `call'
  librato-rack (0.6.0) lib/librato/rack.rb:94:in `process_request'
  librato-rack (0.6.0) lib/librato/rack.rb:64:in `call'

```

**Comment by 1000miles** [comment]
Github automatically closes the tickets when you use the term `fixes #ticketnumber` in your PR. Since this needs final review by @karolinamakaruk I am opening it again.

**Comment by karolinamakaruk** [comment]
The bug is fixed. Everything works correctly now.

**Comment by Shamasher** [comment]
Hey guys,
I've just tested this endpoint and got 500 error

Have you deployed fix at wheelmap.org ?

**Comment by 1000miles** [comment]
Hi @Shamasher, we will deploy this fix tomorrow. Thanks for your interest and patience. :)

**Comment by 1000miles** [comment]
This bugfix has been deployed to live server with [production-20170330110932](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170330110932) today. :)

![00000277](https://cloud.githubusercontent.com/assets/4077916/24501727/11246738-154b-11e7-875f-828030935ac1.png)

**Comment by Shamasher** [comment]
thanks @1000miles !
Appreciate your help!
