### ISSUE TITLE
Import Streetspotr contributions CSVs

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#59]
These CSVs need to be imported:
https://www.dropbox.com/s/h6copt6wq8pji3c/2015-11-16-streetspotr-contributions-wheelmap-CSVs.zip?dl=0
(survey was 01.07.2015-05.11.2015)

There is a rake task for that (but that was before we had the toilet-feature!):
https://github.com/sozialhelden/wheelmap/blob/master/lib/tasks/streetspotr.rake

There is a method in this file to convert the wheelchair status which could be adapted to work with the toilet-tag as well. The data probably has no toilet information AFAIK.

**Comment by christoph-buente** [comment]
Actually the streetspotters answer 3 individual questions. It should now be much easier to import. Toilet and accessible entrance are separate answers.

**Comment by lennerd** [comment]
From our Slack channel posted by @christoph-buente an example for making an export of unmarked nodes for streetspotr:

``` shell
RAILS_ENV=production bundle exec rake export:for_streetspotr REGION="Berlin,Muenchen,Koeln,Duesseldorf,Nuernberg,Wilhelmshaven,Braunschweig,Fulda,Bottrop,Haltern Am See,Gladbeck,Mülheim an der Ruhr,Düren,Kreis Heidekreis,Jülich,Villingen Schwenningen" CATEGORIES="shopping,food,tourism" LIMIT=400
```

**Comment by christoph-buente** [comment]
@lennerd: The example was for an export, not for the import.

**Comment by holgerd** [comment]
- [ ] refactor import logic to reflect toilet status separately

**Comment by holgerd** [comment]
Important to know: the column "country" is wrong, ask Svenja.

**Comment by holgerd** [comment]
Suggestion

- [ ] import this CSV without toilet information (just as before)

We can re-import the toilet info later.

**Comment by lennerd** [comment]
Okay, the current state is that we have a working importer which adds the correct POI entries to the database. Unfortunately the created jobs inside the importer get stacked and are not executed.

**Comment by lennerd** [comment]
* [ ] Fix the importer or the job/task created in the importer to upload photos from streetspotr correctly.
* [ ] Try to find a way to not store the same images twice when the import command was used with the same data.
* [ ] Clear worker and rerun the import task from streetspotr.

**Comment by holgerd** [comment]
- [ ] have a look if old photos can be deleted.

**Comment by 1000miles** [comment]
In agreement with @holgerd and @Svenyo we have changed the streetspotr rake tasks addressed in PR #599 to:
- import only photos and their photo_url from the csv, omit wheelchair status and toilet status infos
  - check for photo duplicates before import

Now the rake tasks work again. :)

Some print out examples from our modified rake tasks: 
- `bundle exec rake streetspotr:check` via `streetspotr.rake`
- `bundle exec rake streetspotr:import` via `streetspotr.rake`

## Staging, 2017, June 8
### Check
```shell
Skipped: PHOTO 36185 already exists.
Skipped: The POI would be skipped.
Skipped: The POI 2273766967 would be skipped.
Skipped: The POI would be skipped.
Skipped: The POI -137614987 would be skipped.
Skipped: The POI would be skipped.
Skipped: The POI -137615036 would be skipped.
Skipped: The POI would be skipped.
Skipped: The POI 833239926 would be skipped.
Skipped: The POI would be skipped.
Skipped: The POI would be skipped.
Skipped: The POI would be skipped.
Skipped: The POI would be skipped.
Skipped: The POI 1480911991 would be skipped.
Skipped: The POI would be skipped.
Skipped: The POI 485664418 would be skipped.
Skipped: The POI would be skipped.

EXISTING: ProvidedPois: 3214, Photos: 25819.
WOULD SKIP: Photos: 930, ProvidedPois: 13724
WOULD SAVE ACTIONS: Photos: 0, ProvidedPois: 930
WOULD TOTAL SAVE ACTIONS: 1860.
```

## Staging, 2017, June 8
### Import
```shell
Success: Provided Poi with provided_poi_id 10012 saved!
Skipped: PHOTO 36176 already exists.
Skipped: osm_id blank and POI not found!
Skipped: POI for osm_id 843204466 not found.
Skipped: osm_id blank and POI not found!
Skipped: osm_id blank and POI not found!
Success: Provided Poi with provided_poi_id 10013 saved!
Skipped: PHOTO 36177 already exists.
Skipped: osm_id blank and POI not found!
Success: Provided Poi with provided_poi_id 10014 saved!
Skipped: PHOTO 36178 already exists.
Skipped: osm_id blank and POI not found!

EXISTING: ProvidedPois: 3214, Photos: 25819.
SKIPPED: Photos: 930, Provided Pois: 13724.
SAVE ACTIONS: Photos: 0, Provided Pois: 930
TOTAL SUCCESSFUL SAVE ACTIONS: 1860.
```

**Comment by holgerd** [comment]
@1000miles Sorry, we do not understand this report. What is the next action here?

**Comment by 1000miles** [comment]
@holgerd I am sorry for the confusion, that were stats from staging for the dry-run.

Assigning this ticket to @Svenyo in favor of final review for https://github.com/sozialhelden/wheelmap/issues/167#issuecomment-311564975.

**Comment by anngreenberg** [comment]
Import is done. Therefore closing.
