### ISSUE TITLE
wheelchair:description does not show up on wheelmap

### ISSUE THREAD

**Issue by anngreenberg** [sozialhelden/wheelmap#606]
As reported by @ldodds on issue #600  

> A user doing mapping using the app added a comment to a coffee shop. While the comments were saved to OSM, they are not appearing in the mobile or web versions of Wheelmap.
> 
> OSM: http://www.openstreetmap.org/way/452678133
> Wheelmap: https://wheelmap.org/en/nodes/-452678133
> 
> Let me know if I should file this as a separate report. Am a bit concerned that notes will get overwritten or lost if they're not displaying

From a quick check, this is also true for other nodes, as for example 
OSM: http://www.openstreetmap.org/way/462307362
Wheelmap: https://wheelmap.org/nodes/-462307362

When adding a comment, this should also be displayed on wheelmap directly.

**Comment by holgerd** [comment]
Just tested the following:

- I was logged in on wheelmap.org and edited the wheelchair:description of this place: https://wheelmap.org/en/nodes/1569218581 (from "Hat eine Rampe" to "has a ramp")
- I see the change on www.openstreetmap.org/node/1569218581 and expect to see it on wheelmap as well
- Instead, I stell see the old description on https://wheelmap.org/en/nodes/1569218581 5 minutes after editing it.

**Comment by holgerd** [comment]
It is okay now! https://wheelmap.org/en/nodes/1569218581

**Comment by holgerd** [comment]
Just tested again and it works:

- I used the iPhone app to add a comment to Cafe Sur in Berlin
- I open Cafe Sur in the web browser: https://wheelmap.org/nodes/623350251 and I see the comment (after ca 3 minutes)
- I open the detail page on the iPhone and do not see the comment. I tap on "edit comment" and there I see my comment in the textarea. This seems to be the only view of comments in the iphone app.

**Comment by holgerd** [comment]
Another test, this time with a node with negative ID:

- I used the iPhone to add the comment "test" to this church: https://wheelmap.org/nodes/-23453689
- This is the changeset: http://www.openstreetmap.org/changeset/49691034
- On iOS I can see the comment when I open the "edit comment" again
- **The comment does NOT show up** on https://wheelmap.org/nodes/-23453689 even 26min later

**Comment by holgerd** [comment]
Just tested:
The comment for https://wheelmap.org/nodes/-23453689 neither shows up on the detail page of the Android app.

**Comment by 1000miles** [comment]
### Update, 2017-07-18

For now we identified 3 behaviors:

#### Behavior one: comment does not appear at all on wheelmap.org

- a) Add comment on a wheelmap poi and submit => does not appear on wheelmap.org
- b) Same comment appears on openstreetmap.org after a few minutes
- c) Edit same comment on openstreetmap.org => does not appear on wheelmap.org
- d) Reload poi on wheelmap => does not appear on wheelmap.org

**Example nodes:**

- https://wheelmap.org/en/nodes/-462307362
- https://wheelmap.org/en/nodes/-452678133/
- https://wheelmap.org/en/nodes/-23453689/

```shell
+-----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| osm_id    | tags                                                                                                                                                                                                                                     | created_at          | updated_at          |
+-----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| -23453689 | ---
amenity: place_of_worship
wheelchair: 'yes'
religion: christian
building: 'yes'
wikidata: Q619821
denomination: protestant
wikipedia: de:Apostel-Paulus-Kirche (Berlin-Sch�neberg)
name: Apostel-Paulus-Kirche
building:levels: '4'
 | 2013-10-03 21:07:39 | 2017-07-18 08:25:26 |
+-----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
1 row in set (0.00 sec)

```

#### Behavior two: comment appears on wheelmap.org on 'edit' click

- a) Add comment on a wheelmap poi and submit => does not appear on wheelmap.org
- b) Same comment appears on openstreetmap.org after a few minutes
- c) Edit same comment on openstreetmap.org => does not appear on wheelmap.org
- d) Click on "Edit" to edit the poi on wheelmap.org => comment appears on the edit page of wheelmap.org without doing anything further
- e) save comment on edit page of wheelmap.org => appears on wheelmap poi

**Example nodes**

- https://wheelmap.org/nodes/1569218581

```shell
+------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| osm_id     | tags                                                                                                                                                                                                                                                                                                                                                                            | created_at          | updated_at          |
+------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| 1569218581 | ---
addr:city: Berlin
addr:country: DE
addr:housenumber: '31'
addr:postcode: '12047'
addr:street: Friedelstra�e
addr:suburb: Neuk�lln
amenity: restaurant
contact:phone: "+49 30 53 05 12 05"
contact:website: http://chez-dang.com/
cuisine: asian
name: Chez Dang
toilets:wheelchair: 'no'
wheelchair: limited
wheelchair:description: 'Ask for ramp ---- TEST #3 17.7.2017'
 | 2013-08-07 06:54:02 | 2017-07-17 13:48:08 |
+------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
1 row in set (0.00 sec)

```

#### Behavior three: comment appears on wheelmap.org after a few times reload

- a) Add comment on a wheelmap poi and submit => does not appear on wheelmap.org
- b) Same comment appears on openstreetmap.org after a few minutes
- c) Edit same comment on openstreetmap.org => does not on wheelmap.org
- d) Reload poi on wheelmap.org => does not on wheelmap.org
- d) Reload poi a few times on wheelmap.org => comment appears on wheelmap.org now


#### Conclusion: 
The syncing from wheelmap.org to openstreetmap.org works fine (comment appears shortly on openstreetmap) while syncing from openstreetmap.org to wheelmap.org does not work all the time. Sometimes it needs a click on "edit wheelmap poi" before the comment appears, sometimes it does not appear at all even after many times of reloading. 

We need to take a deeper look into what triggers to fetch data from openstreetmap to wheelmap. It could be that we have 2 or more bugs in this ticket.

**Comment by 1000miles** [comment]
## Update, 2017-07-25

### Observations so far:

1. When we click on the 'submit' button to update a poi the updated data is sent immediately to openstreetmap which explains why osm always has the newest updated data available quickly.

**openstreetmap api call example**

```shell
curl -v https://api.openstreetmap.org/api/0.6/way/452678133
```
**openstreetmap api response example**

```shell
*   Trying 193.63.75.100...
* Connected to api.openstreetmap.org (193.63.75.100) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: www.openstreetmap.org
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /api/0.6/way/452678133 HTTP/1.1
> Host: api.openstreetmap.org
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 25 Jul 2017 11:35:53 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Content-Encoding: identity
< Cache-Control: private, max-age=0, must-revalidate
< Vary: Accept-Encoding
< Content-Type: text/xml; charset=utf-8
< Transfer-Encoding: chunked
<
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="CGImap 0.6.0 (24935 thorn-03.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
 <way id="452678133" visible="true" version="9" changeset="50350214" timestamp="2017-07-17T13:03:06Z" user="johnnnny" uid="3399518">
  <nd ref="4494317089"/>
  <nd ref="4494317093"/>
  <nd ref="4494309561"/>
  <nd ref="4494308223"/>
  <nd ref="1752501953"/>
  <nd ref="4494317089"/>
  <tag k="amenity" v="cafe"/>
  <tag k="building" v="shop"/>
  <tag k="fhrs:id" v="738675"/>
  <tag k="name" v="Mus Coffee House"/>
  <tag k="toilets:wheelchair" v="no"/>
  <tag k="wheelchair" v="limited"/>
  <tag k="wheelchair:description" v="TEST 3 back =&gt; 2017-07-17 15:01:23 +0200"/>
 </way>
</osm>
* Connection #0 to host api.openstreetmap.org left intact
```

2. When clicking on the submit button of a poi to update the poi data, these infos are not saved immediately in the wheelmap app but dependent on the [UpdateTagsJob](https://github.com/sozialhelden/wheelmap/blob/master/app/jobs/update_tags_job.rb) to work in order to save the data in the wheelmap app. 

We now need to write tests to find out when and why the data gets lost during the `UpdateTagsJob` process.

**Comment by 1000miles** [comment]
@holgerd cc @anngreenberg @Hoverbear 

### Update, 2017-08-04

- we added `wheelchair:description` tag to the method [`update_poi!`](https://github.com/sozialhelden/wheelmap/blob/master/app/jobs/update_tags_job.rb#L127) and simulated under limited conditions the syncing between osm and wheelmap via a test case
- the fix for the **behavior one** mentioned in this ticket seems to be valid for all POIs that are going to be edited **from now** on 
- **important**: since we do not have a fully functional osm test environment to debug/test the syncing between osm and wheelmap we still can not give proper response under which specific conditions some POIs were/are affected.

Current state:
- At the moment a comment field is being shown on a wheelmap POI even though it is empty => we will create a follow-up ticket for this
