### ISSUE TITLE
Open embed's links in _top

### ISSUE THREAD

**Issue by theel0ja** [sozialhelden/wheelmap#610]
If [https://wheelmap.org/en/profile/widgets](https://wheelmap.org/en/profile/widgets)'s "Maps Icons Collection" link is clicked, it don't open it in _top.

**Comment by Hoverbear** [comment]
@theel0ja Hi! Thanks for this report! Could you be a bit more specific about where this link is? I don't see it.

<img width="644" alt="screen shot 2017-05-18 at 10 10 50" src="https://cloud.githubusercontent.com/assets/130903/26192521/54ed76d4-3bb2-11e7-812d-bef0d8447cee.png">

**Comment by theel0ja** [comment]
On that copyright notice on the bottom of the map window.

**Comment by Hoverbear** [comment]
Ahhhhh I see! Thanks!

**Comment by 1000miles** [comment]
For documentation:

After login via osm go to your profile page on wheelmap and click on `widget` which leads you to `https://wheelmap.org/profile/widgets`.
