### ISSUE TITLE
Text align in toolbar dropdowns

### ISSUE THREAD

**Issue by lennerd** [sozialhelden/wheelmap#62]
The text inside the toolbar dropdown is not align correctly. Should be simple to fix:

<img width="355" alt="screenshot 2015-11-23 10 09 40" src="https://cloud.githubusercontent.com/assets/1609692/11332961/6fdee25e-91ca-11e5-96cf-311873c41584.png">

**Comment by 1000miles** [comment]
@lennerd this issue seems to be fixed by this commit, right?
https://github.com/sozialhelden/wheelmap/commit/351b26a7fd068749743212978c12e7c0831cf4fa

**Comment by lennerd** [comment]
It was a different commit, but this is fixed now, right.

**Comment by 1000miles** [comment]
Sorry, copied the wrong commit, I meant this one: https://github.com/sozialhelden/wheelmap/commit/0046437f07ba6b080b06b1a502f49f28d73f68f3.

Thanks for closing.

**Comment by lennerd** [comment]
No problem. :wink:
