### ISSUE TITLE
"Finalize account" screen

### ISSUE THREAD

**Issue by lennerd** [sozialhelden/wheelmap#63]
The current screen for finalizing the account after loggin needs some work to fit to the layout we use.

![screenshot 2015-11-23 10 19 57](https://cloud.githubusercontent.com/assets/1609692/11333156/e2f81ba6-91cb-11e5-85f6-25854a700408.png)

**Comment by lennerd** [comment]
So we did a quick fix to make it less ugly, but it's still no beauty.

![screenshot 2015-11-23 17 11 55](https://cloud.githubusercontent.com/assets/1609692/11342026/80559688-9205-11e5-8737-4601c1ab501a.png)

**Comment by holgerd** [comment]
LAyout is nice, but German version lacks translation.

**Comment by lennerd** [comment]
@Xylakant @skade I double checked the I18n translation configuration. We have a fallback option set to `true` and the default locale is `de`. Any ideas why Rails does not pick the correct translations here but instead uses the last part of the translation key?

**Comment by holgerd** [comment]
@1000miles this is done and obsolete now afaik?

**Comment by Hoverbear** [comment]
I believe it is done.

**Comment by 1000miles** [comment]
Yes, I can confirm it's done. Let's close this ticket.
