### ISSUE TITLE
[CSV Import] 'ArgumentError: argument out of range' on date_time

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#633]
This is a follow-up ticket for https://github.com/sozialhelden/wheelmap/issues/630#issuecomment-311650076.

### Background:
At the moment we can not fully loop through the files `DE_2016.csv`, `IR_2016.csv` and `UK_2016.csv` to import the photo images from streetspotr.

Following are the conditions to debug in dev:
- the osm_id in the csv must match with the osm_id of the existing poi in the dev environment (local)
- the poi/record must raise the exception `(ArgumentError): argument out of range`

In order to analyze what is wrong with the date time on a specific record we need to be able to compare the EXIF data of an image - that requires to strip and display the exif data of respective image before hand.

Needs more investigation.

**Maybe related:**
- https://stackoverflow.com/questions/9131697/rails-active-record-argumenterror-argument-out-of-range-for-time-fields-g
- https://stackoverflow.com/questions/4076248/mysql-time-type-gives-an-argumenterror-argument-out-of-range-in-rails-if-ov
- https://stackoverflow.com/questions/27115441/random-intermittent-argument-out-of-range-error-while-parsing-csv-and-parsing

**Comment by 1000miles** [comment]
**Update, 2017 July 5:**

We finally found out why some images cause an `(ArgumentError): argument out of range` error related to datetime. 

Following 3 images are examples for comparison:
- https://download.streetspotr.com/0da9ec28c99f1c1a598da20fac6432c6dd8cf08e/a9cf07fa864fb2d6ee2d01fe5d6665d80f147e82 (working)
- https://download.streetspotr.com/81e38f251e3a6bde77ce7b027256ec27276429ca/a6d74cb779fc4e12b14ab0152c46fb9e14ebf176 (working)
- https://download.streetspotr.com/05d67819ca0c286c542e88c322a58a4a9115b2d4/1b6fb57f65ae00c36e6933ab2b23c412b79c45bd ((ArgumentError): argument out of range)

```shell

# working
>> EXIFR::JPEG.new('photo_2517845_original.jpg').date_time
=> 2017-05-08 12:07:45 +0200
>> EXIFR::JPEG.new('photo_2075939_original.jpg').date_time
=> 2017-01-21 12:28:43 +0100

# not working
>> EXIFR::JPEG.new('photo_2457067_original.jpg').date_time
=> "2017:04:24 5:37:02 PM"
```

**Comment by anngreenberg** [comment]
@holgerd @Svenyo 
As previously explained, the issue lies in the various date formats used in ‘taken at’.
 
There are 3 possible ways to solve this issue:
1. set all ‘taken at’-dates to nil
2. set all ‘taken at’-dates to the ‘created at’-dates
3. continue research and code a script to identify all possible date formats and one that changes all to the same date format.

How important is the ‘taken at’ date? Do option 1 or 2 seem reasonable for you so we can finish the update?

**Comment by holgerd** [comment]
@anngreenberg I'm okay not having the correct "taken at" for this import. Let's go with option 1 or 2 (no preference from my side).

@Svenyo We should give Streetspotr feedback that date formats are inconsistent in EXIF info of the provided photos, maybe the'll have a solution next time.

**Comment by Svenyo** [comment]
@holgerd @anngreenberg Ok.

**Comment by 1000miles** [comment]
Fixed in https://github.com/sozialhelden/wheelmap/pull/635. Closing this ticket.
