### ISSUE TITLE
Wrong/ old data shown on Wheelmap.org

### ISSUE THREAD

**Issue by Svenyo** [sozialhelden/wheelmap#637]
For these POIs the current OSM data is different from what is shown on Wheelmap:

- Knusperlädle: https://wheelmap.org/nodes/-169000335 (name in OSM different)
- Schubkarrenspiel: https://wheelmap.org/nodes/-99495490 (POI in OSM deleted)
- Kiosk: https://wheelmap.org/nodes/-169010702 (name in OSM different).

**Comment by ldodds** [comment]
I have a related problem in Bath. OSM locations have been deleted, but these points are still in Wheelmap:

* Clintons, https://wheelmap.org/nodes/-380826074
* Fabulous, https://wheelmap.org/nodes/-97235865

It would be useful to have a way to flag a node for deletion

**Comment by ldodds** [comment]
The Raven, https://wheelmap.org/nodes/-120543180

We're unable to update this node on wheelmap, after saving a rating, the icon never changes. The node on OSM is marked as "no":

http://www.openstreetmap.org/way/197919643

**Comment by 1000miles** [comment]
Thank you for reporting this, @ldodds . 👍

**Comment by anngreenberg** [comment]
All places mentioned here have been checked and are solved as expected. Therefore closing.
