### ISSUE TITLE
Interactive Google Streetview on node detail page

### ISSUE THREAD

**Issue by lennerd** [sozialhelden/wheelmap#64]
It would be nice to have an interactive version of Google Streetview on the detailed page (https://developers.google.com/maps/documentation/javascript/examples/streetview-embed).

![screenshot 2015-11-23 15 20 52](https://cloud.githubusercontent.com/assets/1609692/11338693/e15de512-91f5-11e5-8411-c7282472ad0c.png)

There are also some bugs with the static image API from Google, for example:
http://wheelmap.org/nodes/3719783725

:laughing:

**Comment by holgerd** [comment]
maybe show mapiliary widget if streetview is not available. (suggested by @christoph-buente )

**Comment by holgerd** [comment]
@lennerd I see the interactive streetview, nice!

One question:
Christoph told me once that cardinal direction (Himmelsrichtung) is taken into account when he calculated the static streetview image. Can you do the same to the interactive streetview? I mean, that it "looks" into the right direction on load.

Example: restaurant eta hoffmann:

correct cardinal direction: http://wheelmap.org/nodes/838031222
wrong direction: http://staging.wheelmap.org/nodes/838031222

I found a few more like this so I guess it is random (or always the same direction) now?

**Comment by lennerd** [comment]
@christoph-buente I'm not able to see what you meant when telling @holgerd you use the cardinal direction. In the current Google Street View Image API, you simple put the Latitude and Longitude into the image URL. Can you help me out here?
