### ISSUE TITLE
wheelchair:description tag should be used

### ISSUE THREAD

**Issue by anngreenberg** [sozialhelden/wheelmap#645]
Follow up ticket to #606 

**Expected:** All descriptions saved on OSM should reflect in `wheelchair:description` tag

**Experienced:** 

- Descriptions on OSM are saved under `description` tag. 
example: [https://wheelmap.org/en/nodes/-132314330](https://wheelmap.org/en/nodes/-132314330)

<img width="1358" alt="bildschirmfoto 2017-08-04 um 14 07 38" src="https://user-images.githubusercontent.com/22611686/28968076-8c992192-791e-11e7-8815-f9f1f41d2999.png">

<img width="1003" alt="bildschirmfoto 2017-08-04 um 14 07 45" src="https://user-images.githubusercontent.com/22611686/28968074-8c8bd7b2-791e-11e7-9fe8-d601a3c9c64e.png">

- If a new wheelchair:description is added to wheelmap and saved, it saves to `wheelchair:description` and does not modify `description`. 
example: [https://wheelmap.org/en/nodes/-132314330](https://wheelmap.org/en/nodes/-132314330)
[http://www.openstreetmap.org/way/132314330](http://www.openstreetmap.org/way/132314330)

**Ways in db with description tag:**
`28.085`

**Needs clarification:** 
- If a wheelmap POI has a comment saved under the OSM tag `description`, should it also reflect in `wheelchair:description`?

**Comment by holgerd** [comment]
Wheelmap should only read and write the wheelchair:description field, since it is always info in accessibility of the place. If we write to the general description tag, then this is a mistake.

**Comment by anngreenberg** [comment]
@Holger Thank you. 
After checking a few more examples, the idea of missing descriptions being falsely saved to description could not be confirmed, as the info contained in description is not accessibility info. So the behavior is as expected. Therefore closing this ticket.
