### ISSUE TITLE
Unicorn production worker execution failed

### ISSUE THREAD

**Issue by thermann78** [sozialhelden/wheelmap#65]
The past weeks it occured several times that some of the production workers won't restart.
Currently Monit say:
unicorn_production_worker_7	Execution failed - and I'm unable to restart it via Monit.

In addition, the status of our filesystem says:

Filesystem	Status	Space usage	Inodes usage
md2	Resource limit matched	80.8% [788615.1 MB]	3.9% [2644230 objects]

**Comment by christoph-buente** [comment]
Check if start/stop command for unicorns in capistrano and monit are exactly the same.

This also should fix the deployment. Otherwise pause the monit upon capistrano deployment and resume after.

**Comment by Xylakant** [comment]
we're not using monit any more in the new infrastructure, so this is obsolete
