### ISSUE TITLE
List of active widget users

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#652]
Since we get some airbrake errors which may Be linked to wrongly embedded widgets:

Can you get a list of URLs where it is embedded (maybe in referer logs?). Can you then lookup the wheelmap user (email / OSM Id) for each?

Other ideas regarding this are welcome.

**Comment by Xylakant** [comment]
As far as I debugged this last time, the errors are triggered by a content management system that embeds the widget without a valid osm id/user.

**Comment by 1000miles** [comment]
@holgerd There is already a ticket [here](https://github.com/sozialhelden/wheelmap-privateissues/issues/43) where we listed platforms that still have the wheelmap widget implemented with empty api_key values in their source code.

-  http://www.forst-baden.de/site/forst-baden/node/950441/Lde/index.html
-  http://www.ettlingen.de/,Lde/startseite/Wirtschaft+_+Verkehr/stadtplan.html
-  http://www.freiburg.de/pb/,Lde/879920.html
-  ~http://hambruecken.kivbf.de/,Lde/226954.html~ (this website does not exist anymore)

We checked them again and all of them still have this corresponding part:
```
            K.settings.wheelmap = {
            active: true,
            key: ''
        };
```

There maybe more platforms that also use this kind of script. Need further checks.

**Comment by 1000miles** [comment]
Example (line 347-388): 
'view-source:http://www.forst-baden.de/site/forst-baden/node/950441/Lde/index.html'

Full script:
```javascript
<script>
    var toggleMapnav = function() {
        jQuery('#mapnav').toggle('slide', {direction: 'left'}, 500, function() {
            var mapnavShow = jQuery('#mapnav_show');
            jQuery(this).is(':visible') ? mapnavShow.addClass('open') : mapnavShow.removeClass('open');
        });
    };
    jQuery('#mapnav_show').click(toggleMapnav);
    jQuery('#mapnav').hide();
    jQuery('#cmsmap .cmsmap_close').click(toggleMapnav);
    K.settings.application = {
        startLat: 49.15337,
        startLong: 8.586950000000002,
        searchStringAddition: ' , Forst Baden',
        debug: false,
        htmlid: 'map_950453',
        elementid: '950453',
        zoomlevel: 15,
        baseImageUrl: '/site/forst-baden/resourceCached/9.2.1/'
    };
            K.settings.wheelmap = {
            active: true,
            key: ''
        };
                K.settings.servicebw = {
            active: true,
            baseUrl: '/site/forst-baden/map/950441/Lde/kontakt.html'
        };
                K.settings.zusatzmodule = [
                                {
                active: true,
                url: '/site/forst-baden/zmservice/3451/Lde/geo/data.json',
                name: 'Firmen in Forst'
            },
                                            {
                active: true,
                url: '/site/forst-baden/zmservice/3750/Lde/geo/data.json',
                name: 'Vereine in Forst'
            },
                                                                                        ]
                K.start();
</script>
```

**Comment by 1000miles** [comment]
Referencing our last recent log comment [here](https://github.com/sozialhelden/wheelmap-privateissues/issues/43#issuecomment-328789750).

**Comment by holgerd** [comment]
great thanks. So I close this as duplicate to https://github.com/sozialhelden/wheelmap-privateissues/issues/43
