### ISSUE TITLE
Searching for a new POI display a blank map

### ISSUE THREAD

**Issue by pyrog** [sozialhelden/wheelmap#666]
Searching for a POI newly added to OSM and not yet in Wheelmap display an empty map.

Search for "[Le Haut de Versac](https://wheelmap.org/search?q=le+haut+de+versac)" and click to the [link to this object](https://wheelmap.org/fr/map#/popup/5308899054?bbox=46.394762%252C46.394862%252C5.7968337%252C5.7969337&q=le+haut+de+versac).

The javascript console display:
   `[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (5308899054.json, line 0)`

This object is the [OSM node 5308899054](https://www.openstreetmap.org/node/5308899054).

Screen copy of the map:
![blank map](https://user-images.githubusercontent.com/2158081/34438449-4edd04de-eca7-11e7-9c20-a999e052214e.png)

**Comment by 1000miles** [comment]
@pyrog Thank you for reporting this. 

The replication from OSM to wheelmap is fixed and works again since yesterday. The reported POI is to be found here: https://wheelmap.org/nodes/5308899054

**Comment by 1000miles** [comment]
Since this POI appears now, I am going to close this.
