### ISSUE TITLE
Neu hinzugefügte Orte erscheinen in der OSM, aber nicht in der Wheelmap

### ISSUE THREAD

**Issue by Svenyo** [sozialhelden/wheelmap#667]
Bei einem Mapping-Event in Leer wurden neue Orte hinzugefügt. Diese werden jedoch noch immer nicht in der Wheelmap angezeigt. in der OSM sind sie vorhanden (siehe auch Issue #600) 

Die Suche der Wheelmap zeigt jeweils einen Eintrag, aber bei Klick auf den Sucheintrag kommt teilweise eine leere Seite (siehe auch Issue #666) oder man wird in die Karte geleitet, aber dort ist kein Marker an entsprechender Stelle:

Beispiele: 
Da Paolo – https://www.openstreetmap.org/node/5363376421 (siehe auch Screenshots)

![screen shot 2018-01-29 at 17 20 07](https://user-images.githubusercontent.com/20318534/35521020-f03d70fa-0518-11e8-9000-28b652f6ccda.png)
![screen shot 2018-01-29 at 17 20 18](https://user-images.githubusercontent.com/20318534/35521022-f0d27e98-0518-11e8-824f-77cc53f57215.png)

Die Tafel – https://www.openstreetmap.org/node/5363379521

Gesundheitsamt Leer – https://www.openstreetmap.org/node/5363347222

Aktueller Test von heute: https://www.openstreetmap.org/node/5370651426

**Comment by 1000miles** [comment]
Replicated? #667 - https://github.com/sozialhelden/wheelmap/issues/667
https://wheelmap.org/nodes/5363376421 => Yes
https://wheelmap.org/nodes/5363379521 => Yes
https://wheelmap.org/nodes/5363347222 => Yes
https://wheelmap.org/nodes/5370651426 => No. Deleted by osm.
