### ISSUE TITLE
Edits in OSM not updated on Wheelmap - Sync problems

### ISSUE THREAD

**Issue by Svenyo** [sozialhelden/wheelmap#670]
1. POI has been deleted in OSM, still visible in Wheelmap 
https://wheelmap.org/nodes/-99495490 ; compare: https://www.openstreetmap.org/way/99495490

2. Amenity/ Node type was changed in OSM from kiosk to fast food, but still in Wheelmap as Kiosk:
https://wheelmap.org/nodes/-169000335 ; compare:
https://www.openstreetmap.org/way/169000335

3. Name was added in OSM, but still no name visible on Wheelmap:
https://wheelmap.org/nodes/-169010708 ; compare:
https://www.openstreetmap.org/way/169010708

**Comment by spacekookie** [comment]
These issues seem to have resolved themselves with recent syncs. Closing the issue for now cc/@anngreenberg
