### ISSUE TITLE
ice cream places added using wheelmap, but does not show up

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#677]
User nanonan added Eismanufaktur using Wheelmap and the POI shows up in OSM:
https://www.openstreetmap.org/node/5635559521

It does not show up on Wheelmap:
https://wheelmap.org/map#/?lat=52.495104621100594&lon=13.419467210769653&zoom=19

Is the sync maybe not working?

**Comment by holgerd** [comment]
Any news on this? @spacekookie @thuy @anngreenberg

**Comment by anngreenberg** [comment]
Not currently. We've been focussing on the deployment issues that came up.

**Comment by spacekookie** [comment]
The wheelmap sync has been working again for a few days now, working through the backlog and it looks like the places you've linked are now also showing up in wheelmap.
