### ISSUE TITLE
No route matches '/api/nodes/-371887089/update_toilet'

### ISSUE THREAD

**Issue by IsmaelNascimento** [sozialhelden/wheelmap#684]
Api not work

![image](https://user-images.githubusercontent.com/19227867/40880760-0f2bf3c6-668d-11e8-87a8-536ecaea0e94.png)

**Comment by holgerd** [comment]
Thanks for letting us know. @spacekookie can you please look into this and try to reproduce it?

**Comment by holgerd** [comment]
closing this.

@spacekookie places with negative ID have been converted by us (from way to node).
