### ISSUE TITLE
New Layout for "add node"

### ISSUE THREAD

**Issue by lennerd** [sozialhelden/wheelmap#70]
#105

**Comment by holgerd** [comment]
- ähnliche orte nicht weltweit suchen Sondern wie in poichecker (gleiche Kategorie, in der Nähe, siehe Code ;))
- in Safari mobil sehe Ichbewusstsein "Speichern" keinen Fortschritt oder es geht nicht 
- Typ Dropdown-Menü hat leere Zeilen zB nach Optiket

**Comment by lennerd** [comment]
Thanks for the feedback. I will keep working on this today and tomorrow.

**Comment by lennerd** [comment]
Please check again the new version on staging. The main changes are updated english translations to be imported into Transifex.

> ähnliche orte nicht weltweit suchen Sondern wie in poichecker (gleiche Kategorie, in der Nähe, siehe Code ;))

This should be fixed in the next version.

> Typ Dropdown-Menü hat leere Zeilen zB nach Optiket

This is because of a failed node type we did once. This should not be a problem on production.

> in Safari mobil sehe Ichbewusstsein "Speichern" keinen Fortschritt oder es geht nicht

This is fixed.

**Comment by lennerd** [comment]
@holgerd The fix for searching only in a small area around the defined address and for comparing photon results with the data of our database to show only available places is now on staging. What do you think?

**Comment by holgerd** [comment]
after searching for the name "cafe" in category "Café" and location was Berlin I see suggested places in Saudi-Arabia, London and Berlin. See screenshot:
![img_5794](https://cloud.githubusercontent.com/assets/218506/14248283/052d3b50-fa74-11e5-80e3-dd342cbc53c7.PNG)

**Comment by holgerd** [comment]
ok, now only Kranzler is left. :)

**Comment by holgerd** [comment]
@lennerd "searching only in a small area around the defined address" may be too small since we do not know the user's intention. 

I suggest:
1. a larger area like ca. 100km2 or so
2. Make this explicit in the headline: "We found these places within 100km. Is it one of those?"

**Comment by holgerd** [comment]
- [ ] small design glitch on confirmation page: the map is too far to the left, see screenshot
- [ ] rename "Weiter" button on "Ähnliche Orte" to "None of the above"
![img_5792](https://cloud.githubusercontent.com/assets/218506/14248461/11055646-fa75-11e5-9a5f-7c5087c5d596.PNG)

**Comment by lennerd** [comment]
The area is defined as 200 km radius from the address from the previous address section. Good point with the headline. Will fix it.

Remember that staging is based on a quite old OSM dataset, therefore the result will differ when seen on production.
