### ISSUE TITLE
Mysql2::Error: Table 'wheelmap_development.providers' doesn't exist 

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#71]
### CASE:

This Myslq2 error happend a few times when trying to run rake commands. Even though the table for 'providers' is already created in the initial_schema, something in the migrations processes seems to always empty the database tables. I tried to drop, create & migrate a couple of times but yet the databases tables were empty (see step 2 below). To fix this, we have used a manual solution (see step 4) and for now it seems to work again. However, we wanted to document it in case this happens again. Maybe anyone can have a deeper look into this? 

### STEP 1:
rake db:migrate

## ERROR OUTPUT:
rake aborted!
*Mysql2::Error: Table 'wheelmap_development.providers' doesn't exist*
/Users/wheelmap/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `query'
/Users/wheelmap/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `execute'
/Users/wheelmap/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/mysql2_adapter.rb:213:in `execute'
/Users/wheelmap/vendor/bundle/ruby/2.2.0/gems/activerecord-mysql2spatial-adapter-0.4.3/lib/active_record/connection_adapters/mysql2spatial_adapter/main_adapter.rb:114:in `columns'
/Users/wheelmap/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
/Users//wheelmap/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/model_schema.rb:229:in `yield'
/Users/wheelmap/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/model_schema.rb:229:in `[]'
/Users//wheelmap/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/model_schema.rb:229:in `columns'
/Users//wheelmap/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/model_schema.rb:238:in `columns_hash'
/Users//wheelmap/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/locking/optimistic.rb:131:in `locking_enabled?'

------

bundle exec rake db:drop
bundle exec rake:create

### STEP 2: CHECK MYSQL DATABASES FOR TABLES:

mysql -u root 
mysql> show databases;
+----------------------+
| Database |
+----------------------+
| information_schema |
| mysql |
| performance_schema |
| sys |
| wheelmap_development |
| wheelmap_test |
+----------------------+
6 rows in set (0.00 sec)

mysql> use wheelmap_development;
Database changed
mysql> show tables;
Empty set (0.00 sec)

------

Empty Tables in Database ("wheelmap_test"):

mysql> show databases;
+----------------------+
| Database |
+----------------------+
| information_schema |
| mysql |
| performance_schema |
| sys |
| wheelmap_development |
| wheelmap_test |
+----------------------+
6 rows in set (0.00 sec)

mysql> use wheelmap_test;
Database changed
mysql> show tables;
Empty set (0.00 sec)

------

### STEP 4: ADD DB STRUCTURE MANUALLY TO THE DATABASE (had to execute this solution twice):

* bundle exec rake db:migrate:reset
* mysql -u root
* mysql -u root -p wheelmap_development < ./db/structure.sql
* bundle exec rake db:migrate
* bzcat berlin-latest.osm.bz2 | bundle exec rake osm:import
* bundle exec rails s

------

### STEP 5: SERVER STARTED but several files 304 Not Modified 

bundle exec rails s 
=> Booting WEBrick
=> Rails 3.2.22 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2015-12-01 16:39:18] INFO WEBrick 1.3.1
[2015-12-01 16:39:18] INFO ruby 2.2.2 (2015-04-13) [x86_64-darwin14]
[2015-12-01 16:39:18] INFO WEBrick::HTTPServer#start: pid=16953 port=3000
[librato-rails] config: {:user=>"email@xxx.de", :token=>"a_funny_token", :log_level=>"debug", :source=>nil, :prefix=>"development", :flush_interval=>60, :source_pids=>false}
[librato-rails] >> starting up worker for pid 16953...

Started GET "/map" for 127.0.0.1 at 2015-12-01 16:41:23 +0100
Processing by HomeController#index as HTML
Rendered home/_overlay.html.haml (1544.6ms)
Rendered home/index.html.haml within layouts/relaunch (2436.5ms)
Rendered relaunch/_meta.html.haml (59.3ms)
Rendered relaunch/_header.html.haml (29.4ms)
(0.2ms) SELECT COUNT() FROM pois WHERE pois.status = 1
(0.2ms) SELECT COUNT() FROM pois WHERE pois.status = 2
(0.2ms) SELECT COUNT() FROM pois WHERE pois.status = 4
(0.4ms) SELECT COUNT() FROM pois WHERE (status < 8)
Rendered relaunch/_footer.html.haml (32.7ms)
Rendered shared/_google_tracking.html.haml (2.9ms)
Completed 200 OK in 2833.3ms (Views: 2829.0ms | ActiveRecord: 1.5ms)

Started GET "/assets/relaunch.css?body=1" for 127.0.0.1 at 2015-12-01 16:41:26 +0100
Served asset /relaunch.css - 304 Not Modified (263ms)

Started GET "/assets/env.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /env.js - 304 Not Modified (5ms)

Started GET "/assets/jquery/jquery-migrate.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /jquery/jquery-migrate.js - 304 Not Modified (3ms)

Started GET "/assets/jquery.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /jquery.js - 304 Not Modified (18ms)

Started GET "/assets/jquery/jquery.cookies.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /jquery/jquery.cookies.js - 304 Not Modified (3ms)

Started GET "/assets/i18n.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /i18n.js - 304 Not Modified (21ms)

Started GET "/assets/bootstrap-affix.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-affix.js - 304 Not Modified (6ms)

Started GET "/assets/bootstrap-transition.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-transition.js - 304 Not Modified (7ms)

Started GET "/assets/bootstrap-alert.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-alert.js - 304 Not Modified (7ms)

Started GET "/assets/bootstrap-carousel.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-carousel.js - 304 Not Modified (7ms)

Started GET "/assets/bootstrap-button.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-button.js - 304 Not Modified (6ms)

Started GET "/assets/bootstrap-collapse.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-collapse.js - 304 Not Modified (6ms)

Started GET "/assets/bootstrap-dropdown.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-dropdown.js - 304 Not Modified (8ms)

Started GET "/assets/bootstrap-scrollspy.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-scrollspy.js - 304 Not Modified (88ms)

Started GET "/assets/bootstrap-modal.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-modal.js - 304 Not Modified (5ms)

Started GET "/assets/bootstrap-tab.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-tab.js - 304 Not Modified (5ms)

Started GET "/assets/bootstrap-tooltip.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-tooltip.js - 304 Not Modified (5ms)

Started GET "/assets/bootstrap-popover.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-popover.js - 304 Not Modified (5ms)

Started GET "/assets/bootstrap-typeahead.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:27 +0100
Served asset /bootstrap-typeahead.js - 304 Not Modified (6ms)

Started GET "/assets/bootstrap.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /bootstrap.js - 304 Not Modified (28ms)

Started GET "/assets/bootstrap-select.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /bootstrap-select.js - 304 Not Modified (4ms)

Started GET "/assets/custom-bootstrap.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /custom-bootstrap.js - 304 Not Modified (5ms)

Started GET "/assets/map-overlay.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /map-overlay.js - 304 Not Modified (4ms)

Started GET "/assets/function.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /function.js - 304 Not Modified (6ms)

Started GET "/assets/handlebars.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /handlebars.js - 304 Not Modified (8ms)

Started GET "/assets/ember-data.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /ember-data.js - 304 Not Modified (7ms)

Started GET "/assets/spin.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /spin.js - 304 Not Modified (4ms)

Started GET "/assets/leaflet/leaflet-src.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /leaflet/leaflet-src.js - 304 Not Modified (4ms)

Started GET "/assets/ember.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /ember.js - 304 Not Modified (5ms)

Started GET "/assets/leaflet/leaflet.locate.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /leaflet/leaflet.locate.js - 304 Not Modified (3ms)

Started GET "/assets/ember-leaflet.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /ember-leaflet.js - 304 Not Modified (4ms)

Started GET "/assets/jquery/jquery.magnific-popup.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /jquery/jquery.magnific-popup.js - 304 Not Modified (3ms)

Started GET "/assets/responsive-popover.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /responsive-popover.js - 304 Not Modified (4ms)

Started GET "/assets/dropzone.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /dropzone.js - 304 Not Modified (5ms)

Started GET "/assets/app.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:28 +0100
Served asset /app.js - 304 Not Modified (335ms)

Started GET "/assets/models/category.model.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /models/category.model.js - 304 Not Modified (2ms)

Started GET "/assets/store.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /store.js - 304 Not Modified (7ms)

Started GET "/assets/models/node.model.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /models/node.model.js - 304 Not Modified (2ms)

Started GET "/assets/models/node-type.model.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /models/node-type.model.js - 304 Not Modified (2ms)

Started GET "/assets/models/photo.mode.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /models/photo.mode.js - 304 Not Modified (11ms)

Started GET "/assets/controllers/map.controller.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /controllers/map.controller.js - 304 Not Modified (3ms)

Started GET "/assets/controllers/index.controller.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /controllers/index.controller.js - 304 Not Modified (4ms)

Started GET "/assets/controllers/flash-messages.controller.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /controllers/flash-messages.controller.js - 304 Not Modified (2ms)

Started GET "/assets/controllers/nodes.controller.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /controllers/nodes.controller.js - 304 Not Modified (3ms)

Started GET "/assets/controllers/popup.controller.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /controllers/popup.controller.js - 304 Not Modified (11ms)

Started GET "/assets/controllers/category.controller.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /controllers/category.controller.js - 304 Not Modified (3ms)

Started GET "/assets/controllers/toolbar.controller.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /controllers/toolbar.controller.js - 304 Not Modified (2ms)

Started GET "/assets/views/components/form.component.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /views/components/form.component.js - 304 Not Modified (2ms)

Started GET "/assets/views/components/custom-select.component.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /views/components/custom-select.component.js - 304 Not Modified (2ms)

Started GET "/assets/views/components/node-share.component.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /views/components/node-share.component.js - 304 Not Modified (3ms)

Started GET "/assets/views/components/popover.component.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /views/components/popover.component.js - 304 Not Modified (3ms)

Started GET "/assets/views/components/status-filter-button.component.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /views/components/status-filter-button.component.js - 304 Not Modified (2ms)

Started GET "/assets/views/components/wheelchair-checkbox.component.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /views/components/wheelchair-checkbox.component.js - 304 Not Modified (7ms)

Started GET "/assets/views/fake-map.view.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /views/fake-map.view.js - 304 Not Modified (2ms)

Started GET "/assets/views/flash-messages.view.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:29 +0100
Served asset /views/flash-messages.view.js - 304 Not Modified (7ms)

Started GET "/assets/views/map.view.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /views/map.view.js - 304 Not Modified (2ms)

Started GET "/assets/views/node-dropzone.view.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /views/node-dropzone.view.js - 304 Not Modified (5ms)

Started GET "/assets/views/node-popup.view.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /views/node-popup.view.js - 304 Not Modified (3ms)

Started GET "/assets/views/nodes/edit.view.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /views/nodes/edit.view.js - 304 Not Modified (3ms)

Started GET "/assets/views/searchbar.view.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /views/searchbar.view.js - 304 Not Modified (2ms)

Started GET "/assets/views/toolbar.view.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /views/toolbar.view.js - 304 Not Modified (3ms)

Started GET "/assets/helpers/i18n_helper.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /helpers/i18n_helper.js - 304 Not Modified (3ms)

Started GET "/assets/templates/components/control-error.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/components/control-error.js - 304 Not Modified (2ms)

Started GET "/assets/templates/application.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/application.js - 304 Not Modified (4ms)

Started GET "/assets/templates/components/custom-select.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/components/custom-select.js - 304 Not Modified (7ms)

Started GET "/assets/templates/components/control-group.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/components/control-group.js - 304 Not Modified (3ms)

Started GET "/assets/templates/components/email-share.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/components/email-share.js - 304 Not Modified (3ms)

Started GET "/assets/templates/components/facebook-share.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/components/facebook-share.js - 304 Not Modified (2ms)

Started GET "/assets/templates/components/toolbar-filter-button.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/components/toolbar-filter-button.js - 304 Not Modified (3ms)

Started GET "/assets/templates/components/status-filter-button.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/components/status-filter-button.js - 304 Not Modified (4ms)

Started GET "/assets/templates/components/wheelchair-checkbox.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/components/wheelchair-checkbox.js - 304 Not Modified (2ms)

Started GET "/assets/templates/components/twitter-share.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/components/twitter-share.js - 304 Not Modified (30ms)

Started GET "/assets/templates/index.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/index.js - 304 Not Modified (3ms)

Started GET "/assets/templates/map.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:30 +0100
Served asset /templates/map.js - 304 Not Modified (6ms)

Started GET "/assets/templates/node-popup/_edit.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /templates/node-popup/_edit.js - 304 Not Modified (4ms)

Started GET "/assets/templates/node-popup.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /templates/node-popup.js - 304 Not Modified (2ms)

Started GET "/assets/templates/node-popup/_header.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /templates/node-popup/_header.js - 304 Not Modified (2ms)

Started GET "/assets/templates/node-popup/_share.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /templates/node-popup/_share.js - 304 Not Modified (3ms)

Started GET "/assets/templates/node-popup/_report.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /templates/node-popup/_report.js - 304 Not Modified (3ms)

Started GET "/assets/templates/nodes/_status-dropdown.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /templates/nodes/_status-dropdown.js - 304 Not Modified (3ms)

Started GET "/assets/templates/nodes/_status-toilet-dropdown.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /templates/nodes/_status-toilet-dropdown.js - 304 Not Modified (3ms)

Started GET "/assets/templates/toolbar.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /templates/toolbar.js - 304 Not Modified (2ms)

Started GET "/assets/routes/application.route.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /routes/application.route.js - 304 Not Modified (3ms)

Started GET "/assets/routes/error.route.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /routes/error.route.js - 304 Not Modified (2ms)

Started GET "/assets/routes/fake-map.route.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /routes/fake-map.route.js - 304 Not Modified (3ms)

Started GET "/assets/routes/map.route.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /routes/map.route.js - 304 Not Modified (3ms)

Started GET "/assets/routes/index.route.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /routes/index.route.js - 304 Not Modified (4ms)

Started GET "/assets/routes/popup.route.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /routes/popup.route.js - 304 Not Modified (5ms)

Started GET "/assets/router.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /router.js - 304 Not Modified (5ms)

Started GET "/assets/wheelmap.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /wheelmap.js - 304 Not Modified (88ms)

Started GET "/assets/i18n/de.js?body=1" for 127.0.0.1 at 2015-12-01 16:41:31 +0100
Served asset /i18n/de.js - 304 Not Modified (3ms)

Started GET "/categories.json" for 127.0.0.1 at 2015-12-01 16:41:32 +0100
Processing by CategoriesController#index as JSON
Category Load (0.4ms) SELECT categories.* FROM categories
Completed 200 OK in 11.6ms (Views: 0.6ms | ActiveRecord: 1.0ms)

Started GET "/nodes.geojson?bbox=13.379287719726562%2C52.474520648527516%2C13.466920852661133%2C52.53590758888872&node_id=" for 127.0.0.1 at 2015-12-01 16:41:32 +0100
Processing by NodesController#index as GEOJSON
Parameters: {"bbox"=>"13.379287719726562,52.474520648527516,13.466920852661133,52.53590758888872", "node_id"=>""}
(3.3ms) SELECT COUNT() AS count_all, status AS status FROM pois WHERE (MBRContains(GeomFromText('POLYGON(( 13.379 52.474, 13.467 52.474, 13.467 52.536, 13.379 52.536, 13.379 52.474))'), pois.geom)) GROUP BY status
Poi Load (0.5ms) SELECT pois. FROM pois WHERE (MBRContains(GeomFromText('POLYGON(( 13.379 52.474, 13.467 52.474, 13.467 52.536, 13.379 52.536, 13.379 52.474))'), pois.geom)) LIMIT 300
Rendered nodes/index.geojson.erb (20.9ms)

Completed 200 OK in 157.6ms (Views: 117.7ms | ActiveRecord: 3.8ms)

**Comment by lennerd** [comment]
Thank you for reporting this. I did the same by importing the schema manually. There is an initial migration creating the providers table. This defenitily need a look.

**Comment by lennerd** [comment]
We maybe need to squash the migrations into one.

**Comment by schultyy** [comment]
We did a bit of research and found out that this problem is caused by active admin. There is an issue for that problem https://github.com/activeadmin/activeadmin/issues/783
