### ISSUE TITLE
can't undo wheelchair classification

### ISSUE THREAD

**Issue by dev-camp-2015** [sozialhelden/wheelmap#84]
if you classify a location as wheelchair = yes/limited/no you can't set it back to status "unknown"

**Comment by Hoverbear** [comment]
We noted this as well and brought it up in a meeting some time ago. I believe the conclusion was that "Some data is better than no data at all".

I'm going to close this due to age/inactivity, if anyone wants to tackle it or objects to this conclusion please just reopen it.
