### ISSUE TITLE
amenity=community_centre spelled wrong (_center) in wheelmap categories

### ISSUE THREAD

**Issue by polarbearing** [sozialhelden/wheelmap#87]
The american spelling (amenity=community_center) of amenity=community_centre is deprecated but used in the categories to create a new entry. 

This has led to Germany having the highest concentration of the deprecated tag now :-(

Test example: http://www.openstreetmap.org/node/3906831259/history

**Comment by lennerd** [comment]
We will definitely take a look into this. Thank you for reporting.

**Comment by 1000miles** [comment]
@lennerd Thank you. As soon as we have access  to the credentials, we will deploy and test it.

**Comment by holgerd** [comment]
is this live now?

**Comment by schultyy** [comment]
It's live now.

**Comment by holgerd** [comment]
yay!
