### ISSUE TITLE
Update dev-env for MacOS, Ubuntu & Vagrant in README.md

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#90]
It takes a lot of time to research, configure and (re-)setup the project wheelmap dependent on the different environments (e.g. Ubuntu, Vagrant, etc.) and packages that are used. 

Currently the [README file](https://github.com/sozialhelden/wheelmap/blob/master/README.md) contains installation instructions mainly for Homebrew which is rather relevant for Mac Users, another example are the instructions for rbenv which does not apply for rvm users or users with no Ruby version managers. An instruction update for different environments might help new contributors to get started faster with this project.

We will write/edit install instructions for:
- [x] MacOS
- [x] Ubuntu
- [x] Vagrant

**Comment by Hoverbear** [comment]
https://github.com/sozialhelden/wheelmap/pull/431 contributes both a working Vagrant box as well as some brief instructions.

**Comment by 1000miles** [comment]
PR #431 merged to master today. Closing.
