### ISSUE TITLE
Search not user friendly: spaces are replaced with "+" when re-searching, leading to 0 results

### ISSUE THREAD

**Issue by schultyy** [sozialhelden/wheelmap#97]
When I search for "12 place voltaire 94200" I get one result. I select the result and the map shows that area.
After that I hit the search button again but then I get no results at all, because the search term was changed to `12+place+voltaire+94200`. From a user's perspective this makes the search functionality difficult to use.

**Comment by 1000miles** [comment]
@Svenyo cc @karolinamakaruk 

Deployed to staging today. Ready for review, opening ticket again. 
// @Hoverbear

**Comment by schultyy** [comment]
Deployed to production. Closing therefore.
